### ISSUE TITLE
Database is locked

### ISSUE THREAD

**Issue by vitobotta** [gilesknap/gphotos-sync#104]
Hi! Daily backup was working fine for a few days, but then following a connection problem it now fails because the database is locked. How to fix? Thanks!

**Comment by gilesknap** [comment]
Are you on Windows?

Does this still persist if you log out and back in?

If so then try deleting or removing the file gphotos.lock from your backup
root.

**Comment by vitobotta** [comment]
Hi! Deleting that file did the trick and was able to update the backup. Thanks a lot! This tool is very handy indeed. :)

**Comment by gilesknap** [comment]
Thanks for letting me know. What is are you using?

**Comment by vitobotta** [comment]
Not sure of what you mean?

**Comment by gilesknap** [comment]
Are you running Windows, Linux or OSX?

**Comment by gilesknap** [comment]
oh yeah. Not what *is* are you using but what *os* are you using!

**Comment by vitobotta** [comment]
Ah OK :D I'm on MacOS Mojave.

**Comment by gilesknap** [comment]
Ok, thanks - maybe it handles locks a little differently. The lock
definitely goes away with the process on Linux.

**Comment by vitobotta** [comment]
It happened only once though and I think there was a temporary connection issue right then.
