### ISSUE TITLE
Running from docker container

### ISSUE THREAD

**Issue by jenyayel** [gilesknap/gphotos-sync#105]
Hi,

I wonder if you have looked into or have any plans to build a docker image from this repo. This way the tool can be run from the container and the photos directory/ies will be mounted via volume. 

I imagine (and willing to try and contribute) that the Docker file will be pretty straight forward (because your setup is easy) and slim.

**Comment by gilesknap** [comment]
Hi, I have not worked with docker yet but your proposal sounds like a good idea. I'm happy to accept contribution of a docker file.

**Comment by gilesknap** [comment]
It looks like @kcgthb has already started this https://hub.docker.com/r/kilian/docker-gphotos-sync

**Comment by kcgthb** [comment]
Indeed, and it should hopefully work.

**Comment by jenyayel** [comment]
Thanks for the link, but I'm confused how the above image can be used without mount points? How it would access `client_secret.json` and the directory to store backup?

**Comment by jenyayel** [comment]
I imagine that the Docker file should be something similar to:
```
FROM python:3.7-buster

RUN mkdir -p /root/.config /config
RUN ln -s /config /root/.config/gphotos-sync 
VOLUME /config

RUN mkdir /storage
VOLUME /storage

RUN pip install gphotos-sync

ENTRYPOINT [ "gphotos-sync" ]
```
I also imagine that the best way would be to build the image from source and not by pulling from pip. What do you think?

I'll try to push PR soonish.

**Comment by gilesknap** [comment]
Thanks for this. I'm on holiday this week but should get a chance to review next week. Cheers.

**Comment by kcgthb** [comment]
@jenyayel Good suggestion! I've updated the [Dockerfile](https://github.com/kcgthb/docker-gphotos-sync/blob/master/Dockerfile)

**Comment by iMerica** [comment]
I was able to get this working with ` docker run -it -v ~/.google-photos-secrets:/config kilian/docker-gphotos-sync <target-dir>`, however once I paste in the oauth token into the CLI I see:

```
08-10 23:46:55 Indexing Google Photos Files ...
08-10 23:46:56
Process failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gphotos/Main.py", line 345, in main
    self.start(args)
  File "/usr/local/lib/python3.7/site-packages/gphotos/Main.py", line 317, in start
    self.do_sync(args)
  File "/usr/local/lib/python3.7/site-packages/gphotos/Main.py", line 292, in do_sync
    new_files = self.google_photos_idx.index_photos_media()
  File "/usr/local/lib/python3.7/site-packages/gphotos/GooglePhotosIndex.py", line 146, in index_photos_media
    favourites=self.favourites)
  File "/usr/local/lib/python3.7/site-packages/gphotos/GooglePhotosIndex.py", line 110, in search_media
    pageToken=page_token, pageSize=self.PAGE_SIZE).json()
  File "/usr/local/lib/python3.7/site-packages/gphotos/restclient.py", line 86, in execute
    result.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://photoslibrary.googleapis.com/v1/mediaItems?pageSize=100
```

**Comment by jenyayel** [comment]
May be you pasted wrong token? I assume that you already tested it without docker and it works fine?

**Comment by tverbeiren** [comment]
@iMerica Using your Dockerfile I got it working on Linux:

```
sudo docker run -it \
  -v `pwd`/config:/root/.config/gphotos-sync/ \
  -v `pwd`/target:/target \
  gphotos-sync /target
```

Please note the addition af the additional volume mapping in order to store the photos on the host, not inside the container.

**Comment by jenyayel** [comment]
thanks @tverbeiren, I just noticed that @iMerica missed the part with storage volume. There is an [example](https://github.com/gilesknap/gphotos-sync/pull/106/files#diff-88b99bb28683bd5b7e3a204826ead112R162) in PR I opened. 

Note, that if you specify `pwd` when mounting, then it depends from which directory you run the command, it is best to specify absolute path. Also, mount names are `/storage` and `/config`, I'm not sure why it worked for you with `/target`.

And to be really picky, avoid running `docker` under `sudo`.

**Comment by tverbeiren** [comment]
Good comments, thanks!

**Comment by henroFall** [comment]
Awesome work. Could use a little cleanup for posterity... I notice that [](https://hub.docker.com/r/kilian/docker-gphotos-sync) still exists, though this project seems to point to [](https://hub.docker.com/r/gilesknap/gphotos-sync) which is a few days newer. Is the older one going to be a dead branch and purged? 
Also, I attempted to use this under Docker for Windows and I believe I have hit a hard blocking point with symlinks and the albums. In my searching, I believe there is no way for a process inside a docker container to create an actual symlink in Windows that will work in the host. It creates a bunch of 2K files that have contents that are the symlink, but Windows sees the files as actual jpgs, not links. If there is a way to configure Windows to make that work, it would be great to have some tips in the documentation. If this is a known issue with the Docker container on Windows, then should it be noted in the documentation? I do have symlinks working in the Windows Host and "everyone" has rights to create them, so I'm not sure what else I could do to let Docker maintain them...

**Comment by gilesknap** [comment]
re the cleanup. Are you referring to the fact that Pypi does not have the latest version? I think the deploy broke silently last time I did a release and I will fix for the next release in a few days. If it is something else then please can you elaborate?

Re symlinks in a Linux image hosted on Windows, I'm afraid I do not know, maybe other contributors have insight?
