### ISSUE TITLE
Works badly when HTTP connections are intermittently unreliable (e.g. connection resets)

### ISSUE THREAD

**Issue by DavidAnderson684** [gilesknap/gphotos-sync#107]
Thank you for this tool. I successfully installed and began downloading, but unfortunately it is not usable on a low-quality Internet connection. I can download plenty of data, but TCP connections get dropped or time out sometimes.

There seem to be some issues this causes.

1) For one, there's no way to specify the number of retries; gphotos-sync just gives up pretty quickly - it doesn't move onto the next file, but quits entirely. So, I put it in a `while true; do ...` loop so that it runs continuously. Unfortunately this didn't work well either; it terminated, apparently believing there was nothing more to do (it had finished indexing and begun downloading photos on the previous run - it had got around a handful occupying about 5 MB, but the account has hundreds, occupying a few Gigabyes).

2) So, I added the option to index again. This appears to then get things going, though adds 2.5 minutes whilst it does that (which is awkward when it's something that will have to run very many times to get all the gigabytes). 

Though having said that... now I'm running again and it doesn't need to re-index, and --skip-index works. I can't yet see a way to distinguish when it needs to re-index and when it doesn't (when it decided nothing needed doing there were no messages about the index being incomplete or corrupt, and the previous runs all appeared to have downloaded the index correctly). i.e. Unfortunately what happened in 1) with the "apparently believing there was nothing more to do" bit doesn't seem easily reproducible.

**Comment by DavidAnderson684** [comment]
Now I'm seeing another awkward behaviour. When the first failure occurs, nothing else then happens; it just hangs. I have to quite and restart. Here's the end of log (level: info):

`
...
08-08 11:21:30 downloading 62 photos/2019/08/IMG_20190802_203313.jpg
08-08 11:21:32 downloading 63 photos/2019/08/IMG_20190802_203304.jpg
08-08 11:21:43 downloading 64 photos/2019/08/IMG_20190802_200719.jpg
08-08 11:21:56 downloading 65 photos/2019/08/IMG_20190802_200717.jpg
08-08 11:22:23 downloading 66 photos/2019/08/IMG_20190802_200714.jpg
08-08 11:22:34 downloading 67 photos/2019/08/IMG_20190802_200708.jpg
08-08 11:22:50 downloading 68 photos/2019/08/IMG_20190802_200706.jpg
08-08 11:23:21 downloading 69 photos/2019/08/IMG_20190802_200704.jpg
08-08 11:24:23 FAILURE 1 downloading photos/2019/08/IMG_20190802_203333.jpg
`

That last entry was now 10 minutes ago.

`find photos/ -mmin -10` finds no changes during that time. Using `lsof` on the process shows 4 TCP connections in a "CLOSE_WAIT" state, and one in "ESTABLISHED".

**Comment by gilesknap** [comment]
The default behaviour is to search for photos with date newer than the last scan date, hopefully this explains some of what you have seen.

I could add an option to control the number of retries and that might help your situation.

Your second post where it hangs while downloading seems a bit ominous. Frankly I don't think the code has been tried against such a flakey connection and there may be an issue with the recovery logic.

I will have a go at creating some tests which emulate intermittent network failure and see if I can reproduce this.

What is making your connection so bad?

**Comment by gilesknap** [comment]
Also you may need to delete your bad IDs file due to the issue in #98

**Comment by DavidAnderson684** [comment]
Thank you.

> What is making your connection so bad?

I think it's congestion on the exchange (ADSL). Things are good early in the day, and get worse progressively as the day goes on.

**Comment by DavidAnderson684** [comment]
Following up on this (I'm still downloading!)... I've not been able to reproduce the situation in which `gphotos-sync` wrongly things it's downloaded everything. Now, each time it resumes, it is carrying on. 

My `gphotos.bad_ids.yaml` is empty (i.e. just the empty enclosure).

It still hangs plenty. For anyone who finds this useful, I'm using these three mini-scripts (all run at the same time in separate consoles) to automatically detect that, and restart, and wipe stale temporary data, and it's working nicely (make sure you navigate so that the current directory is the right one):

1) Run `gphotos-sync` itself: `while true; do pipenv run gphotos-sync --skip-index --log-level=info `pwd`; sleep 5; done`

2) Monitor for progress and kill it (so that it auto-restarts) if there's no progress: `LAST_COUNT=`find photos/ -type f |wc -l`; echo $LAST_COUNT; while true; do du -hsx photos/ ; sleep 300; NEW_COUNT=`find photos/ -type f |wc -l`; echo $NEW_COUNT; if [[ $LAST_COUNT -eq $NEW_COUNT ]]; then killall gphotos-sync; fi;  LAST_COUNT=$NEW_COUNT; done`

3) Remove stale temporary data: `while true; do du -msx photos/; find photos/ -regex '.*/tmp.*' -mmin +20 -ls -exec rm -f {} \;; du -msx photos/; sleep 300; done`

It'd be nice if there was an option to choose how many photos it downloads in parallel . The hard-coded value seems to be 20. This means that if someone in the house wants to do something else at the same time, they may be opening a small handful of TCP connections, and be dwarfed by `gphotos-sync`. As a result, the "background" process of syncing photos is dominating over things you'd want to be more interactive. If it was just downloading 3-4 at a time, it should theoretically go at the same rate overall, but more interactive things would work better. Of course, this is what QoS/traffic-shaping exists for, but that takes rather more time to set up and configure than just reducing the number of parallel downloads.

In general though I seem to have found a way for the tool to work - thank you very much for it. The alternatives looked pretty unusable (e.g. getting Google to generate 2GB zip files that probably you have to download completely in one go).

**Comment by gilesknap** [comment]
Thanks for the update. I can easily add an option for number of parallel
downloads as well as the retry option.

I should also look at a more direct bandwidth throttle option.

I've not got much time to look at these issues this week but hope to spend
time on it next week.

**Comment by gilesknap** [comment]
Please, can you try the branch https://github.com/gilesknap/gphotos-sync/tree/network-issues and see if it helps with your issues.
It adds the options --max-retires and --max-threads.

Next, I will try to create some tests to simulate a flakey network and see if I can reproduce the hang you have seen.

**Comment by gilesknap** [comment]
I've created a test which mocks the requests Session.get function and fails 90% of the time.

The behaviour I get is as expected and the failed files get added to the bad_ids file, the others download. This test passed on all platforms in CI.

This could mean that the issue is lower down in the requests library but that does not seem likely. 

Please, try out the new options and see if they help. This might give us some more insight into the nature of the issue.

**Comment by DavidAnderson684** [comment]
Hi Giles,

Thank you for this project. Unfortunately I am no longer in a position to test it - after several days of running it in the above loop, it completely downloaded everything. When it had done that, I deleted all the data from Google. But I hope other people will benefit from these improvements and am sure they will.

**Comment by gilesknap** [comment]
Ok thanks.

**Comment by gilesknap** [comment]
Be aware that your downloaded videos may not be original quality. See known issues in the read me for details. If this is an issue you should be able to recover then from the Bin.

**Comment by gilesknap** [comment]
Be aware that your downloaded videos may not be original quality. See known issues in the read me for details. If this is an issue you should be able to recover then from the Bin.
