### ISSUE TITLE
Still no workaround for videos not downloading in full quality?

### ISSUE THREAD

**Issue by mrzoops** [gilesknap/gphotos-sync#108]
Do we still not have an option to get our videos in full quality? Is that something that will ever come through? It is capping my videos at 30fps instead of 60 and drastically compressing the files.

**Comment by gilesknap** [comment]
That sucks. We have a bug report in with Google regarding this (see known
issues in README). I've seen the compression change but not the frame rate
reduction.

If you would not mind sharing one of your videos to gilesknap@gmail.com I
can investigate further and at least at more detail to the bug report if
nothing else.

**Comment by mrzoops** [comment]
Absolutely. Would you like the original or the synced file or both?

**Comment by gilesknap** [comment]
I mean could you share it from the Google photos web GUI.

That way I can sync it down to my filesystem using gphotos-sync and see the
differences.

Thanks.

**Comment by gilesknap** [comment]
Thanks for the video. When I download your video directly from the Google Photos Web it is already at 30fps. This implies that is how it is stored and the downgrade occurred at upload time. I'm not sure why this is the case.

However, I just checked a recent 1080p 60fps video of my own and although it still is fine if I directly download from GP Web it is indeed downgraded to 30fps in my gphotos-sync backup.

This is rubbish and I'll update the google issue accordingly.

**Comment by gilesknap** [comment]
I've updated Google with detailed info and an example. Let's hope this has an effect. https://issuetracker.google.com/issues/80149160#comment20

**Comment by mrzoops** [comment]
Yeah, that's strange. My video was 60fps when downloaded from gphotos. Either way I'm glad you saw the issue as well. I wonder why they are restricting the API on this? Thanks for your help.

**Comment by gilesknap** [comment]
> I wonder why they are restricting the API on this?

The conspiracy theory is that Google wants to keep control of your data and lock you in to use of their Photos service. (and with respect to the removal of GPS data, I feel that this is quite possibly true).

With respect to the video file transcode it might just be a bug - in the bug report I referenced above they do claim to have fixed the issue and were asking for examples to show it was still a problem. Now they have an example so maybe it will get fixed.

**Comment by gilesknap** [comment]
wrapping these API bugs into #119
