### ISSUE TITLE
Performance on rasberry pi zero

### ISSUE THREAD

**Issue by gilesknap** [gilesknap/gphotos-sync#11]
@pierrerigal reports:-

![capture d ecran 2017-11-27 a 07 59 41](https://user-images.githubusercontent.com/895267/33254439-14802d74-d349-11e7-9026-0f304b714d98.png)

Still running after a night. Has indexed only 16K photos in about 8hours. 

------------
Maybe I should build the database from my mac, and then let raspberry only do overnight updates.

**Comment by gilesknap** [comment]
That seems very slow, on an old i5, I index 100,000 in about 20 mins and currently the code is only single threaded.
However, the memory and processor use don't look that bad, could it be the network? I guess you are reading from google and writing db to the NAS over wifi? 

There is a good chance that writing the DB journal is the issue. Two ideas come to mind:-
- Give the option of keeping the SQL journal in memory (and also tune how often transactions are committed - currently all of indexing is a single transaction)
- allow DB file location to be separate to the backup data so it could be located in local disk

If you want to try indexing on the Mac and downloading on the Pi then you can use the --index-only and --skip-index options respectively.

I have not tested on a Mac yet, if you have issues please can you report in a new ticket.

Thanks.

**Comment by pierrerigal** [comment]
Oups I cross post on old closed ticket, sorry.

But I think problem is LAN and wifi. Writing DB over LAN on a USB drive attached to a router is not the best perf architecture :)

"allow DB file location to be separate to the backup data so it could be located in local disk" -> this is the good option I think. I will try to index localy first and confirm.

**Comment by pierrerigal** [comment]
Ok this is way faster :)

But it's not an option actually, because I saw that you store full path to media in SyncFiles table, so I can't move my db after synching.

Why not only store relative path in database ? That will allow us to move our backup later.

**Comment by gilesknap** [comment]
Just to confirm. You ran indexing locally on the Pi and it was fast?
If that is the case then I can easily provide an option to specify location
of the db.
Re the full path issue, I am aware of this and will address it in #12

**Comment by pierrerigal** [comment]
Yes indexing locally is faster on the Pi.

**Comment by gilesknap** [comment]
Great. I'll add the option tonight.

**Comment by gilesknap** [comment]
In fact that was a quick lunch break job. Please try latest master.

**Comment by pierrerigal** [comment]
Took 5 min to run it again. Wait 'n see. 

`gphotos-sync --db-path=var/ /media/toshiba/ > var/gphotos.log &`

**Comment by pierrerigal** [comment]
It's indexing ~1200 photos per min and keep running. 

10K so far. 

We can tell it's ok.

**Comment by gilesknap** [comment]
I believe this one is sorted now.

**Comment by gilesknap** [comment]
--db-path is awesome. My sync runs way faster with the db on my SSD.
