### ISSUE TITLE
Photos downloaded are compressed

### ISSUE THREAD

**Issue by fernando-lopez** [gilesknap/gphotos-sync#111]
Sync photos in the computer are downloaded.  When I try to sync / Download photos saved in RAW format (around 25 Mb per photo in the cloud) those are downloaded in JPEG format (around ~900Kb in the computer)

I have seen it's a limitation of the API. I have been playing with the API and there is no way to workaround or skip this limitation. https://developers.google.com/photos/library/guides/access-media-items#base-urls

**Comment by gilesknap** [comment]
I guess I need to add this to the known issues list. There has been a bit more activity from Google on the bug forum in the last few days. Who knows? they might even fix this.

**Comment by gilesknap** [comment]
wrapping these API bugs into #119
