### ISSUE TITLE
gphotos-sync does not work on smb mount "database is locked"

### ISSUE THREAD

**Issue by golserma** [gilesknap/gphotos-sync#113]
I use docker for gphotos-sync and have the storage volume on a samba share.
If you do this gphotos-sync fails giving "sqlite3.OperationalError: database is locked"

A simple workaround is using --db-path /config/database
Maybe you can add this to the known issues?

**Comment by gilesknap** [comment]
I do not know docker at all well, @jenyayel provided the build script. So please excuse the following questions:
(a) do we understand why this issue occurs?
(b) is /config/database persisted or does it mean recreating the database on each execution?

**Comment by golserma** [comment]
I don't use your dockerfile
I have created my own image since I need do access the samba share as user https://gist.github.com/golserma/6475d36e0fc593b95ae3697cabd809dd

For me /config is a separate volume and it is persitent

**Comment by gilesknap** [comment]
OK, Thanks.

I have found some references to this issue elsewhere e.g. https://github.com/docker/for-win/issues/11.

Are you using CIFS to mount your Samba drive and if so can you use the nobrl flag to the mount as per the above issue?

**Comment by golserma** [comment]
Was not able to create the symlinks for the albums on the samba share.
I switched to NFS now. On NFS symlinks and the database works just fine.

Maybe there should be a check if creating a symlink is possible on the startup and if not warn the user and fail

**Comment by gilesknap** [comment]
Yes, agreed on the check at startup. Will implement soon.

**Comment by gilesknap** [comment]
So I assume yuo got the DB lock working on Samba and then fail with the symlinks? Did you use the nobrl flag to do so?

Thanks.

**Comment by golserma** [comment]
I never got symlinks working on my samba share. -> I did not try the nobrl flag

**Comment by gilesknap** [comment]
I'm closing this and rolling up the requirement to check for symlink capability into #110
