### ISSUE TITLE
Add argument for client_secrets.json

### ISSUE THREAD

**Issue by matthewmmorrow** [gilesknap/gphotos-sync#114]
I've been trying to setup gphotos sync on my Hass.io raspberry pi. That worked ok but then I switched to running it on my Synology DS218j NAS. This is in Python and not using docker. In both cases it would be helpful to be able to specify a path for the client_secrets.json instead of forcing it to be in a specific location.

This is a great project. It's working well on my NAS

**Comment by gilesknap** [comment]
That is easy to do. I'll add the option soon.

**Comment by gilesknap** [comment]
I've added the option --secret. It's in feature at the moment but will go in the next release.
