### ISSUE TITLE
multiple accounts

### ISSUE THREAD

**Issue by gosugimoto** [gilesknap/gphotos-sync#120]
I've got the other .json file for a separate account now downloaded.  Do I place this in the same folder as the other one, but with a separate name, or into the separate download folder?  I'd like to keep both accounts downloading...

**Comment by gilesknap** [comment]
Hi,

If you want to sync two accounts then do it to two separate root folders,
each with its own credentials (json) file.

**Comment by gosugimoto** [comment]
do i need to install 2 instances of gphotos-sync? I just don't know where
to save the other json file...

sorry, very newbie to all this still
--
iamgo.net

**Comment by gilesknap** [comment]
Maybe I did not understand the original question.

There are two json files. 

- The client secret that registers your copy of gphotos-sync as a user of the Google Photos API, this file goes in ~/.confg/gphotos-sync on linux (see readme for other platforms). This you only need once. To create this file you have to interact with the Google Developer Console.
- The user credentials file. This gets created in the root folder of the backup as .gphotos-token. This you would have one of for each account you are syncing. For account that you sync you would run 'gphotos-sync <root_folder>'. The first time you do this in each folder you will be taken through the Google Authentication page and provide the login details for the user account.

HTH

**Comment by gosugimoto** [comment]
Thanks! So even if one account is xx@abc.com and the other zz@123.com, they
use the same JSON file?  I originally created a JSON from the ABC.com
account.

The 2nd half makes sense to point to a different directory.  I'll perhaps
just give a go.

Thanks!

**Comment by gilesknap** [comment]
You only need to go to Google Developer Console and download a json file
once and put it in the config directory.

Each user you want to sync, provide a new root directory parameter to
gphotos-sync, when you first run against a new directory you will be asked
which user you want to sync (via the authentication/authorization pages).
This step will automatically create a token file for you in that folder.
(this file is also a JSON file and that is why I have managed to really
confuse you! apologies)

**Comment by gilesknap** [comment]
@gosugimoto please close this issue if your issue has been resolved. Thanks.

**Comment by gilesknap** [comment]
I think we are OK with this one. Closing

**Comment by gosugimoto** [comment]
Hi,
Sorry to open this up again, but trying to do another sync to another account, I get this error:

```
Error 403: org_internal
This client is restricted to users within its organization.
```

The first account syncing is my own domain, and another is a gmail.com address.  Whether there is a different step I need to take?

**Comment by gilesknap** [comment]
So, do you have two different root directories for each of the accounts you are trying to sync?

The error sounds to me like you have mixed up tokens and databases somehow.

i.e. if you:
- performed sync to a directory and provided the login for account a. 
- Did the sync again but used --new-token and provided different account details
- or
- synced to two folders with two accounts
- then swapped the token files

Then you would get errors trying to access items with remote ids from a different account

**Comment by gosugimoto** [comment]
Hmmm.  So the first account (owndomain.com) is set to sync into

gphotos-sync /Volumes/photography/phone/user1/mobile

I ran the same script, but then just changed the directory to:
gphotos-sync /Volumes/photography/phone/user2/mobile

Then I get the error.  I haven't done any of the new token or share token.

**Comment by gilesknap** [comment]
The first time you sync to a given folder you will be asked to authenticate your Google account and authorize gphotos-sync to use the Google Photos API. The result of this is a file called .gphotos.token in the root folder. If there is somehow a mismatch between .gphotos.token and the media index in gphotos.sqlite then I can see you getting this error. My previous response was an attempt to describe some scenarios where that mismatch might occur.

If you would not mind sharing your script, I might be able to see if there is an issue with that.

**Comment by gosugimoto** [comment]
I haven't altered any scripts, but happy to share - just don't know what to
share... sorry! Quite a newbie still.

I tried a search for the token file, but can't find it.  The actual
gphotos-sync-master folder sits on my mac main drive and the sync folder is
on an external volume with these directories:


*/Volumes/photography/phone/user1/mobile*
*/Volumes/photography/phone/user2/mobile*

The commands I run are:


*cd /Users/username/Documents/_temp/gphotos-sync-master *
*source .venv/bin/activate*

*gphotos-sync /Volumes/photography/phone/user1/mobile*

*gphotos-sync /Volumes/photography/phone/user2/mobile*

**Comment by gilesknap** [comment]
It does not look like you are doing anything unusual so I'm a bit stumped.

The tokens files start with a '.' and are therefore hidden, (their contents
is private to since it allows authentication to Google). However, since
you are running gphotos-sync with no additional parameters, I can't see how
it is possible for you to have an issue with mixing up these token files.

Do you still get the problem now? is it still only with one of the accounts?

(If the problem has gone away, then I assume it was a temporary issue with
Google service.)

**Comment by gosugimoto** [comment]
So I did the show hidden files in finder, and see the .token file.  It only
exists in the main folder of user1, but not in the user2 folder structure.
Is it something to do with the original api being part of a google custom
domain?  I have one of the old Google managed domain things for my own url
--
iamgo.net

**Comment by gosugimoto** [comment]
Just to confirm, it's only with the first account user1 - that one works effortlessly - thank you!  I just can't seem to get past the authorisation for the second account.  I past the link from terminal, and get this error.

https://snipboard.io/7Ur4lI.jpg

**Comment by gilesknap** [comment]
OK, now this is making some sense. Clearly our authorization approach does not work with a Google managed domain. I'm not sure if I'll be able to fix this.

It is possible than when you create your client secret token that you can allow it to work with managed domains. I'll have a go this evening and see if I can find any options in the process for this.

**Comment by gosugimoto** [comment]
Sorry, just to further clarify, it's working with a google managed domain.
But when I try to add another account which is just a gmail.com account, it
won't let me.  Whether there is a way to associate a separate token file
for the separate user?

User 1 - google managed domain (myowndomain.com) // this one is working fine
User2  - user2@gmail.com address // trying to add this one

Thanks for your help as always!
--
iamgo.net

**Comment by gilesknap** [comment]
That makes even more sense!

You created your client secret using your domain account. It only authorises gphotos-sync to connect to accounts in your domain.

I suggest you go through the client secret generation again but use a non-domain account to make it.  This will give access to non-domain accounts and with luck will also allow domain accounts.

Do keep the original client-secret.json file because if it turns out that you need two client secrets then I can explain how to do that too.

**Comment by gosugimoto** [comment]
Great.  I'll give it a go tonight.  Does it interfere with the mysql
database or downloaded items to date?
--
iamgo.net

**Comment by gilesknap** [comment]
Hi - it should not interfere with your DB. When you have a new secret file you will need to reauthenticate the user and get a new .gphotos.token. I have never tried this so you may also need to delete the current token file. If you are worried about your DB, take a copy of the .db file first. It is just the one file ending in .sqlite

**Comment by gosugimoto** [comment]
So I removed (and backed up just in case) the client.json file and created
a new one from the gmail.com user.  I ran the script, and it looks like
that is piping along well and indexing.

I ran the script again and this time to the other folder of the user (
owndomain.com) and I get this error..

Process failed.

Traceback (most recent call last):

  File
"/Users/gomachan/Documents/_temp/gphotos-sync-master/.venv/lib/python3.7/site-packages/requests_oauthlib/oauth2_session.py",
line 395, in request

    http_method=method, body=data, headers=headers)

  File
"/Users/gomachan/Documents/_temp/gphotos-sync-master/.venv/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/clients/base.py",
line 198, in add_token

    raise TokenExpiredError()

oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File
"/Users/gomachan/Documents/_temp/gphotos-sync-master/.venv/lib/python3.7/site-packages/gphotos/Main.py",
line 344, in main

    self.setup(args, db_path)

  File
"/Users/gomachan/Documents/_temp/gphotos-sync-master/.venv/lib/python3.7/site-packages/gphotos/Main.py",
line 208, in setup

    photos_api_url, self.auth.session)

  File
"/Users/gomachan/Documents/_temp/gphotos-sync-master/.venv/lib/python3.7/site-packages/gphotos/restclient.py",
line 36, in __init__

    service_document = self.auth_session.get(api_url).json()

  File
"/Users/gomachan/Documents/_temp/gphotos-sync-master/.venv/lib/python3.7/site-packages/requests/sessions.py",
line 546, in get

    return self.request('GET', url, **kwargs)

  File
"/Users/gomachan/Documents/_temp/gphotos-sync-master/.venv/lib/python3.7/site-packages/requests_oauthlib/oauth2_session.py",
line 408, in request

    self.auto_refresh_url, auth=auth, **kwargs

  File
"/Users/gomachan/Documents/_temp/gphotos-sync-master/.venv/lib/python3.7/site-packages/requests_oauthlib/oauth2_session.py",
line 374, in refresh_token

    self.token = self._client.parse_request_body_response(r.text,
scope=self.scope)

  File
"/Users/gomachan/Documents/_temp/gphotos-sync-master/.venv/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/clients/base.py",
line 415, in parse_request_body_response

    self.token = parse_token_response(body, scope=scope)

  File
"/Users/gomachan/Documents/_temp/gphotos-sync-master/.venv/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py",
line 425, in parse_token_response

    validate_token_parameters(params)

  File
"/Users/gomachan/Documents/_temp/gphotos-sync-master/.venv/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py",
line 432, in validate_token_parameters

    raise_from_error(params.get('error'), params)

  File
"/Users/gomachan/Documents/_temp/gphotos-sync-master/.venv/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/errors.py",
line 405, in raise_from_error

    raise cls(**kwargs)

oauthlib.oauth2.rfc6749.errors.UnauthorizedClientError:
(unauthorized_client) Unauthorized

11-06 19:46:04 Done.

logout

Saving session...

...copying shared history...

...saving history...truncating history files...

...completed.

Deleting expired sessions...none found.


[Process completed]


--
iamgo.net

**Comment by gilesknap** [comment]
I think from this error that you are going to require two client tokens. This seems a little unfortunate but is not too hard to do.

For your domain account, you need to point at the backed-up client secret JSON file using the option --secret.

Hopefully, that should get you backing-up both accounts.

**Comment by gosugimoto** [comment]
I'm trying both

gphotos-sync /Volumes/photography/phone/go/mobile --secret

and

gphotos-sync --secret /Volumes/photography/phone/go/mobile


I get this error:

gphotos-sync: error: unrecognized arguments: --secret
--
iamgo.net

**Comment by gosugimoto** [comment]
hmmm i just did --new token, and put a new token for the managed domain and
it looks like it's working!
i'll keep an eye on it..
--
iamgo.net

**Comment by gilesknap** [comment]
Awesome. Hopefully, you don't need -- secret in that case, I should have
suggested --new-token first.

I think the reason --secret did not work will be because you do not have
the latest gphotos-sync?

**Comment by gosugimoto** [comment]
I did update with the latest, but not sure if I correctly updated the
script...is there a terminal command way of updating?

**Comment by gilesknap** [comment]
cd to the install directory and run 
pipenv install 1.10.3

If you look in the log file it will tell you at the top which version it is running.

**Comment by gosugimoto** [comment]
Hmmm, doesn't seem to work.  I just downloaded from github, unzipped and
replaced the directory and files...
--
iamgo.net

**Comment by gilesknap** [comment]
I think I recall you are running on Mac. I don't remember how you installed gphotos-sync, please check the output of the log to make sure that the approach you used did actually update the code you are running (if you had used pipenv, then just copying the files over might not have worked).

**Comment by gosugimoto** [comment]
This is what I did to do the initial install:

   - cd to the gphotos directory
   - brew cleanup
   - brew update
   - brew upgrade python3
   - python3 -m pip install virtualenv
   - virtualenv .venv -p python3
   - source .venv/bin/activate
   - pip install .
   - python3 ./gphotos-sync --help

--
iamgo.net
