### ISSUE TITLE
Emojis in album name cause an UnicodeEncodeError

### ISSUE THREAD

**Issue by ksquared101** [gilesknap/gphotos-sync#121]
I have a few albums that have emoji characters in the title. When trying to sync these albums it throws an error. Here is the error message I get, "UnicodeEncodeError: 'charmap' codec can't encode characters in position 78-79: character maps to <undefined>".

**Comment by gilesknap** [comment]
Thanks, I already filter characters that are illegal for the filesystem but
guess I'm not covered for everything.

I'll take a look at a fix for this. Please, can you let me know which
operating system you are using?

**Comment by ksquared101** [comment]
Windows 10, version 1903

**Comment by gilesknap** [comment]
@ksquared101 which platform are you on, please? I have discovered that my filesystem on Linux is OK with emojis 🥺. Hehe.

I think I'll add this issue to the filesystem checks in #110.

```
(master) [giles@gklinux gphotos-sync]$ echo hello >  🥺
(master) [giles@gklinux gphotos-sync]$ ls
🥺               dist        gphotos-sync           MANIFEST.in   setup.py
AUTHORS          Dockerfile  gphotos_sync.egg-info  Pipfile       test
build-docker.sh  etc         __init__.py            Pipfile.lock  travis.log
ChangeLog        gphotos     LICENSE                README.rst
(master) [giles@gklinux gphotos-sync]$ 

```

**Comment by gilesknap** [comment]
Closing and rolling up into #110
