### ISSUE TITLE
Requesting that album paths not change with each sync

### ISSUE THREAD

**Issue by apastel** [gilesknap/gphotos-sync#123]
Was wondering if it's possible to prevent the album paths from changing each time new photos are synced.

For example, the directory 
`albums/2019/0829 Concert Photos` will change to
`albums/2019/0905 Concert Photos` the next time it is synced with new photos. The inconvenience here is that an application I am using is referencing this path, and I have to update the reference each time new photos are synced.

I've looked through the usage options but I don't see one that will keep the album paths consistent. (e.g. would prefer just `albums/Concert Photos`, or a static date that does not change.)

**Comment by gilesknap** [comment]
:-)
I went to some trouble to make the album names change when new photos were
put in.

However, I see that this use case is not for everyone.

I propose we add an option to switch between album dates based on:- the
earliest photo / the latest photo.

**Comment by gilesknap** [comment]
I have added the option --album-date-by-first-photo.

It's in the master branch and will roll into the next release in a week or so.

This should give you the behaviour you are looking for although note folder name will change if you add photos that are earlier than the first photo. There is no way to get around this and also continue to support the ability to totally flush the index and recover it (i.e. all info in the index is discoverable from the Google Photos API)
