### ISSUE TITLE
Bad IDs

### ISSUE THREAD

**Issue by wills721** [gilesknap/gphotos-sync#125]
I have a total of 76 'Bad Ids' issues.  I read in comments this is a Google issue.  Any workaround?

09-09 15:41:02 WARNING: skipped 76 files listed in /mnt/Photos/gphotos.bad_ids.yaml

**Comment by gilesknap** [comment]
I was under the impression that the cause of this issue had been fixed by
Google. I don't get bad IDs anymore. Are these video files by any chance?

I do have an outstanding bug in my code which is that intermittent network
errors might be mistaken for 'Bad IDs'. To check if this is happening you
can just delete the bad ids file and re-run gphotos-sync.

**Comment by wills721** [comment]
All Videos yes.  Either .MOV or .VOB extension but mostly .MOV

**Comment by gilesknap** [comment]
Please can delete your bad Ids file from the roor folder, run again and
send your logfile from your root folder to gilesknap@gmail.com.

Thanks.
giles.

**Comment by wills721** [comment]
I did that.  It is strange.  The first time I re-ran the badid files re-appeared.  Same exact number of files. However the next few times the bad id file did not re-appear (after removing it) however the files in the bad id file (original and next one) did not download.  Its as if the bad id MOV & VOB files are now seen as already downloaded?

**Comment by gilesknap** [comment]
I should have mentioned that you will need to use the  --rescan option,
otherwise, it will only look for files newer than the previous scan date.

Please resend the log file when you try that. Thanks.

**Comment by wills721** [comment]
Email sent to your gmail

**Comment by gilesknap** [comment]
Thanks for the extra info. It does look like you are getting HTTP 500 errors downloading those video files. So this does look like the Google issue that I thought was fixed.

One more question. How long ago did you first run gphotos-sync? If it indexed the items before the fix (a few weeks ago) then they will need to be re-indexed. I think the bug used to deliver bad remote IDs and the DB saves these and tries to use them to get the download URL.

If you do a gphotos-sync with option --flush-index this will rescan everything and re-index the offending files. If this does not fix it then we need to compile a report to Google.

**Comment by wills721** [comment]
So,  sadly,  the --flush-index run ended the same.  Same 76 files failed.  Same yaml results I sent you :(

**Comment by gilesknap** [comment]
OK, we have confirmed that the Google API bug still exists even though it is fixed for all of my videos.

Please, could you place a few of the videos that you are willing to share into a publicly shared album and update the bug https://issuetracker.google.com/issues/116842164 with a link to the album?

Many thanks - sorry we did not resolve this but Google was responsive on this bug before so you may be lucky.

**Comment by gilesknap** [comment]
closing as a duplicate of #119 (updated with a link here)

**Comment by wills721** [comment]
So I made a comment up on the google site but did not yet upload any sample.  I'm not crazy about uploading my videos -- they are home movies of my kids mostly.  However,  if you read to the end of the google issue thread seems I am not alone.

**Comment by gilesknap** [comment]
OK, thanks for that. Let's hope they address it.

If you don't mind a couple of Google engineers looking at the videos then
there is an option to give them permission to look at photos in your
account. They did this for my account. If you are OK with that then mention
it on the ticket and they may contact you directly to arrange.

Cheers,
giles.

**Comment by wills721** [comment]
I'm good with that.  I just left that comment up there.

**Comment by gilesknap** [comment]
This got a response from google on buganizer - result.

**Comment by gilesknap** [comment]
It looks like  https://issuetracker.google.com/issues/116842164 has been fixed by Google.

**Comment by compman723** [comment]
I can't seem to locate the Bad ids file while on windows.  Can someone point me to the location of this file?  Thanks!

**Comment by gilesknap** [comment]
Hi, If you are running a recent version of gphotos-sync then there is no badids file any more, this is because the bug in google api is fixed. 

If gphotos sync gets an error it always reports it now, rather than collecting a list of bad files that will never work.

**Comment by compman723** [comment]
Thank you for the reply.  Is there a way to retrigger a download if there
is a failure?  or retry all the failures?  Also view all the failures?

**Comment by wills721** [comment]
Also,  just so I'm sure I have it,  what version of gphotos-sync stopped writing a badids file and what is the most recent version?

**Comment by gilesknap** [comment]
The current version is 2.12.4 (but ironically the version number reporting is broken in this release).
2.10.4 Was the first release without bad ids.
The bad ids file would always have appeared in the root of your target folder.

To retrigger scan and downloads use the --rescan option.
