### ISSUE TITLE
Size disparity

### ISSUE THREAD

**Issue by wills721** [gilesknap/gphotos-sync#126]
After completing an entire download of my Google Photos library the total size I see is 250GB.  However,  when I look up on Google Google tells me my Google Photos size is 434GB.  So, for starters I have 76 bad-id files which do not come down and also I do understand and have read that when videos are downloaded the transcoding reduces the size -- is it possible however that the total size would be this much off even given the latter? (the 76 files missing I have not yet tallied up in terms of size)

**Comment by gilesknap** [comment]
If you go to https://myaccount.google.com/dashboard and click on Google photos it will tell you how many you have. You can verify the count against what gphotos-sync has downloaded.

My library is about 1/2 the size downloaded because of the video file compression issue. Most videos are about 1/10th the size!

**Comment by wills721** [comment]
Ok.  Sent.

**Comment by gilesknap** [comment]
Your log shows that the Google API indexes 89,243 items in your library and fails to download 76 of them due to 'bad ids'. 

I'm not clear on what happens with sharing or with Dashboard, here are my numbers
- Google Dashboard
  - My account shows 123,754 items
  - My wife's account shows 108,528 items
- gphotos-sync:-
  - indexes: 103,824
  - local filesystem files count: 103,831 (probably a few deleted photos but no --do-delete)

So there is some anomaly here. This requires investigation but I'm pretty sure that I do not have any missing photos since I did multiple comparisons with different means of synchronization as I was developing gphotos-sync. My feeling is that the Dashboard figure is wrong, but I'm not sure. One possibility is that there have been many duplicates uploaded to my account due to using dodgy sync methods via Google Drive - Google photos eliminates duplicates but maybe the count does not?

I just tried syncing my wife's account and gphotos-sync indexed 104000 files. Nothing quite adds up!

I'm going to do some samples of years and count the files in them using the google web to see if the count matches my local sync.

**Comment by wills721** [comment]
At least its not just me.  You are closer though.

**Comment by gilesknap** [comment]
I'm doing a Google Takeout of my photos so I can make a scientific comparison.

**Comment by gilesknap** [comment]
it takes a long time to download and unpack a takeout. still going ...

**Comment by wills721** [comment]
Been there.  Done that.  While you are at it -- I have a significant number of photos and videos which have no modified date.  PNG,  MTS2,  IMG files.  I have done the take-out before and I have seen it there so I do not believe this issue is gphotos-sync.  Wondering if you see that too.

**Comment by gilesknap** [comment]
Some progress on this.

I have checked my Takeout count and it almost matches what Google Dashboard says (Dashboard shows 1124 more items than takeout).

HOWEVER: the Takeout duplicates any items that are in Albums. See below for an example file that appears 3 times in my Takeout.

```
[giles@gklinux Takeout]$ find . -type f | perl -ne 'print $1 if m/\.([^.\/]+)$/' | sort -u
3ga
3gp
avi
AVI
bmp
gif
HEIC
html
jpeg
jpg
JPG
json
m4v
mov
MOV
mp4
mpg
MTS
png
PNG
wmv
[giles@gklinux Takeout]$ find . -not -name "*.json"  -type f | wc
 124883  329923 6176887
[giles@gklinux Takeout]$ find .  -name '2013-01-28 11.59.15.jpg'
./Google Photos/Alan and Noah/2013-01-28 11.59.15.jpg
./Google Photos/2013-01-28/2013-01-28 11.59.15.jpg
./Google Photos/2016-12-25/2013-01-28 11.59.15.jpg
[giles@gklinux Takeout]$ ls -l './Google Photos/Alan and Noah/2013-01-28 11.59.15.jpg' './Google Photos/2013-01-28/2013-01-28 11.59.15.jpg' './Google Photos/2013-01-28/2013-01-28 11.59.15.jpg'
-rw-rw-r-- 1 giles vboxusers 1009915 Jul 18  2018 './Google Photos/2013-01-28/2013-01-28 11.59.15.jpg'
-rw-rw-r-- 1 giles vboxusers 1009915 Jul 18  2018 './Google Photos/2013-01-28/2013-01-28 11.59.15.jpg'
-rw-rw-r-- 1 giles vboxusers 1009915 Jul 18  2018 './Google Photos/Alan and Noah/2013-01-28 11.59.15.jpg'
```
Now if I count items in my gphotos-sync folders:-
```
[giles@gklinux GilesPhotos]$ find albums -type l | wc
  17321   75995 1114098
[giles@gklinux GilesPhotos]$ find photos/ -type f | wc
 103843  138003 3657287
```
They add up to 121,164 items. That is only 3719 files short and this may be explained by the fact that takeout includes shared folders and gphotos does not sync unamed shared folders.

For a definitive answer I'm going to run a gphotos-sync --compare against the Takeout, but it seems my exif extraction code is broken at the moment so needs a fix ...

**Comment by wills721** [comment]
Would the EXIF issue explain why there may be missing modified dates for me?

**Comment by gilesknap** [comment]
I would say no. Normally gphotos-sync does nothing with EXIF.

When it is asked to do a comparison with another folder it uses EXIF to
match files to each other.

Otherwise, it just downloads blobs from Google with whatever EXIF is
already in them (caveat that Google seems to mess with at least the GPS
info).

**Comment by gilesknap** [comment]
Sorry I think I misunderstood - you mean are photos in takeout missing EXIF. Yes maybe, but also there will be some that didn't have EXIF when unloaded in the first place. My comparison code use to cope with missing EXIF but it looks like an update to the exif library has changed this.

**Comment by wills721** [comment]
Google is beyond my understanding.  Why any file I upload to Google would come down any different than what I uploaded -- there should be a law.

**Comment by gilesknap** [comment]
Yes. I believe it is a deliberate hobbling of the API so that we are compelled to use Google Photos Web. They comply with Data Protection Law via Takeout but that is extremely clunky.

**Comment by wills721** [comment]
Well -- if you don't get out of takeout what you put in to Google is it really complying :(

**Comment by gilesknap** [comment]
So I think they are complying. Do you have cases in takeout where you think the metadata is different to what you uploaded? I don't see this - I only see it in what is downloaded via the Google Photos API with gphotos-sync.

**Comment by gilesknap** [comment]
This has been a long investigation and I am now reasonably happy that I have resolved it. This kind of question 'are there any files missing from this huge data set' are quite hard to answer and I spent a great deal of time on them when developing gphotos-sync. Having said that I have never before looked at Google Dashboard or attempted comparison with the takeout contents.

I tried to use gphotos-sync --comparison (now fixed) but this feature needs work to be useful in this case. It always shows a missing file for each duplicate it finds and there was way too much noise.

So I took a more basic approach and came up with this script that you can also try (if you are not on Linux then try to get a bash shell running on your platform - it will be the easiest way to make this work.)
```
#!/bin/bash
TAKEOUT='/media/Data/Takeout/Takeout/Google Photos/'
GPHOTOS='/media/Data/GilesPhotos/'

echo TAKEOUT folder ${TAKEOUT}
echo number of photos in date folders
find "${TAKEOUT}" -path "${TAKEOUT}????-??-??*" -type f -not -name "*.json" | wc -l 
echo number of photos in album folders
find "${TAKEOUT}" -path  "${TAKEOUT}????-??-??*" -prune -o -type f -not -name "*.json" -print | wc -l
echo number of photos in total
find "${TAKEOUT}" -type f -not -name "*.json" | wc -l
echo
echo 'number of burst shot files (excluding the 1st one) - these are not available to Google Photos API'
find "${TAKEOUT}" -path  "${TAKEOUT}????-??-??*" -type f -name "*_0??.jpg" | grep -v _001 | wc -l
echo
echo


echo gphotos-sync folder ${GPHOTOS}
echo number of photos
find "${GPHOTOS}photos"  -type f  > /tmp/photo_list.txt
wc -l /tmp/photo_list.txt
echo number of album links to photos
find "${GPHOTOS}albums" -type l > /tmp/album_list.txt
wc -l /tmp/album_list.txt
echo number of photos in total
cat /tmp/photo_list.txt /tmp/album_list.txt | wc -l
```

My results are as follows:-
```
TAKEOUT folder /media/Data/Takeout/Takeout/Google Photos/
number of photos in date folders
104927
number of photos in album folders
19956
number of photos in total
124883

number of burst shot files (excluding the 1st one) - these are not available to Google Photos API
1418


gphotos-sync folder /media/Data/GilesPhotos/
number of photos
103860 /tmp/photo_list.txt
number of album links to photos
17321 /tmp/album_list.txt
number of photos in total
121181
```
Essentially, with a little margin, the numbers match up so I'm pretty happy. Note that gphotos-sync does not backup un-named shared albums so there are a few less album entries and also that burst shot files are know not to be available via the API.

Takeout and Google Dashboard both count album entries as extra photos while Google Photos and gphotos-sync do not waste disk space on duplicates.
