### ISSUE TITLE
Unable to install from git repository with pipenv

### ISSUE THREAD

**Issue by michalhainc** [gilesknap/gphotos-sync#130]
Hi, I failed to install from git repo using python 3.7.3 on armbian with pipenv

It failed with "No matching distribution found for pywin32==225"
Without pipenv it installed fine.

output of installation: 

	root@nas:~/gphotos-sync# python3.7 -m pipenv install .
	Creating a virtualenv for this project…
	Pipfile: /root/gphotos-sync/Pipfile
	Using /usr/local/bin/python3.7 (3.7.3) to create virtualenv…
	⠼ Creating virtual environment...Already using interpreter /usr/local/bin/python3.7
	Using base prefix '/usr/local'
	New python executable in /root/.local/share/virtualenvs/gphotos-sync-wbnW4jFe/bin/python3.7
	Also creating executable in /root/.local/share/virtualenvs/gphotos-sync-wbnW4jFe/bin/python
	Installing setuptools, pip, wheel...
	done.
	✔ Successfully created virtual environment!
	Virtualenv location: /root/.local/share/virtualenvs/gphotos-sync-wbnW4jFe
	Installing .…
	✔ Installation Succeeded
	Installing dependencies from Pipfile.lock (c7c0c4)…
	An error occurred while installing pywin32==225 --hash=sha256:0443e9bb196e72480f50cbddc2cf98fbb858a77d02e281ba79489ea3287b36e9 --hash=sha256:09bbe                7cdb29eb40ab2e83f7a232eeeedde864be7a0622b70a90f456aad07a234 --hash=sha256:0d8e0f47808798d320c983574c36c49db642678902933a210edd40157d206fd0 --hash=                sha256:0db7c9f4b93528afd080d35912a60be2f86a1d6c49c0a9cf9cedd106eed81ea3 --hash=sha256:749e590875051661ecefbd9dfa957a485016de0f25e43f5e70f888ef1e29                587b --hash=sha256:779d3e9d4b934f2445d2920c3941416d99af72eb7f7fd57a63576cc8aa540ad6 --hash=sha256:7c89d2c11a31c7aaa16dc4d25054d7e0e99d6f6b24193cf6                2c83850484658c87 --hash=sha256:81f7732b662c46274d7d8c411c905d53e71999cba95457a0686467c3ebc745ca --hash=sha256:9db1fb8830bfa99c5bfd335d4482c14db5c6                f5028db3b006787ef4200206242b --hash=sha256:bd8d04835db28646d9e07fd0ab7c7b18bd90e89dfdc559e60389179495ef30da --hash=sha256:fc6822a68afd79e97b015985                dd455767c72009b81bcd18957068626c43f11e75 --hash=sha256:fe6cfc2045931866417740b575231c7e12d69d481643be1493487ad53b089959! Will try again.
	  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 14/14 — 00:00:20
	Installing initially failed dependencies…
	[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 1992, in do_install
	[pipenv.exceptions.InstallError]:       skip_lock=skip_lock,
	[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 1253, in do_init
	[pipenv.exceptions.InstallError]:       pypi_mirror=pypi_mirror,
	[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 859, in do_install_dependencies
	[pipenv.exceptions.InstallError]:       retry_list, procs, failed_deps_queue, requirements_dir, **install_kwargs
	[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 763, in batch_install
	[pipenv.exceptions.InstallError]:       _cleanup_procs(procs, not blocking, failed_deps_queue, retry=retry)
	[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 681, in _cleanup_procs
	[pipenv.exceptions.InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
	[pipenv.exceptions.InstallError]: ['Looking in indexes: https://pypi.python.org/simple', 'Collecting pywin32==225 (from -r /tmp/pipenv-fjwofmya-re                quirements/pipenv-tyg8rxk8-requirement.txt (line 1))']
	[pipenv.exceptions.InstallError]: ['ERROR: Could not find a version that satisfies the requirement pywin32==225 (from -r /tmp/pipenv-fjwofmya-requ                irements/pipenv-tyg8rxk8-requirement.txt (line 1)) (from versions: none)', 'ERROR: No matching distribution found for pywin32==225 (from -r /tmp/p                ipenv-fjwofmya-requirements/pipenv-tyg8rxk8-requirement.txt (line 1))']
	ERROR: ERROR: Package installation failed...
	  ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/1 — 00:00:

**Comment by gilesknap** [comment]
I'm wondering if this is because you already have a venv activated when running pipenv.
`⠼ Creating virtual environment...Already using interpreter /usr/local/bin/python3.7`

I assume you are OK installing from pypi? This should have the same dependencies, but I have made a few changes to master since the last release.

Please can you post the output of:
`pipenv graph`

Thanks

**Comment by michalhainc** [comment]
The output of pipenv graph

	root@nas:~/gphotos-sync# python3.7 -m pipenv graph
	gphotos-sync==2.10.1
	  - appdirs [required: Any, installed: 1.4.3]
	  - exif [required: Any, installed: 0.8.1]
		- enum34 [required: Any, installed: 1.1.6]
	  - PyYaml [required: Any, installed: 5.1.2]
	  - requests-oauthlib [required: Any, installed: 1.2.0]
		- oauthlib [required: >=3.0.0, installed: 3.1.0]
		- requests [required: >=2.0.0, installed: 2.22.0]
		  - certifi [required: >=2017.4.17, installed: 2019.9.11]
		  - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
		  - idna [required: >=2.5,<2.9, installed: 2.8]
		  - urllib3 [required: >=1.21.1,<1.26,!=1.25.1,!=1.25.0, installed: 1.25.6]
	  - selenium [required: Any, installed: 3.141.0]
		- urllib3 [required: Any, installed: 1.25.6]
	root@nas:~/gphotos-sync#

**Comment by gilesknap** [comment]
Your pipenv is trying to look for pywin32==225 but my pipfile does not specify a version.

I'm not sure where that is coming from. I will have to fire up a Windows VM and see if I can see the issue.

**Comment by michalhainc** [comment]
But I don't run this on windows... I'm running it on SOC ODroid Xu-4 which is arm based, OS is Armbian (debian clone for Arm cpus)

**Comment by gilesknap** [comment]
hmmm, I guess you could try removing the pywin32 from the Pipenv file. 

I have not yet discovered how to get Pipenv to do platform-specific dependencies. But if the above works for you, I'll look into how to do this.

**Comment by gilesknap** [comment]
(I meant Pipfile)

**Comment by gilesknap** [comment]
This is fixed in master now.
