### ISSUE TITLE
Some mp4 videos failed to download

### ISSUE THREAD

**Issue by michalhainc** [gilesknap/gphotos-sync#131]
Excerpt from log file: 

	09-25 16:20:43 gphotos.GooglePhotosDownload ERROR    FAILURE 7 downloading photos/2019/09/VID_20190920_170124.mp4
	09-25 16:20:43 gphotos.BadIds DEBUG    BAD ID AGcGo_pNOxI539YX65BO-oeo9bNt2PmTRcn26ithKcAQJCf2xlOcPYkrqkW5z4IHo9TaEMdUZVxwQnG9JKmuKmYOpzdyEjHz0g for photos/2019/09/VID_20190920_170124.mp4
	Traceback (most recent call last):
	  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
		result = self.fn(*self.args, **self.kwargs)
	  File "/usr/local/lib/python3.7/site-packages/gphotos/GooglePhotosDownload.py", line 225, in do_download_file
		response.raise_for_status()
	  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
		raise HTTPError(http_error_msg, response=self)
	requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://video-downloads.googleusercontent.com/ABzBgw3zoA_v8O3nvw9wQp74pStwRR24r026cYjDSzS50ReiAgSCYBJfMxxSjNCrnSDOK30C3zqmcXsvbGPadRFcK0XxrZwoN9J6ujW_OOCSqXPNt1c7lTuQZOiCLzuWzaqjqtg6-Bp4sztH4MYtMpUvnoF_dQG7iZ9zEMLCKTNHUDnfyBEgiE5PlL09hFrQUpIz5g221P8hmLXVqtGZIhB25w-ZY1M03Ox3HR9eA6q1OcRpICZlEnr3Irq2odyo-J0Atxywue9j05evzk0oHjdNIDR5KPxHnUL2_XnBWblCko14aId8rlyRDtI965wnNMu9dgx9m9FU-gNjx_f1xUyp3XG6APG25Vir6vpTGCDeIw9W2dQb4e33ywjPuycDidd6UApIKda3CsBvtavtZW7tqlyIg6JMxuN2UFL55NVlTFDoS_5HQQrAyRQNyBVVkXmmz0zPoPapIvEqsyWZiaqUveWREcPHwYEvqw0aHlQGCYE7S4buofSH-oRs6_hpwO-esYZVtGti-dejraO2VuvfKb9QI1C5a0wTaFgm4dbVJTVZTSjSq23SXZSZTwAPDL8fUwe56rHkg1zGEOW7e0WNOLdy2gV-vZuP65neEQz_1zIiQzOcFzjjEVl0p-_dp0tKjCag3A45r1DGmw3i9QoIs_q6izqNmFWcV6KpsHQnoKGCK_XrCgMWD194YSZxGTfV04YdTTR-7-8zxOskXiRLqZHmTmWca0kGwl4ge1X-k1sKAUOKHkWjttA7J4Vvm57Q79LU8QuXZcr8ZnF2fVgzowr-P28-Dm2b9sLanR27ugWyqJ3Rwq4qZNm8H4k8Vslracbb8TIOnEw8-UuKnJvUUD2BFdAr_UXbrJ3jr8YzvGR2v0979wiWl6rDVVMuaspgjYmgWwOS

**Comment by gilesknap** [comment]
I think you are seeing the 2nd know issue in https://github.com/gilesknap/gphotos-sync/blob/master/README.rst.

I guess from the description that some of your MP4s are OK?

**Comment by michalhainc** [comment]
Aha yes it might be the known issue nr. 2

Majority of videos downloaded fine, closing the issue, thank you and sorry for not reading the manual
