### ISSUE TITLE
Skip .HEIC photos

### ISSUE THREAD

**Issue by Tom1n0** [gilesknap/gphotos-sync#132]
Hello gilesknap, 

Will it be possible to add an option to skip a custom file format, or to skip .HEIC format directly? It is apple's live photo format introduced in iOS 11. It is possible to open it in Windows, if you buy a codec, but there is no need for live photos on windows. That is why I would like to skip those, so I do not have duplicates in the Photos app. Another example for a filtering feature could be to skip (edited) photos, which means that they have been edited on the phone.

Really appreciate your program! 👍

**Comment by gilesknap** [comment]
Filtering out by file extension would not be difficult to do. However, it is not in the spirit of gphotos-sync which is supposed to create a backup. If anyone wants to make a PR I will happily accept.

I do not think it is possible to filter by 'edited on the phone'. There is no metadata in the API for modified date. It is one of the listed know issues that we don't download changes to existing photos as a result of this.

**Comment by gilesknap** [comment]
closing this. Please re-open if you wish to discuss further.
