### ISSUE TITLE
Sync Albums/Photos between two Google Accounts

### ISSUE THREAD

**Issue by MatthiasLohr** [gilesknap/gphotos-sync#134]
Hello,

is it possible to sync albums and photos from one Google Account to another? If not, would it be possible to consider this as a feature request?

Best regards
Matthias

**Comment by gilesknap** [comment]
Hi Matthias,

I'm pretty attached to the idea of gphotos-sync being download only. There are two motivations:-
- Currently, the Google Photos API is too crippled in its upload features. e.g. paid for storage only, only specifying album at upload time and only allowed one album per item, no delete, etc...
- being download only means never having a bug that can trash someone's library

So I'm afraid the answer is that won't be happening in the near future.
