### ISSUE TITLE
Does not work on NFS mouned filesystem

### ISSUE THREAD

**Issue by redlegoman** [gilesknap/gphotos-sync#135]
If I choose a dir on an NFS mounted filesystem gphotos-sync just seems to hang. It creates a gphotos.lock file and a gphotos.log file in the NFS dir but they stay at zero size and nothing happens. I have to kill the python process with a SIGKILL.
If I specifiy --db-path to somewhere local, things start working and the gphotos.log file which is still on the NFS filesystem gets bigger, as does the sqlite db which is on local disk. The photos then start downloading into the photos sub directory once the database is populated.

I'm running on Ubuntu 19.04 with python 3.7. The NFS filesystem is mounted from a Centos 7 host.

**Comment by gilesknap** [comment]
I think the answer is to not use NFS for the DB unfortunately. See this article:
https://stackoverflow.com/questions/9907429/locking-sqlite-file-on-nfs-filesystem-possible
Luckily gphotos-sync lets you store the DB locally and this would always give better performance anyway.

**Comment by gilesknap** [comment]
Closing this, please re-open if you would like to discuss further,
