### ISSUE TITLE
Corrupt Database - how to resolve

### ISSUE THREAD

**Issue by smseidl** [gilesknap/gphotos-sync#140]
gphotos-sync is failing with the following error: "sqlite3.DatabaseError: database disk image is malformed".  How do I correct this without duplicating files.

10-12 13:34:26 gphotos.Main INFO     version: 2.10.1, database schema version 5.6
10-12 13:34:27 gphotos.BadIds DEBUG    bad_ids file, loaded 3 bad ids
10-12 13:34:27 gphotos.GooglePhotosIndex WARNING  Indexing Google Photos Files ...
10-12 13:34:27 gphotos.GooglePhotosIndex INFO     searching for media start=2019-10-06 19:50:34, end=None, videos=True
10-12 13:34:27 gphotos.GooglePhotosIndex DEBUG    mediaItems.search with body:
{'pageToken': None, 'pageSize': 100, 'filters': {'dateFilter': {'ranges': [{'startDate': {'year': 2019, 'month': 10, 'day': 6}, 'endDate': {'year': 3000, 'month': 1, 'day': 1}}]}, 'mediaTypeFilter': {'mediaTypes': ['ALL_MEDIA']}, 'featureFilter': {'includedFeatures': ['NONE']}}}
10-12 13:34:28 gphotos.LocalData INFO     Saving Database ...
10-12 13:34:28 gphotos.LocalData INFO     Database Saved.
10-12 13:34:28 gphotos.Main ERROR    
Process failed.
Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\gphotos\Main.py", line 373, in main
    self.start(args)
  File "c:\program files\python36\lib\site-packages\gphotos\Main.py", line 345, in start
    self.do_sync(args)
  File "c:\program files\python36\lib\site-packages\gphotos\Main.py", line 320, in do_sync
    new_files = self.google_photos_idx.index_photos_media()
  File "c:\program files\python36\lib\site-packages\gphotos\GooglePhotosIndex.py", line 158, in index_photos_media
    media_item.id)
  File "c:\program files\python36\lib\site-packages\gphotos\LocalData.py", line 260, in file_duplicate_no
    (path, name.lower()))
sqlite3.DatabaseError: database disk image is malformed
10-12 13:34:28 gphotos.Main WARNING  Done.
10-12 13:34:28 gphotos.Main INFO     Elapsed time = 0:00:01.879255

**Comment by gilesknap** [comment]
Hi,

It sounds like you have somehow corrupted the database.

if you simply delete the gphotos.sqlite file then the next run will
re-index all of your library (which takes a while) but will not cause any
duplicates to be downloaded.

**Comment by gilesknap** [comment]
Did this work for you?

**Comment by smseidl** [comment]
I believe so.  I did get a sync to occur and will monitor future runs.

**Comment by gilesknap** [comment]
Closing, let me know if you have further problems.
