### ISSUE TITLE
Date Modified and Date Created

### ISSUE THREAD

**Issue by wills721** [gilesknap/gphotos-sync#143]
The 'Date Modified' date of the files are set properly and reflect the date of the photo.  Would it be possible for the 'Date Created' to also be set when a new file is downloaded by gphoto's? The 'Date Created' would equal the 'Date Modified'.  This would help indexing in cloud services such as Amazon photos.  Note:  I am not asking for the meta data inside the file to be changed -- just the 'Date Created' of the file itself.

**Comment by gilesknap** [comment]
I think I addressed this in 723e1140a81a8400210d82233b68b0314d3d11b8
It is a Windows-only fix though. I assume you are using Windows?

It is not in an official release yet - you would need work from master to pick it up. Perhaps it is time for a new release ...

**Comment by wills721** [comment]
Well -- maybe.  I run GPhotos-sync on Ubuntu Linux.  Will it work for me?

**Comment by gilesknap** [comment]
It won't work on Linux. It uses a specific windows library.

As far as I understand Linux kernel does not support create date, am I
wrong?

**Comment by wills721** [comment]
It does exist.  Its called 'Birth date'.  However, I'm not sure (now that you bring it up) how to update it.  Its part of the inode.

  File: DSC00170.JPG
  Size: 4380912         Blocks: 8560       IO Block: 131072 regular file
Device: 32h/50d Inode: 338316      Links: 1
Access: (0777/-rwxrwxrwx)  Uid: ( 1024/ UNKNOWN)   Gid: (  100/   users)
Access: 2036-02-07 06:28:16.000000000 -0500
Modify: 2010-01-01 03:21:11.000000000 -0500
Change: 2019-10-12 05:12:17.748730864 -0400
 Birth: -

(Birth is empty above)

**Comment by wills721** [comment]
This may all be a lost cause.  I'm trying to get Amazon to date sort correctly and its just may be a lost cause.  I'll close it out

**Comment by gilesknap** [comment]
Yes, I think many Linux filesystems have create-date but the kernel has no
way to set it.
It does seem a strange limitation.

**Comment by gilesknap** [comment]
I don't think you meant to reopen this? Closing.
