### ISSUE TITLE
Still no modified date in the API... Here's my suggestion

### ISSUE THREAD

**Issue by ghost** [gilesknap/gphotos-sync#153]
Hi,

Google has still not provided any API to provide get the last modification date and time.

Here's my proposal:
* user/app creates a new Album names "gphotos-sync"
* user adds any updated photos to this album before syncing
* when gphotos-sync finds a photo in the "gphotos-sync" album
  * it re-downloads the file
  * then it removes the photo from the gphotos-sync album

What do you think ?

Regards,

Michael

**Comment by gilesknap** [comment]
This is a good attempt at a workaround to an annoying issue but I'm afraid it is still scuppered by the API:-
from https://developers.google.com/photos/library/guides/manage-albums
```
Note that you can only remove media items that your application has added to an album or that have
been created in an album as part of an upload. For albums that are shared, you can only remove 
items added by other collaborators if you are acting on behalf of the owner of the album.
```
My other issues with the approach are:
- it is quite brittle in that it requires user intervention and there is no way to check if you have remembered to do action every item you have edited after the fact.
- it involves modification to the library which gphotos-sync does not currently do

**Comment by michael79bxl** [comment]
Crap :hankey: !
This API is soooo limited :roll_eyes:

**Comment by gilesknap** [comment]
Feel free to re-open if you would like to discuss further.

**Comment by michael79bxl** [comment]
I noticed Google Photos is providing`etag` and `if-none-match` http headers.

The etag changed when I modified the picture ! 😎 

I still need to check if it changes after a certain amount of time.

It might be a way to detect changes. 😲 

The idea would be to not download the whole picture, but the header only (i think it's possible).
Event better, I noticed Google Photos accepts (at the moment) the header `Range` which allows to limit the bytes downloaded.

**Comment by gilesknap** [comment]
This sounds promising (I was not aware of etag before).

It would still be much slower than at present to use this though. If I understand correctly there would need to be an Http request per media item to make use of this. Currently, indexing only takes one Http request per 100 items, and also filters out everything that predates the last scan.

We could mitigate this by making it massively parallel. I would be concerned about what this will do to quota though.

Reopening this ticket as 'still worth a look'

**Comment by michael79bxl** [comment]
I confirm the `etag` keeps its value after baseURL expiration and/or more than 24 hours.
Its value changes when the picture is modified.

**Comment by michael79bxl** [comment]
Also, a crop can be detected by the `width` and `height` properties of MediaMetadata.

**Comment by gilesknap** [comment]
Encouraging. Are you implying that a crop does not change the etag?

**Comment by michael79bxl** [comment]
The `etag` does change when you do crop the image.
I meant: the size of the image is one of the indicator that an image has changed.

**Comment by gilesknap** [comment]
Michael, I wonder if you would be interested in applying your JavaScript skills to the GPS problem? It might be possible to use an approach like this https://github.com/mrishab/google-photos-delete-tool to scrape the library for GPS info of all photos. Then put it in gphotos-sync db and update all the local files' EXIF.

If we can crack the GPS issue and the syncing of modified images then we just need Google to fix the Video transcoding issue. At that point, we have a pretty decent backup system.

**Comment by michael79bxl** [comment]
Looks really hard. Google is using a series of batchexecute remote scripts that return invalid json.
Those are extremely protected (no way to re-fetch). It seems impossible to get the real download URL.
Google is schizophrenic: Google Picker returns the GPS coords but the Google Photos API strips them!

Sample Picker result (notice the "picasa" `serviceId`)
```
{
   "id":"6761432079566617458",
   "serviceId":"picasa",
   "mimeType":"application/vnd.google-apps.photo",
   "name":"20191119_171329_HDR.jpg",
   "description":"",
   "type":"photo",
   "lastEditedUtc":1574180009000,
   "iconUrl":"https://ssl.gstatic.com/docs/doclist/images/icon_10_generic_list.png",
   "url":"https://picasaweb.google.com/117390654716346557837/CPAS#6761432079566617458",
   "thumbnails":[
      {
         "url":"https://lh3.googleusercontent.com/-H9IqgMYbUcA/XdVupxt_u3I/AAAAAAABGdo/fOVXW1jqwqcMbynFjfvUNWic59uj0Ic5QCMECGAYYCw/s32-c/20191119_171329_HDR.jpg",
         "width":32,
         "height":32
      },
      {
         "url":"https://lh3.googleusercontent.com/-H9IqgMYbUcA/XdVupxt_u3I/AAAAAAABGdo/fOVXW1jqwqcMbynFjfvUNWic59uj0Ic5QCMECGAYYCw/s64-c/20191119_171329_HDR.jpg",
         "width":64,
         "height":64
      },
      {
         "url":"https://lh3.googleusercontent.com/-H9IqgMYbUcA/XdVupxt_u3I/AAAAAAABGdo/fOVXW1jqwqcMbynFjfvUNWic59uj0Ic5QCMECGAYYCw/s72-c/20191119_171329_HDR.jpg",
         "width":72,
         "height":72
      },
      {
         "url":"https://lh3.googleusercontent.com/-H9IqgMYbUcA/XdVupxt_u3I/AAAAAAABGdo/fOVXW1jqwqcMbynFjfvUNWic59uj0Ic5QCMECGAYYCw/s400/20191119_171329_HDR.jpg",
         "width":400,
         "height":300
      },
      {
         "url":"https://lh3.googleusercontent.com/-H9IqgMYbUcA/XdVupxt_u3I/AAAAAAABGdo/fOVXW1jqwqcMbynFjfvUNWic59uj0Ic5QCMECGAYYCw/20191119_171329_HDR.jpg",
         "width":512,
         "height":384
      }
   ],
   "sizeBytes":307888,
   "rotation":0,
   "rotationDegree":null,
   "parentId":"6113604356475795105",
   "latitude":50.83546619444445,
   "longitude":4.347759833333333,
   "version":72154,
   "mediaKey":"AF1QipM5xBw_ASNquQXOXOoMhLIcl__kKFi0CRB2RIps",
   "docIndex":25,
   "lastEdited":1574180009000
}
```

**Comment by michael79bxl** [comment]
OMG, that was stupid ! Here is the solution:

* Use the productUrl (requires user to login)
* Download HTML and find the picture URL
* Replace =... with =d and download the TRUE image

Range HTTP Header even works!

I will implement this in gphotos-sync-ui 😉

**Comment by gilesknap** [comment]
I like the sound of that!
This would solve both the GPS issue and the Video Transcode issue.
Let's open an issue in the gphotos-sync-ui repo to discuss.

**Comment by gilesknap** [comment]
Michael is making progress on this. See https://github.com/michael79bxl/gphotos-sync-ui/issues/2#issue-526237070

**Comment by karan** [comment]
Uh oh. Looks like the user and repo are gone.

**Comment by gilesknap** [comment]
Yes I'm afraid some time ago.

If anybody wants to pursue this then I did fork it here https://github.com/gilesknap/gphotos-sync-ui
