### ISSUE TITLE
Favorites and Categories folders

### ISSUE THREAD

**Issue by ghost** [gilesknap/gphotos-sync#154]
Hi,

Could gphotos-sync create a "favorites" and "categories" folders according to the following APIs?

https://developers.google.com/photos/library/reference/rest/v1/mediaItems/search#FeatureFilter
https://developers.google.com/photos/library/reference/rest/v1/mediaItems/search#ContentFilter

ContentFilter (categories) would have a subfolder by Category (e.g. ANIMALS).
Of course, these folders would only contain symlinks.

Thanks,

Regards,

Michael

**Comment by gilesknap** [comment]
This sounds like a good idea and not too difficult to implement.

I will take a look at doing this.

**Comment by e-id** [comment]
I just discovered the tool has a setting to get favorites only :)
I will add this to my gphotos-sync-ui project

**Comment by michael79bxl** [comment]
I just discovered the tool has a setting to get favorites only :smile: 
I will add this to my gphotos-sync-ui project

**Comment by gilesknap** [comment]
Note that --favourites won't meet your requirement above since it downloads
favourites only but to the same folder hierarchy.

**Comment by michael79bxl** [comment]
No problem, I will put favorites to another root folder :wink:

**Comment by michael79bxl** [comment]
The flag does not seem to work 😞

**Comment by gilesknap** [comment]
What are the symptoms?

**Comment by michael79bxl** [comment]
The flag is ignored. All photos and albums are downloaded.

**Comment by gilesknap** [comment]
Sorry about that. I'll look into it.

**Comment by gilesknap** [comment]
OK, it looks like there is bug. Although file indexing only gets favourites, the album indexing goes ahead and indexes everything that is in an album (I have a CI test for the feature but skipped albums for expedience).

I'll see what I can do about this. The API has no filters for album listing, but I guess I could do the filtering internally.

In the meantime, if you do --favourites-only --skip-albums you should get your favourites (just not the albums they are in).

**Comment by michael79bxl** [comment]
Thanks. Works great!

**Comment by gilesknap** [comment]
shouldn't have closed this - I still have the new folders to implement!

**Comment by gilesknap** [comment]
closing as won't implement. there is no recent demand for the further folders.
