### ISSUE TITLE
archive

### ISSUE THREAD

**Issue by gosugimoto** [gilesknap/gphotos-sync#155]
Hi,

I just noticed that photos in "archive" folder are not listed.  Is there a way to get those?  What I tend to do in gphotos is for example the likes of documents and drawings, I would take a photo, then put them into a folder.  Then I'd archive the photos so that they don't show up in my main catalog of photos - I can just goto the albums.

Or is it somewhere and I'm missing this?

**Comment by gilesknap** [comment]
Hi,

I've not looked into this before. I assume that items that have been
archived don't get listed by the Google API by default. I will look to see
if this can be overridden.

Cheers,
giles.

**Comment by gosugimoto** [comment]
Great, thank you.  Whilst filtering thru, realized many images missing...it
was the archives.

**Comment by gilesknap** [comment]
So it appears that archived items do not appear by default https://developers.google.com/photos/library/guides/apply-filters#archived-state
. I will add the ability to backup archived data too.

**Comment by gosugimoto** [comment]
Great, thanks!

**Comment by gilesknap** [comment]
@gosugimoto I have implemented a --archive argument. It is currently in the branch 'feature' if you want to try it out now you will need git. Alternatively, you can wait for the next release which I'll do in a week or so.

**Comment by gosugimoto** [comment]
Amazing, thank you!  I'll wait for the next release!

**Comment by gosugimoto** [comment]
Hi,

Has the next release come out with archive downloading features?  And what
is the best way to upgrade gphotos?  Can I just download and physically
replace the files in the mac finder?

Thanks!
--
iamgo.net

**Comment by gilesknap** [comment]
Sorry, No. I am >evaluating< Stadia so am having a pause on development. :-)

I promise a release by 1st week of Jan.

**Comment by gosugimoto** [comment]
No rush at all,just wanted to check in. Thanks! How's stadia?

**Comment by gilesknap** [comment]
Stadia is pretty good. For me, it was an inexpensive way to get all of
Destiny 2. It is getting a hard time in the press but I think it may do OK
in the long run.

**Comment by gilesknap** [comment]
@gosugimoto sorry for the delay. You should now see this feature in the latest release.

change to your installation dir and execute
- pipenv install gphotos-sync==2.10.4

to update

**Comment by gosugimoto** [comment]
Hi,

Thanks!!! and happy new year!
FYI, in the virtualenv, i did pip update --gphotos-sync and that seemed to
work I think.  However I don't see the archive function in the help, is
this automatic as default now?

--
iamgo.net

**Comment by gilesknap** [comment]
There should be a new argument --archived
if you do a --help you should see it listed at the end of the arguments, this will also print the version number at the end which should be 2.8.6

**Comment by gosugimoto** [comment]
Yes I think that worked! thank you!!
--
iamgo.net

**Comment by gilesknap** [comment]
I just retired the test for this because I thought it was not working but now realise that it was behaving as expected since it just adds archived items as opposed to only downloading them as per my assumption. TODO: restore the test and make the count work correctly.
