### ISSUE TITLE
Windows Shortcut files instead of symbolic links

### ISSUE THREAD

**Issue by ghost** [gilesknap/gphotos-sync#160]
Hi,

Is it possible to provide a flag to support LNK file creation instead of symbolic links?
e.g. --use-lnk

http://www.mamachine.org/mslink/index.en.html

Regards,

Michael

**Comment by gilesknap** [comment]
I guess this is sensible since Windows support for symlinks is not so great. I had not thought of using lnks.

I'll put it on the list.

**Comment by michael79bxl** [comment]
Thanks.
symlinks are better (e.g. can't use shortcuts for scrolling desktop backgrounds).
But anyway, works great just to "show" an album.

**Comment by gilesknap** [comment]
We could put the lnk files is a separate subfolder so you could have both if you want.

**Comment by michael79bxl** [comment]
Yes, why not. Both using command line option. Thank.

**Comment by kebbob** [comment]
I've recently updated to the latest version (on windows, pipenv) and my previously Hardlinked Albums are now just normal files. Is it to do with this update?

**Comment by gilesknap** [comment]
Hi,

No, it should not be as far as I am aware. 

gphotos-sync only ever makes links in the album folders. However, I've not looked into hardlinks on windows. If the creation of the album folders is taking a long time then I guess that would indicate that gphotos-sync's attempt to make a link is resulting in a file copy.

Can you report on the time spent during the creating album links phase? You could so so by deleting your albums folder and running with --log-level debug. 

Thanks.

**Comment by kebbob** [comment]
Well, I've done a couple flush/syncs since I posted and my albums are hardlinks again. Odd. But seems to be fine now?!

**Comment by gilesknap** [comment]
@kebbob thanks for letting me know. If it happens again, we'll try to diagnose.

**Comment by gilesknap** [comment]
maybe someone native to windows could look at this?

**Comment by oweitman** [comment]
here is the code. but its only possible if the script is started with elevated privileges (as administrator)
https://stackoverflow.com/questions/26787872/how-to-create-symlinks-in-windows-using-python

**Comment by gilesknap** [comment]
@oweitman I think that is for creating symlinks which we already do. This Issue is about creating Shortcut files (which do not require special privileges). 

I'm asking for volunteers to look at this issue :-)

**Comment by gilesknap** [comment]
I'm releasing a new version of gphotos-sync and closing stale issues. Please reopen if you still want me to look at this. Thanks.
