### ISSUE TITLE
issue with docker image

### ISSUE THREAD

**Issue by midevil** [gilesknap/gphotos-sync#161]
i'm getting a " photos-sync: error: the following arguments are required: root_folder" error when starting the container

**Comment by gilesknap** [comment]
Hi, There are some instructions towards the end of the Readme. Take a look and see if that helps. If not please post details of how you are launching. Thanks.

**Comment by midevil** [comment]
I'm running it in the docker interface in synology NAS. I Guess the problem is not being able to add a startup folder via the syno gui. If i run the container in command mode, it does work. Is it possible to modify the docker so that it uses an environment variable?

**Comment by midevil** [comment]
Ok, the command in the readme file creates the container on the syno just fine when using shell access to the synology. There you can also get the url for the token and enter the token. After that, the docker container is created in the GUI and with a cronjob you can start the sync. Use the command: `docker restart <containername>`

**Comment by martyp187** [comment]
I'm getting the same error. But it's not Synology related.

The readme docker command always complains with:

`usage: gphotos-sync [-h] [--album ALBUM] [--logfile LOGFILE]

                    [--compare-folder COMPARE_FOLDER] [--favourites-only]

                    [--flush-index] [--rescan] [--retry-download]

                    [--skip-video] [--skip-shared-albums]

                    [--album-date-by-first-photo] [--start-date START_DATE]

                    [--end-date END_DATE] [--log-level LOG_LEVEL]

                    [--db-path DB_PATH] [--albums-path ALBUMS_PATH]

                    [--photos-path PHOTOS_PATH] [--use-flat-path]

                    [--new-token] [--index-only] [--skip-index] [--do-delete]

                    [--skip-files] [--skip-albums] [--get-locations]

                    [--use-hardlinks] [--no-album-index]

                    [--case-insensitive-fs] [--max-retries MAX_RETRIES]

                    [--max-threads MAX_THREADS] [--secret SECRET]

                    root_folder

gphotos-sync: error: the following arguments are required: root_folder
`

Thats on straight-up docker on ubuntu. The container is created but will not start.

**Comment by martyp187** [comment]
So although it just got me to another error, I found its the white spacing of the docker command in the readme that is the issue. If you you make it a single line command with correct spacing it works.

**Comment by gilesknap** [comment]
Thanks for letting me know. I'll see if I can fix the README. @midevil would you like to contribute a 'how to set up in Synology' description?
