### ISSUE TITLE
Add photos to albums

### ISSUE THREAD

**Issue by dehnert** [gilesknap/gphotos-sync#162]
It would be helpful if gphotos-sync supported adding photos to albums -- it'd be great if, say, making appropriate symlinks in an album folder and then running GPhotos could add the photos in question to the (either new or existing) album. It looks like there's an [appropriate API](https://developers.google.com/photos/library/reference/rest/v1/albums/batchAddMediaItems). (I'm currently downloading photos from GPhotos and picking out favorites to share with Shotwell, and this would make sharing those photos on GPhotos much easier.)

**Comment by gilesknap** [comment]
Hi, thanks for your interest.

At present, I'm keeping gphotos-sync as read-only and not looking at modifying the library. The main reason for this is that the API is currently really limited and it would be impossible to provide a symmetric solution.

What you are asking for is now possible (since a recent improvement to the API) but only if the album you are adding to was created by gphotos-sync in the first place. This quirky limitation would confuse the hell out of a user of this feature.

**Comment by gilesknap** [comment]
Closing this issue but please continue to respond if you wish to discuss further.
One day - if the API get sufficiently fixed, I will implement two-way sync and this would be part of that.

**Comment by dehnert** [comment]
Huh, I'd been thinking that the requirement that the *album* was created by gphotos-sync, which seems okayish -- the option could always create a new album, which would be a little annoying and a little weird, but easy to understand. I didn't realize until I'd tried implementation (https://github.com/dehnert/gphotos-sync/tree/upload-album) that apparently the *photos* need to be from the app too. I commented on the issue about that (https://issuetracker.google.com/issues/132274769) -- no idea if it'll help...

(Thanks for this tool, though! It's a pity Google severely limited their API...)

**Comment by gilesknap** [comment]
Currently, Google has some very specific ideas about what the API is for and that is not synchronizing with a 3rd party and it is not replacing their web GUI. So we may be out of luck. Both of these would reduce clients' reliance on Google.

But keeping the pressure on is good so thanks for commenting on their issue.

**Comment by mgutt** [comment]
Really like to have uploads. I'm using Google Photos only as free solution to view my (local) original files from everywhere. I don't have a problem by creating the target folder through the Google Photos app first.

**Comment by gilesknap** [comment]
@mgutt the Google API does not support upload to the free storage. It only supports full-size photos upload to paid storage. This is one of the reasons I have never bothered with two-way sync.

**Comment by mgutt** [comment]
@gilesknap 
Oh... crap.
