### ISSUE TITLE
Log only errors to stderr

### ISSUE THREAD

**Issue by staffanf** [gilesknap/gphotos-sync#165]
Hi, great project!

Hi, wondered if you could make this program only log to stderr if there is an error?
Currently this [line](https://github.com/gilesknap/gphotos-sync/blob/3fcb4b73299134ef9c593797516065eee5990e85/gphotos/Main.py#L312) sets all logging to stderr. To me this is a very strange standard. Using stderr for ERROR (maybe WARNING) and up is fine.

Backstory:
I'm running this as a cronjob in docker on a OMV NAS. Cron sends a mail for every command that prints output, so I get a main every night, even when everything works.
So instead I run my jobs with a script (cronic) which only prints info if here is output on stderr of an error code.
Since this program always prints all info on stderr, I get email every night.

**Comment by staffanf** [comment]
Another alternative would be to clean up the logging on WARNING level to actually be warnings.. Right now a lot of info is printed on WARNING level.

**Comment by gilesknap** [comment]
Hi, yep I think you have a good point re stderr logging, I'm not sure why I did it that way and am happy to log only errors to std error.

re warnings vs infos. I kind of use warning for high priority infos. I accept that this is not good practice and should probably use a custom logging level.

I'll put these on the todo list.

**Comment by gilesknap** [comment]
this should be fixed in https://github.com/gilesknap/gphotos-sync/tree/api-logging. I now use stderr for ERROR and CRITICAL, and stdout for all others. I'm still using WARNING as a high priority INFO. But I have learned about adding custom levels since I also added API tracing on a custom level.

Will roll this into the next release. Closing.
