### ISSUE TITLE
HTTPError: 403 Client Error: Forbidden for url: https://photoslibrary...

### ISSUE THREAD

**Issue by martyp187** [gilesknap/gphotos-sync#166]
Spinning up from the docker image

Once entering to the oauth repsonse token..

WARNING  Indexing Google Photos Files...
ERROR
Process failed.

requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://photoslibrary.googleapis.com/v1/mediaItems?pageSize=100

WARNING  Done.

the container then stops.

**Comment by gilesknap** [comment]
This sounds like you did not give the required permissions to your OAuth Token. You may have missed a step in the creation of the token. There is a good description of the steps at https://www.linuxuprising.com/2019/06/how-to-backup-google-photos-to-your.html

**Comment by martyp187** [comment]
This is true. The permissions I set were for an app not associated with my client json.
Starting again and getting a new link etc worked.
