### ISSUE TITLE
odd behavior

### ISSUE THREAD

**Issue by gosugimoto** [gilesknap/gphotos-sync#168]
Hi.

So I don't know how to describe this, but I'll try.  I'm getting so really weird behavior with the script.  I have an album that is shared with me, but I don't download the photos nor do I have it selected to show up in my albums.  Sometimes these photos (at random) are downloaded by the script.  Most times, I haven't even seen the photos as I hadn't opened/clicked on the shared album in the app or website yet.  And it isn't every photo, just some of them...

I keep thinking how these photos get downloaded as they aren't on my phone, nor can I see them in my main list of photographs...

Any thoughts?

**Comment by gilesknap** [comment]
Hi,

gphotos-sync is supposed to sync shared albums so I would expect you to see
these pictures.

You can suppress this with --skip-shared-albums.

**Comment by gosugimoto** [comment]
Right, I'll give that a try, thank you!
Is there a document showing all these options and codes?

--
iamgo.net

**Comment by gilesknap** [comment]
To discover all of the options use gphotos-sync --help

**Comment by gilesknap** [comment]
I think it is OK to close this
