### ISSUE TITLE
TIMEOUT for build issues

### ISSUE THREAD

**Issue by jaal2001** [gilesknap/gphotos-sync#169]
Hi,
as I was having issues during the installation on my RaspBerryPi B, maybe adding this to the documentation could help other people:

Use
  export PIPENV_TIMEOUT=240
beore running the pipenv commands. It seems that pipenv needs much more time on old and slow systems. It took some time to find that parameter...

Regards
JJ

**Comment by gilesknap** [comment]
Thanks for the tip.

Do you think it is also your connection speed? I have installed on my
raspberry pi zero with no issues but not sure if that is faster than the B?

**Comment by jaal2001** [comment]
I've tried numerous of hours to track down the problem. After setting the timeout to 240 (actually im using 480) solved the problem. 
I don't know if and how B and Zero do differ. My connection speed is Ethernet 100Mbit (while my cable ISP connection does exceed that). So I assume this is an issue of the slow/old CPU.

**Comment by gilesknap** [comment]
@jaal2001 thanks for this. I have added a troubleshooting section to the readme with this info.
