### ISSUE TITLE
KeyError: 'mimeType' error as i try to download the photos for the first time

### ISSUE THREAD

**Issue by XshzX** [gilesknap/gphotos-sync#171]
After i configured gphotos-sync on my MacBook and i tried to download the fotos from my google account. 

`Mac@MacBook-Pro-Mac ~/temp/gphotos-sync/Google_fotos (master) $ pipenv run gphotos-sync .
12-23 01:31:09 WARNING  Case insensitive file system found 

Please go here and authorize, <URL>

Paste the response token here: <TOKEN>

12-23 01:32:38 WARNING  Indexing Google Photos Files ... 

12-23 01:33:00 ERROR    

Process failed. 

Traceback (most recent call last):

  File "/Users/Mac/.local/share/virtualenvs/gphotos-sync-xgkNzhvg/lib/python3.7/site-packages/gphotos/Main.py", line 398, in main
    self.start(args)

  File "/Users/Mac/.local/share/virtualenvs/gphotos-sync-xgkNzhvg/lib/python3.7/site-packages/gphotos/Main.py", line 351, in start
    self.do_sync(args)

  File "/Users/Mac/.local/share/virtualenvs/gphotos-sync-xgkNzhvg/lib/python3.7/site-packages/gphotos/Main.py", line 329, in do_sync
    new_files = self.google_photos_idx.index_photos_media()

  File "/Users/Mac/.local/share/virtualenvs/gphotos-sync-xgkNzhvg/lib/python3.7/site-packages/gphotos/GooglePhotosIndex.py", line 156, in index_photos_media
    media_item = GooglePhotosMedia(media_item_json, to_lower=self.case_insensitive_fs)

  File "/Users/Mac/.local/share/virtualenvs/gphotos-sync-xgkNzhvg/lib/python3.7/site-packages/gphotos/GooglePhotosMedia.py", line 23, in __init__
    if self.is_video():

  File "/Users/Mac/.local/share/virtualenvs/gphotos-sync-xgkNzhvg/lib/python3.7/site-packages/gphotos/BaseMedia.py", line 53, in is_video
    return self.mime_type.startswith('video')

  File "/Users/Mac/.local/share/virtualenvs/gphotos-sync-xgkNzhvg/lib/python3.7/site-packages/gphotos/GooglePhotosMedia.py", line 81, in mime_type
    return self.__media_json['mimeType']

KeyError: 'mimeType'

12-23 01:33:00 WARNING  Done. `

Can somebody provide a solution for this ? Thanks

**Comment by gilesknap** [comment]
Thanks for the report. I'll take a look at this next week.

**Comment by alexortner** [comment]
I got the same error here today on a complete fresh python gphoto-sync install

**Comment by gilesknap** [comment]
@alexortner are you on a Mac?

**Comment by XshzX** [comment]
> @alexortner are you on a Mac?

i also tried it on an ubuntu 18.04 machine, same behaviour

**Comment by gilesknap** [comment]
@alexortner @XshzX or anyone seeing this issue.

Please, can you try checking out the debug branch https://github.com/gilesknap/gphotos-sync/tree/debug and send me the log file from your root dir when you get this issue.

This branch has extra debugging to show what json content is coming back from the Google API.

The issue looks pretty serious since it implies missing fields from the responses that Google is sending.

Thanks.

**Comment by XshzX** [comment]
> @alexortner @XshzX or anyone seeing this issue.
> 
> Please, can you try checking out the debug branch https://github.com/gilesknap/gphotos-sync/tree/debug and send me the log file from your root dir when you get this issue.
> 
> This branch has extra debugging to show what json content is coming back from the Google API.
> 
> The issue looks pretty serious since it implies missing fields from the responses that Google is sending.
> 
> Thanks.

Using the debug branch helped to find out the files that had no mimeType metadata. The 2 files caused the error, I used the productURL from the logs to access the file in the browser and deleted them there. Afterwards running gphotos-sync again, the files were indexed and downloaded correctly.
Thank you,

**Comment by gilesknap** [comment]
Thanks for debugging. I need to make gs not crash in this circumstance. Can you let me know what the file was that had no mime type please? Even better post the JSON for the offending file. Thanks!

**Comment by XshzX** [comment]
As the logs are overwriten everytime, i don't have and exact log entry for you but I will try to reproduce it for you: It looks like this:
`Legit log entry with mimeType:
12-30 20:39:55 gphotos.GooglePhotosIndex DEBUG    item json:
{'id': '<randomID1>', 'productUrl': 'https://photos.google.com/lr/photo/<randomID1>', 'baseUrl': 'https://lh3.googleusercontent.com/lr/<randomString>, 'mimeType': 'image/jpeg', 'mediaMetadata': {'creationTime': '2019-10-17T08:56:26Z', 'width': '960', 'height': '1280', 'photo': {}}, 'filename': '14fd29bf-9e75-4b12-b097-e6400e4e0cad.jpg'}`
Log entry without mimeType that caused the error was something like:
`12-30 20:39:55 gphotos.GooglePhotosIndex DEBUG    item json:
{'id': '<randomID1>', 'productUrl': 'https://photos.google.com/lr/photo/<randomID1>', 'baseUrl': 'https://lh3.googleusercontent.com/lr/<randomString>, 'mimeType': '', 'mediaMetadata': {'creationTime': '2019-10-17T08:56:26Z', 'width': '960', 'height': '1280', 'photo': {}}, 'filename': '14fd29bf-9e75-4b12-b097-e6400e4e0cad.jpg'}`
The mimeType entry was empty causing the error. 
I hope it helps. 
Best regards,

**Comment by gilesknap** [comment]
That helps.

It seems it is a JPG but no mimetype is provided. I can default to assuming
it is an image or ignore items with missing mimeType. Probably the latter.

Thanks.

**Comment by XshzX** [comment]
Ah, there's something else. I managed to take a screenshot of one the files that caused the problem. This files had no preview, it looked like this: 
![google_foto](https://user-images.githubusercontent.com/11617309/71622556-2c59b780-2bdf-11ea-8f01-90fc161f959a.png)
Before breaking down the indexing process the damaged image was indexed anyway. I therefore ran gphotos-sync again with the --skip-index option, so the indexed files including the one that broke the indexing process was downloaded and I could open and view it. 
I think the 2 photos were damaged and/or something in the metadata information was missing or corrupt, as there was no preview accessing them using the productURL in the browser but they could be seen and opened in browser in Google Photos.
I don't think many people are affected but it is pretty tricky to fix it. 
Thanks for the tool. it helped a lot

**Comment by gilesknap** [comment]
I have certainly managed to get corrupted files in my library before, but
this is the first time I have seen missing mimeType.

Thanks for the info.

**Comment by gilesknap** [comment]
@alexortner I have pushed a fix to the branch '2020' please give it a go. 

Thanks
