### ISSUE TITLE
Photos in album left unindexed

### ISSUE THREAD

**Issue by jonathancrawford** [gilesknap/gphotos-sync#172]
When I first ran the sync, it found about 4800 out of 5000 images.  I tried flush-index and rescan and now it only finds 3800 images.

The album I'm syncing is "Rachel Frame" and it is selected using the --album option.  I don't want to sync all the photos because this program is pulling a specific set of pictures for display on a self-made digital picture frame and the frame is configured to only pull pictures for that frame.  Any ideas on how I can debug this?  Thanks!

Snippets from the LOG here:

12-22 21:27:51 gphotos.Utils DEBUG    MINIMUM_DATE = 1970-01-01 00:00:00
12-22 21:27:51 gphotos.Checks DEBUG    MAX_PATH_LENGTH: 4096
12-22 21:27:51 gphotos.Checks DEBUG    MAX_FILENAME_LENGTH: 255
12-22 21:27:51 gphotos.Checks DEBUG    Checking if is filesystem supports symbolic links...
12-22 21:27:51 gphotos.Checks DEBUG    Checking if File system is case insensitive...
12-22 21:27:51 gphotos.Main INFO     version: 2.10.3, database schema version 5.6
12-22 21:27:52 gphotos.LocalData INFO     Saving Database ...
12-22 21:27:52 gphotos.LocalData INFO     Database Saved.
12-22 21:27:52 gphotos.LocalData INFO     Saving Database ...
12-22 21:27:52 gphotos.LocalData INFO     Database Saved.
12-22 21:27:52 gphotos.BadIds DEBUG    bad_ids file, loaded 0 bad ids
12-22 21:27:52 gphotos.GoogleAlbumsSync WARNING  Indexing Shared (titled) Albums ...
12-22 21:27:53 gphotos.GoogleAlbumsSync DEBUG    Skipping Album: Karen’s Frame, photos: 1978 (does not match --album)
**12-22 21:27:53 gphotos.GoogleAlbumsSync INFO     Indexing Album: Rachel Frame, photos: 5056**
.
.
.
12-22 21:27:52 WARNING  Indexing Shared (titled) Albums ... 
12-22 21:28:43 WARNING  Indexed 10 Shared (titled) Albums 
12-22 21:28:43 WARNING  Indexing Albums ... 
12-22 21:29:33 WARNING  Indexed 2 Albums 
12-22 21:29:33 WARNING  Downloading Photos ... 
12-22 21:29:38 WARNING  Downloaded 0 Items, Failed 0, Already Downloaded 3881 
12-22 21:29:38 WARNING  Creating album folder links to media ... 
12-22 21:29:46 WARNING  Created 3881 new album folder links 
12-22 21:29:46 WARNING  Done.

**Comment by jonathancrawford** [comment]
@gilesknap 

I think I tracked down the error.  During one of the batches during the album index, the items_json contains no media items but it does contain a nextPageToken. 

As written, the code cannot handle this scenario.  The code sees an empty media_json object at line 81 of GoogleAlbumSync.py and breaks even though the items_json has another page of items.

I suggest the following change:

`          if not media_json:
               #Allows for the case where the nextPageToken exists but the media_json doesn't. 
               if not items_json.get('nextPageToken'):
                    break
            else:
                for media_item_json in media_json:
                    position += 1
                    media_item = GooglePhotosMedia(media_item_json)
                    log.debug('----%s', media_item.filename)
                    self._db.put_album_file(album_id, media_item.id, position)
                    last_date = max(media_item.create_date, last_date)
                    first_date = min(media_item.create_date, first_date)

                    # this adds other users photos from shared albums
                    # Todo - This will cause two copies of a file to appear for
                    #  those shared items you have imported into your own library.
                    #  They will have different RemoteIds, one will point to your
                    #  library copy (you own) and one to the shared item in the
                    #  the folder. Currently with the meta data available it would
                    #  be impossible to eliminate these without eliminating other
                    #  cases where date and filename (TITLE) match
                    if add_media_items:
                        media_item.set_path_by_date(self._photos_folder,
                                                    self._use_flat_path)
                        (num, row) = self._db.file_duplicate_no(
                            str(media_item.filename),
                            str(media_item.relative_folder),
                            media_item.id)
                        # we just learned if there were any duplicates in the db
                        media_item.duplicate_number = num

                        log.debug('Adding album media item %s %s %s',
                                media_item.relative_path, media_item.filename,
                                media_item.duplicate_number)
                        self._db.put_row(
                            GooglePhotosRow.from_media(media_item), False)

            next_page = items_json.get('nextPageToken')
            if next_page:
                body = self.make_search_parameters(album_id=album_id,
                                                   page_token=next_page)
                response = self._api.mediaItems.search.execute(body)
            else:
                break`

**Comment by gilesknap** [comment]
This is fixed in #173
