### ISSUE TITLE
While using --skip-video .mov and .mp4 are still downloaded

### ISSUE THREAD

**Issue by jaal2001** [gilesknap/gphotos-sync#174]
Hi,
as my Image frame should only display photos and no videos, I would like to skip downloading the videos.

This is my download command:

pipenv run gphotos-sync --skip-video --log-level DEBUG --logfile /var/log/gphotos-sync.log --do-delete --flush-index --rescan ~/Pictures/google

The scan starts:
12-24 11:33:28 gphotos.Utils DEBUG    MINIMUM_DATE = 1970-01-01 00:00:00
12-24 11:33:28 gphotos.Checks DEBUG    MAX_PATH_LENGTH: 4096
12-24 11:33:28 gphotos.Checks DEBUG    MAX_FILENAME_LENGTH: 255
12-24 11:33:28 gphotos.Checks DEBUG    Checking if is filesystem supports symbolic links...
12-24 11:33:28 gphotos.Checks DEBUG    Checking if File system is case insensitive...
12-24 11:33:28 gphotos.Main INFO     version: 2.10.4, database schema version 5.7
12-24 11:33:29 gphotos.LocalData INFO     Saving Database ...
12-24 11:33:29 gphotos.LocalData INFO     Database Saved.
12-24 11:33:29 gphotos.LocalData INFO     Saving Database ...
12-24 11:33:29 gphotos.LocalData INFO     Database Saved.
12-24 11:33:30 gphotos.GooglePhotosIndex WARNING  Indexing Google Photos Files ...
12-24 11:33:30 gphotos.GooglePhotosIndex INFO     searching for media start=None, end=None, videos=False
12-24 11:33:30 gphotos.GooglePhotosIndex DEBUG    mediaItems.search with body:
{'pageToken': None, 'pageSize': 100, 'filters': {'dateFilter': {'ranges': [{'startDate': {'year': 1900, 'month': 1, 'day': 1}, 'endDate': {'year': 3000, 'month': 1, 'day': 1}}]}, 'mediaTypeFilter': {'mediaTypes': ['PHOTO']}, 'featureFilter': {'includedFeatures': ['NONE']}, 'includeArchivedMedia': False}}
12-24 11:33:34 gphotos.GooglePhotosIndex DEBUG    search_media parsed 0 media_items with 100 PAGE_SIZE

[...]

12-24 11:55:36 INFO     Indexing Album: [XXX], photos: 2350
12-24 11:55:38 DEBUG    ----IMG_3617.MOV
12-24 11:55:38 DEBUG    Adding album media item photos/2019/12/IMG_3617.MOV IMG_3617.MOV 0
12-24 11:55:38 DEBUG    ----IMG_3616.MOV
12-24 11:55:38 DEBUG    Adding album media item photos/2019/12/IMG_3616.MOV IMG_3616.MOV 0
12-24 11:55:39 DEBUG    ----IMG_3418.MOV
12-24 11:55:39 DEBUG    Adding album media item photos/2019/12/IMG_3418.MOV IMG_3418.MOV 0
12-24 11:55:39 DEBUG    ----IMG_3417.MOV
12-24 11:55:39 DEBUG    Adding album media item photos/2019/12/IMG_3417.MOV IMG_3417.MOV 0
12-24 11:55:39 DEBUG    ----IMG_3416.MOV
12-24 11:55:39 DEBUG    Adding album media item photos/2019/12/IMG_3416.MOV IMG_3416.MOV 0
12-24 11:55:39 DEBUG    ----IMG_3415.HEIC
12-24 11:55:39 DEBUG    Adding album media item photos/2019/12/IMG_3415.HEIC IMG_3415.HEIC 0
12-24 11:55:39 DEBUG    ----IMG_3410.MOV
12-24 11:55:39 DEBUG    Adding album media item photos/2019/12/IMG_3410.MOV IMG_3410.MOV 0
12-24 11:55:39 DEBUG    ----IMG_3409.HEIC
12-24 11:55:39 DEBUG    Adding album media item photos/2019/12/IMG_3409.HEIC IMG_3409.HEIC 0
12-24 11:55:39 DEBUG    ----IMG_3408.HEIC

[...]

12-24 12:05:24 INFO     downloading 26 photos/2019/11/IMG_3146.MOV
12-24 12:05:24 INFO     downloading 27 photos/2019/11/IMG_3144.MOV

ffprobe is installed.

Is there any hint how to chase why the sync is reaching for the videos?

Thx
JJ

**Comment by jonathancrawford** [comment]
By default the index search looks for Media of All types.  When the "skip-video" option is used, the search is switch to media that is labelled as a "PHOTO" in Google.  

When you look at the google library,  do the .MOV files show up as "Videos" or "Movies"?

**Comment by jaal2001** [comment]
The i.e. 3144.mov video has been sorted by the google algorithm into the video folder.

But taking this as a hint:
I‘m adding all photos and videos with a specific person to a shared album. This album is shared to a 2nd account. This 2nd account then does import this shared album to his local drive via gphotos-sync. 
So could be the main „error“ cause, that I‘m downloading a specific shared album and not the whole library?

**Comment by gilesknap** [comment]
You theory as to the cause could be correct. I'm going to do some big fixes
next week and will look at this.

**Comment by jaal2001** [comment]
Let me know if I can provide any additional tests and/or logs.

**Comment by gilesknap** [comment]
This bug is next on the list. Expect an update sometime this week.

**Comment by gilesknap** [comment]
@jaal2001 there was indeed an issue with skipping videos in shared albums. I have fixed this in the branch '2020' please give it a try.

**Comment by jaal2001** [comment]
I was not able to install the new branch properly (never done this with a branch, so maybe there will still be an issue with my enviroment), so I copied the 3 changed files manually into the pipenv folder.

I've deleted the .MOV files manually in the folder, then re-run the sync. However the .mov file has again been downloaded:

pipenv run gphotos-sync --skip-video --log-level DEBUG --logfile /var/log/gphotos-sync.log --do-delete --flush-index --rescan /home/pi/Pictures/google

[...]
01-02 18:57:48 gphotos.GooglePhotosDownload DEBUG    SKIPPED download (file exists) 63 photos/2019/12/IMG_3660.HEIC
01-02 18:57:48 gphotos.GooglePhotosDownload DEBUG    SKIPPED download (file exists) 64 photos/2019/12/IMG_3659.HEIC
01-02 18:57:48 gphotos.GooglePhotosDownload DEBUG    SKIPPED download (file exists) 65 photos/2019/12/GX013732.MP4
01-02 18:57:48 gphotos.GooglePhotosDownload DEBUG    SKIPPED download (file exists) 66 photos/2019/12/IMG_3648.HEIC
01-02 18:57:49 gphotos.GooglePhotosDownload INFO     downloading 10 photos/2019/12/IMG_3670.MOV
01-02 18:57:49 gphotos.GooglePhotosDownload INFO     downloading 11 photos/2019/12/IMG_3662.MOV
01-02 18:57:50 gphotos.GooglePhotosDownload INFO     downloading 12 photos/2019/12/IMG_3655.MOV
01-02 18:57:50 gphotos.GooglePhotosDownload INFO     downloading 13 photos/2019/12/IMG_3651.MOV
01-02 18:57:50 gphotos.GooglePhotosDownload INFO     downloading 14 photos/2019/12/IMG_3650.MOV
01-02 18:57:53 gphotos.GooglePhotosDownload DEBUG    SKIPPED download (file exists) 67 photos/2019/12/IMG_3647.HEIC
01-02 18:57:53 gphotos.GooglePhotosDownload DEBUG    SKIPPED download (file exists) 68 photos/2019/12/IMG_3646.HEIC
01-02 18:57:54 gphotos.GooglePhotosDownload DEBUG    SKIPPED download (file exists) 69 photos/2019/12/IMG_3645.HEIC
[...]

**Comment by gilesknap** [comment]
I believe you are running the (previous) installed version of gphotos-sync and not the source files you copied over.

To install from the 2020 branch please:

- cd to you install directory
- pipenv install git+https://github.com/gilesknap/gphotos-sync.git@2020#egg=gphotos-sync

**Comment by jaal2001** [comment]
After numerous attempts with pipenv (I'm not used to this ...), I got it working. 
Now gphotos is skipping the videos and also deleting all videos (full command: pipenv run gphotos-sync --skip-video --log-level DEBUG --logfile /var/log/gphotos-sync.log --do-delete --flush-index --rescan /home/pi/Pictures/google)

Looks good, thanks!

**Comment by gilesknap** [comment]
Thanks for letting me know.

Pipenv is somewhat idiosyncratic!
