### ISSUE TITLE
Support older python 3.5.x for Synology

### ISSUE THREAD

**Issue by dmitryuv** [gilesknap/gphotos-sync#175]
First of all, thank you for all the hard work. I'm running this tool on my x86-based Synology NAS to continuously backup all the photos. However, the latest Python3 available for Synology is 3.5.6, so currently I'm stuck with gphotos-sync 2.8.4. Is it possible to pull Py version back to 3.5+ (i mean, are there really new features needed from latest Py?). Being on bleeding edge is always cool, but at the same time it limits usage scenarios for those who can't update.
Thanks.

**Comment by gilesknap** [comment]
I'll take a look to see if I'm using 3.6 features.

**Comment by gilesknap** [comment]
OK, I'm afraid this is not going to be possible. I use the new Python 3.6 type hint syntax throughout the code and none of my modules will even load in Python 3.5.

I'm a big fan of the feature but did not realize it was only introduced in 3.6.

Closing as can't fix.

**Comment by dmitryuv** [comment]
Thanks, I hope 2.8.4 will keep working for a long time, or Synology will update their Py package. Backing up directly on NAS sounds like a valuable use-case to me, and I think many other NAS owners.

**Comment by gilesknap** [comment]
Hi, I have had other users get this working on Synology. Some use docker and some have found a python 3.6 for synology. See this thread for some insight https://github.com/gilesknap/gphotos-sync/issues/141

**Comment by Tennyleaz** [comment]
Many Synology models can't run Docker, nor SynoCommunity python 3.6 package. 
So we are stuck at python 3.5 for good.

**Comment by gilesknap** [comment]
That is unfortunate. It looks like there is some activity to fix this though? https://github.com/SynoCommunity/spksrc/pull/3833
