### ISSUE TITLE
Add ~"my photos" directory

### ISSUE THREAD

**Issue by dehnert** [gilesknap/gphotos-sync#176]
AFAICT, when using GPhotos to sync, it'll also include photos uploaded by other people that are in your shared albums. It looks like [mediaItems.list](https://developers.google.com/photos/library/guides/list) returns the things actually in your library (which is close to, although admittedly apparently not quite the same as, just the things you uploaded). It'd be great to make a pseudo-album of things in the library, or a third directory alongside photos and albums containing symlinks to photos in the library.

There's also the [contributorInfo](https://developers.google.com/photos/library/reference/rest/v1/mediaItems#ContributorInfo) field, which as seems typical for the GPhotos API, is irritatingly only available for albums created by the app, so not very useful for the purpose.

**Comment by gilesknap** [comment]
We already have the option --skip-shared-albums. If you use this then you won't see any shared content.

What you cannot do with the current options is include your shared albums but only include the photos that you put in them. 

Does --skip-shared-albums meet your requirement?

**Comment by gilesknap** [comment]
closing this. please re-open if you still have concerns.
