### ISSUE TITLE
RFE: filter on EXIF attributes

### ISSUE THREAD

**Issue by raintonr** [gilesknap/gphotos-sync#177]
I'd like to be able to filter downloads based on EXIF attributes. Eg. exclude: 'cameraMake': 'Nikon'

This is because my Google Photos library has images taken on my Android phone (various models throughout the year) which end up there automatically and images from my DSLR and compact cameras which I add manually as part of my photo workflow.

I want to download all the photos that were taken on my Android phone as these are currently only stored in Google Photos and would like a local backup.

However, as I already have local backups of the original files from the DSLR & compact it's pretty pointless downloading the JPG versions that are in Google Photos and would like to exclude them from the download. Given I've never had a phone made by Nikon or Canon the easiest way to excluded these from download would be by using cameraMake EXIF tag, but other users may also want to filter based on model or other attributes and think that would be a useful generic feature.

**Comment by gilesknap** [comment]
I can't get the EXIF out of a file without downloading it first. However, Google does provide some of the EXIF fields in its own metadata and cameraMake, cameraModel are included.

The only other fields at present are focalLength, apetureFNumber and isoEquivalent. (not sure that anyone would want to filter on these?).

I will add this to the feature todo list.

**Comment by gilesknap** [comment]
I'm releasing a new version of gphotos-sync and closing stale issues. Please reopen if you still want me to look at this. Thanks.
