### ISSUE TITLE
Windows network drive issue

### ISSUE THREAD

**Issue by Tennyleaz** [gilesknap/gphotos-sync#183]
I created a network drive like:

    NET USE S: \\192.168.1.1\Share\Photos

Then I run this script like:

```
D:\PythonApps\gphotos-sync>pipenv run gphotos-sync --secret secret.json S:\\Alice
01-09 20:32:02 WARNING  cant determine max filepath length, defaulting to 248
01-09 20:32:02 WARNING  cant determine max filename length, defaulting to 248
01-09 20:32:02 ERROR    Symbolic links not supported
01-09 20:32:02 ERROR    Albums are not going to be synced - requires symlinks
01-09 20:32:02 WARNING  Case insensitive file system found
01-09 20:32:03 WARNING  Indexing Google Photos Files ...
01-09 20:32:04 WARNING  Done.
```

Somehow the first run seems successful, all images are downloaded. However I always get this error message now.
How could I correctly using on a network drive under Windows?

**Comment by gilesknap** [comment]
Hi, it looks like you did everything correct.

The output you posted implies that the sync ran OK but did not find any photos in your library. If you do want to sync albums you will need to see  Enabling SymLinks on Windows in the README.

If you want help understanding why no photos were synced, please can you send me the contents of your log file in the root of s:\\Alice? (to gilesknap@gmail.com if you prefer not to share on github)

**Comment by gilesknap** [comment]
Note that if all the photos in your library are in shared albums then the behaviour described is expected and you will need symlinks enabled to sync those albums.

**Comment by Tennyleaz** [comment]
Thanks for the quick reply.
I test uploading one photo and sync again, I see lines like:
```
01-09 21:03:02 WARNING  Downloading Photos ...
01-09 21:03:04 WARNING  Downloaded 1 Items, Failed 0, Already Downloaded 6907
```
I confirmed photos are downloaded. Since using symlink on windows need to run as administrator, missing album link is ok to me.

**Comment by gilesknap** [comment]
Thanks for letting me know. I have a feature request to support windows LNK files instead of symlinks so in the future you will be able to sync albums without admin rights.
