### ISSUE TITLE
Syncing stops when firewall on

### ISSUE THREAD

**Issue by emetselaar** [gilesknap/gphotos-sync#188]
I am running gphotos sync on a synology NAS (with docker). Works great when I leave my firewall off, but when it is switched on I get timeouts. So I am trying to figure out which ports are used. I block most ports and incoming traffic from "foreign" ips. I guess the used API is only "get" and thus that last part will not make a difference. If someone knows we can perhaps add it to the docs

**Comment by gilesknap** [comment]
Hi,

The API is REST over HTTPS so should only be using PORT 443. I would not expect your firewall to be blocking that. Maybe you can look in the firewall logs and see what it is having an issue with?

**Comment by emetselaar** [comment]
Thanks for the quick answer. I will take a look. The firewall is for the NAS itself, and it is quite restrictive, so perhaps 443 is not even open. Will test later today and let you know.

**Comment by gilesknap** [comment]
Did you manage to resolve this? If so please go ahead and close. Thanks.

**Comment by emetselaar** [comment]
Not yet, I see this when starting up and it keeps repeating that message:
![Screenshot 2020-01-27 at 11 03 51](https://user-images.githubusercontent.com/18800/73165934-1fa08480-40f5-11ea-8505-15ad9ea400a1.jpg)

I tried to add port 443 to the "allowed list, but that did not work"

Switch firewall off and it seems to work ok.
Not sure what settings I should use. It is not a problem with the software but only with my configuration. 

I wil try to experiment but for now close the ticket as it is a problem on my side.
![image](https://user-images.githubusercontent.com/18800/73166282-da308700-40f5-11ea-902d-e79e82c38dad.png)
