### ISSUE TITLE
Not support unicode file name

### ISSUE THREAD

**Issue by nntu** [gilesknap/gphotos-sync#189]
`--- Logging error ---
Traceback (most recent call last):
  File "d:\anaconda3\lib\logging\__init__.py", line 1028, in emit
    stream.write(msg + self.terminator)
  File "d:\anaconda3\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u1ec5' in position 83: character maps to <undefined>
Call stack:
  File "d:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "d:\Anaconda3\Scripts\gphotos-sync.exe\__main__.py", line 9, in <module>
    sys.exit(main())
  File "d:\anaconda3\lib\site-packages\gphotos\Main.py", line 412, in main
    GooglePhotosSyncMain().main()
  File "d:\anaconda3\lib\site-packages\gphotos\Main.py", line 398, in main
    self.start(args)
  File "d:\anaconda3\lib\site-packages\gphotos\Main.py", line 351, in start
    self.do_sync(args)
  File "d:\anaconda3\lib\site-packages\gphotos\Main.py", line 329, in do_sync
    new_files = self.google_photos_idx.index_photos_media()
  File "d:\anaconda3\lib\site-packages\gphotos\GooglePhotosIndex.py", line 169, in index_photos_media
    media_item.relative_path)
Message: 'Indexed %d %s'
Arguments: (27378, WindowsPath("photos/2016/12/3. lễ ký kết thi đua '65 ngày đêm, xung kích, sáng tạo, quyết thắng' .jpg"))`

**Comment by gilesknap** [comment]
Thanks for the report.

Your photo name includes Unicode characters that for some reason cannot be mapped in the logging code. Debug logging to a file is always on so there is no way to avoid this at present.

I'll try passing your filename through a logger here and see if I can make it go wrong. If so I should be able to implement a fix.

I also might add a no-logfile option which would also have worked around this problem.

**Comment by gilesknap** [comment]
Hello,

I have created a test which logs your filename and it works for me so I don't understand the issue. The error says that your filename has a character "\u1ec5" at position 83 causing the problem.

The character is supposed to be ễ
My test seems to print it as expected ễ.
Your filename looks like it has this character in it but much earlier than position 83.
I wonder if there is more than one Vietnamese code page for Unicode?

Please can you try the following and send me the output:
```
cd /tmp
git clone https://github.com/gilesknap/gphotos-sync.git --single-branch --branch test-unicode
cd gphotos-sync/
pipenv install -dev .
pipenv run pytest test -k test_nntu_filename
```

**Comment by gilesknap** [comment]
@nntu I have just learned from @popey that there are issues with Unicode when using a snap. We are working on a fix.

Do you run gphotos-sync in a snap?

@popey the test above in this thread might be useful in verifying your fix. I will also test your fixes tomorrow evening (GMT)

**Comment by popey** [comment]
@gilesknap from the paths it looks like @nntu is using Windows.

**Comment by gilesknap** [comment]
Doh.

**Comment by gilesknap** [comment]
@nntu did you try running the test above yet? Thanks.

**Comment by gilesknap** [comment]
Closing as no response. Let me know if you have more to add or have some results from the test specified here https://github.com/gilesknap/gphotos-sync/issues/189#issuecomment-579878731
