### ISSUE TITLE
snapd filesystem and unicode characters

### ISSUE THREAD

**Issue by gilesknap** [gilesknap/gphotos-sync#192]
Hi @popey,

The 2nd issue I have under snap is that it cant write Unicode characters in folder names. gphotos-sync checks to see if the filesystem can accept Unicode and modifies folder and file names if necessary. For some reason under snap the Unicode test succeeds but the creation of a folder with a Unicode character fails.

See below
```
(master) [giles@gklinux gphotos-sync]$ snap run gphotos-sync /tmp/test-gphotos5 --secret /home/giles/github//gphotos-sync/test/test_credentials/client_secret.json --log-level error
Please go here and authorize, https://accounts.google.com/o/oauth2/v2/auth?response_type=code&client_id=434668126185-isurs73113r7iafhra2tlkpjsoormvie.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fphotoslibrary.readonly+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fphotoslibrary.sharing&state=dFJHKX6iMvdqfepCu3BqweSaKw5LFu&access_type=offline&prompt=select_account
Paste the response token here:4/wAEyp62D9m0CKRHNxfgAmjQdZ9v_KVsq47-Kk_w9KLI1fW5Ga83SnC4
--- Logging error ---
Traceback (most recent call last):
  File "/snap/gphotos-sync/92/usr/lib/python3.6/logging/__init__.py", line 996, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\U0001f600' in position 71: ordinal not in range(128)
Call stack:
  File "/snap/gphotos-sync/92/bin/gphotos-sync", line 11, in <module>
    load_entry_point('gphotos-sync==2.10.4', 'console_scripts', 'gphotos-sync')()
  File "/snap/gphotos-sync/92/lib/python3.6/site-packages/gphotos/Main.py", line 412, in main
    GooglePhotosSyncMain().main()
  File "/snap/gphotos-sync/92/lib/python3.6/site-packages/gphotos/Main.py", line 398, in main
    self.start(args)
  File "/snap/gphotos-sync/92/lib/python3.6/site-packages/gphotos/Main.py", line 351, in start
    self.do_sync(args)
  File "/snap/gphotos-sync/92/lib/python3.6/site-packages/gphotos/Main.py", line 335, in do_sync
    self.google_albums_sync.index_album_media()
  File "/snap/gphotos-sync/92/lib/python3.6/site-packages/gphotos/GoogleAlbumsSync.py", line 137, in index_album_media
    'albums', "Albums", True, self.album_index)
  File "/snap/gphotos-sync/92/lib/python3.6/site-packages/gphotos/GoogleAlbumsSync.py", line 178, in index_albums_type
    album.size)
Message: 'Indexing Album: %s, photos: %d'
Arguments: ('Clones\U0001f600', 4)
^C02-01 11:28:43 ERROR    User cancelled download 
(master) [giles@gklinux gphotos-sync]$ pipenv run ./gphotos-sync /media/Data/tmp/gphotos-test6 --secret /home/giles/github//gphotos-sync/test/test_credentials/client_secret.json --log-level error
Please go here and authorize, https://accounts.google.com/o/oauth2/v2/auth?response_type=code&client_id=434668126185-isurs73113r7iafhra2tlkpjsoormvie.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fphotoslibrary.readonly+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fphotoslibrary.sharing&state=fPzPh710rx3Z3AEJ2fYtqJL1Nc0VJG&access_type=offline&prompt=select_account
Paste the response token here:4/wAFOXw05Q8_XCwM9_92sqgqTfjLauvPeKUpLYHHbame1hqbwdKqUgHU
(master) [giles@gklinux gphotos-sync]$ ls /media/Data/tmp/gphotos-test6/albums/2017
'0528 Movies'  '0923 Clones😀'  '0926 Album 2016'  '1001 Shared Test Album'
(master) [giles@gklinux gphotos-sync]$ 
```

The code that does the Unocode check is as follows. Is there a way for me to debug it while running in the snap?
```
    def _unicode_filenames(self) -> bool:
        log.debug("Checking if File system supports unicode filenames...")
        testfile = self.root_path / ".unicode_test.\U0001f604"

        is_unicode = False
        try:
            testfile.touch()
        except BaseException:
            log.info("Filesystem does not support Unicode filenames")
        else:
            log.info("Filesystem supports Unicode filenames")
            is_unicode = True
            testfile.unlink()
        return is_unicode
```

**Comment by gilesknap** [comment]
If we can resolve these, I'm going to recommend that users install using snap since it is easier and less error-prone that pipenv.

**Comment by popey** [comment]
Ah, this is a known [bug](https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1576411) with some [suggestions](https://forum.snapcraft.io/t/enviroment-dependent-python-unicodeencodeerror/10108) on how to fix. I've added the suggested fix and rebuilt (a few times). 

Is there some test case I can use? 

Alternatively if you want to test, I have pushed potentially "fixed" versions to the various channels.

```
channels:
  stable:    2.10.4  2019-12-31  (92) 13MB - # existing "broken" version
  candidate: 2.10.4  2020-02-01 (158) 13MB - # fixed stable release
  beta:      2.10.4  2020-02-01 (158) 13MB -
  edge:      6433d36 2020-02-01 (162) 13MB - # fixed unstable release
```

If you want to test the fixed stable version you could `snap refresh gphotos-sync --candidate` and run that. To test the latest build from tip of git use `snap refresh gphotos-sync --edge`. 

You may need to manually connect the interfaces (as per the other issues)

`snap connect gphotos-sync:mount-observe`

`snap connect gphotos-sync:removable-media`

```
$ snap connections gphotos-sync
Interface        Plug                          Slot              Notes
home             gphotos-sync:home             :home             -
mount-observe    gphotos-sync:mount-observe    :mount-observe    manual
network          gphotos-sync:network          :network          -
removable-media  gphotos-sync:removable-media  :removable-media  manual
```

**Comment by gilesknap** [comment]
I tried candidate, beta, edge but got the same error.

If you would like to run a test yourself then clone master and do the following:
```
$ mkdir -p <TEST_FOLDER> 
$ cp <GPHOTOS_REPO>/test/test_credentials/.gphotos.token <TEST_FOLDER> 
$ snap run gphotos-sync <TEST_FOLDER> --secret <GPHOTOS_REPO>/test/test_credentials/client_secret.json
```

**Comment by gilesknap** [comment]
@popey did you get anywhere with this?

(side note: I've been struggling with auto version stamping and had loads of slightly broken deploy's to PyPi, however, this is now sorted and a release later this week would be fit for a snap)

**Comment by gilesknap** [comment]
@popey I just tried the latest 2.14.0 snap and it works great. The issues with mounts and removable storage are fixed.
It still exhibits the issue with Unicode characters.

If this is not easy to fix then I can provide an option to force the removal of Unicode characters from filenames.

**Comment by gilesknap** [comment]
@popey any news on this? Thanks.

**Comment by gilesknap** [comment]
@popey its been some time since we last looked at this issue. I wonder if you have discovered anything recently that might throw light on it? I'm getting a few bug reports from people that have unicode in their filenames, especially those that use a non english $LANG. 

You have a prominent page at https://ubuntu.com/blog/safely-backup-google-photos which is leading some people down a broken path. If we can't fix the issue, would it be possible to mention that an alternative install path is available for people in non english locales?

Thanks.

**Comment by gilesknap** [comment]
@popey maybe the last few comments in #259 will help?

**Comment by gilesknap** [comment]
@popey I'm taking snap out of the documentation for this project since we never got it working for anyone with unicode chars.

I notice that you have gone an written a snap to flatpak converter!! :-)

**Comment by gilesknap** [comment]
I'm releasing a new version of gphotos-sync and closing stale issues. Please reopen if you still want me to look at this. Thanks.
