### ISSUE TITLE
Runnning docker image on Raspberry Pi fails

### ISSUE THREAD

**Issue by igorkulman** [gilesknap/gphotos-sync#194]
Using libreelec on Raspberry Pi 2, running

```bash
docker run \
  --rm \
  -it \
  --name gphotos-sync \
  -v /media/mybook/Google\ Photos:/storage \
  -v /storage/client_id.json:/config/client_secret.json:ro \
  gilesknap/gphotos-sync \
  --log-level INFO \
  /storage
```

I get

```bash
standard_init_linux.go:211: exec user process caused "exec format error"
```

**Comment by gilesknap** [comment]
Hi, I'm afraid the docker image is for intel so won't run on the Pi.

I have successfully run gphotos-sync directly on a Pi 3 so you could try
that.
You may need to install python, pip and pipenv first.
If you need help with that I can run through in on my Pi this evening and
post the instructions.

**Comment by igorkulman** [comment]
I cannot and do not want to run it directly outside docker for multiple reasins. 

I am wondering is there maybe some Python 3.7 docker image that is "architecture neutral" you can base your image on? 

I think the Ruby image for example is configured in a way that it works both on x86 and ARM.

**Comment by gilesknap** [comment]
Apparently, such a thing may be possible but requires building multiple images and packaging in the same container https://www.docker.com/blog/multi-arch-all-the-things/

Alternatively, we could just make a separate docker image for Pi.

I am not experienced in docker and the image was provided by a contributor. I would guess that the following might work?

- Find an RPi image with python 3.6/3.7 on docker hub 
- modify the FROM field in https://github.com/gilesknap/gphotos-sync/blob/master/Dockerfile to point to the above
- docker build .   -f ./Dockerfile

**Comment by igorkulman** [comment]
Thanks. I got it working using `FROM :arm32v7/python:3.7-alpine`.

For anyone interested in running this on the RPi, just make the change and build teh container using `docker build -t gphotos-sync .`

The resulting image is just under 100 MB.

**Comment by gilesknap** [comment]
Thanks,

I might just add Arm to the continuous integration matrix and have it build a docker image too.
