### ISSUE TITLE
Older photos are never downloaded after crash

### ISSUE THREAD

**Issue by igorkulman** [gilesknap/gphotos-sync#195]
Here is what I did

1. Run the sync
2. It crashed after about 1000 photos downloaded with `ConnectionResetError(104, 'Connection reset by peer')`
3. Run the sync again

In step 3 I just get

```bash
02-03 15:05:53 INFO     version: 2.10.4, database schema version 5.7
02-03 15:05:53 WARNING  Indexing Google Photos Files ...
02-03 15:05:53 INFO     searching for media start=2020-02-01 21:52:04, end=None, videos=True
02-03 15:05:55 INFO     Saving Database ...
02-03 15:05:55 INFO     Database Saved.
02-03 15:05:55 WARNING  Done.
02-03 15:05:55 INFO     Elapsed time = 0:00:02.465079
```

Meaning older photos there were left to be download are not downloaded.

It looks like if I do not get all the photos downloaded at once then I will never be able to download all the old photos.

**Comment by igorkulman** [comment]
I would expect the tool to remember the last successfully downloaded photo and continue downloading on next run.

**Comment by igorkulman** [comment]
Maybe downloading photos from oldest to newest might be more reliable.

**Comment by gilesknap** [comment]
Thanks for the report. I did open a bug on this a while back but the solution was non trivial due to the way I have separated indexing and downloading and because downloading is a parallel operation.

The easy workaround is to use the --rescan option. Also, as soon as one new photo appears in the library it will trigger a download.

I'll take another look at this, I agree that continuing from the last download rather than last index is the correct behaviour.

**Comment by igorkulman** [comment]
What about something like a isDownloaded flag next to each file in the index that only gets set after a successful download. Then on the next run you know what is downloaded and what not even without rescan.

**Comment by gilesknap** [comment]
That flag already exists. However, the download code is completely skipped
if no new items are indexed.

Skipping is probably a mistake because it would be pretty cheap to do a SQL
query for downloaded=0.

That should be an easy fix.

**Comment by gilesknap** [comment]
Sorry for the delay. expect a fix this coming week.

**Comment by gilesknap** [comment]
This should be fixed in https://pypi.org/project/gphotos-sync/2.14.0/

**Comment by igorkulman** [comment]
Thanks!
