### ISSUE TITLE
Console windows pop up when running python in non-terminal mode.

### ISSUE THREAD

**Issue by christianbrugger** [gilesknap/gphotos-sync#196]
For continuous background updates, I want to periodically run gphotos-sync in the background. This currently does not work, as console windows still flash up at different times.

## How to reproduce it:

Preparations:
```
python -m venv env
env\Scripts\activate
pip install gphotos-sync
```
Run:
```
pythonw env\Scripts\gphotos-sync-script.py
```

Now you should see for a short time a console window flashing up in the foreground.

## Suspected issue

It seems that the issue is caused by using the subprocess module in the information gathering process. This causes terminal windows to flash up.

## Workaround

Apply the following monkey patch to the end of `env\Lib\site-packages\gphotos\__init__.py`:

```
import subprocess
Popen_orig = subprocess.Popen
def Popen_patch(*args, **kargs):
	startupinfo = subprocess.STARTUPINFO()
	startupinfo.dwFlags |= subprocess.STARTF_USESHOWWINDOW
	kargs["startupinfo"] = startupinfo
	return orig_Popen(*args, **kargs)
subprocess.Popen = Popen_patch
```

This will remove any flickering terminals.

## System Information

```
Windows 10, 1903
Pyhton 3.8.0, 64 bit
pip freeze
  appdirs==1.4.3
  attrs==19.3.0
  certifi==2019.11.28
  chardet==3.0.4
  enum34==1.1.6
  exif==0.8.1
  gphotos-sync==0+unknown.error
  idna==2.8
  oauthlib==3.1.0
  psutil==5.6.7
  pywin32==227
  PyYAML==5.3
  requests==2.22.0
  requests-oauthlib==1.3.0
  urllib3==1.25.8
```

**Comment by gilesknap** [comment]
Hi, thanks for the detailed report.

I run gphotos-sync in a cron job and do not see this issue. Which platform are you on?

However, I'm happy to apply the fix you suggest.

**Comment by gilesknap** [comment]
Sorry, I see that you already said you were on Windows 10 so that is why I don't see the issue (on Linux). Just running CI on the change right now ...

**Comment by gilesknap** [comment]
It broke one of my tests that also patches subprocess, but that should not affect you.

Please try out branch https://github.com/gilesknap/gphotos-sync/tree/versioning to verify that it fixes your issue.

**Comment by christianbrugger** [comment]
I really appreciate quick responses to my issue. I just tested it out. There is one Popen that is misses:
```
  File "test\env\lib\site-packages\gphotos\_version_git.py", line 53, in <module>
    __version__, git_error, git_sha1 = get_version_from_git()
  File "test\env\lib\site-packages\gphotos\_version_git.py", line 31, in get_version_from_git
    out = check_output(git_cmd.split(), stderr=STDOUT).decode().strip()
```
This one is called before the patch is applied. And as a result, there is still a terminal popping up.

**Comment by christianbrugger** [comment]
It would probably be better to use `from gphotos import __version__` instead of `from gphotos._version_git import __version__` in `Main.py`

Also you might be aware of this, but the version in `_version_static.py` is not correct. It says `__version__ = '0+unknown.error'` instead of `__version__ = ''2.12.3+1.4d9b334'`.

**Comment by christianbrugger** [comment]
I just looked at the regression test that failed. It turns out that Popen is not a function, but a class. So the monky patch should look more like this:

```
import subprocess
Popen_orig = subprocess.Popen
class Popen_patch(subprocess.Popen):
    def __init__(self, *args, **kargs):
        startupinfo = subprocess.STARTUPINFO()
        startupinfo.dwFlags |= subprocess.STARTF_USESHOWWINDOW
        kargs["startupinfo"] = startupinfo
        super().__init__(*args, **kargs)
subprocess.Popen = Popen_patch
```

**Comment by gilesknap** [comment]
Thanks for all the detailed help. I've just pushed the changes you suggest.

I've just been fighting with getting tests to run under VSCode in a Windows VM. So your input was much appreciated.

**Comment by gilesknap** [comment]
I think the change to __version__ import has fixed the issue with _version_static.py too (at least in a local test of executing setup.py). That was the bug I was currently chasing!

**Comment by gilesknap** [comment]
In fact, _version_static.py is still broken when deploying to Pypi. Something about how travis is building the distribution.

There is now a release 2.12.4 on pypi with your changes (but still with broken version number reporting).

**Comment by christianbrugger** [comment]
It all works now. Thanks for the new release.

**Comment by gilesknap** [comment]
Thanks for letting me know. And thanks for providing the solution to your issue.
