### ISSUE TITLE
Using --do-delete and --flush-index flag gives gphoto.sqlite file error

### ISSUE THREAD

**Issue by miketunes** [gilesknap/gphotos-sync#199]
Does this file need to be manually deleted before running the sync?  I'm running in Windows.  

File "C:\Users\mike\AppData\Local\Programs\Python\Python36\Lib\pathlib.py", line 393, in wrapped
    return strfunc(str(pathobjA), str(pathobjB), *args)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Google_Photos\\gphotos.sqlite' -> 'C:\\Google_Photos\\gphotos.sqlite.previous':

**Comment by gilesknap** [comment]
Hi, I think this is just doing --flush-index more than once on Windows. I back up to gphotos.sqlite.previous and it seems that the NTFS permissions don't allow overwrite on move.

Please can you try deleting 'C:\Google_Photos\gphotos.sqlite.previous' and try again?

Thanks.

**Comment by gilesknap** [comment]
I'll put in an explicit delete, I'll add it to the release that is going out tonight.

**Comment by gilesknap** [comment]
This should now be fixed in 2.14.0

**Comment by gilesknap** [comment]
if you do --help the version number is shown at the end of the text
