### ISSUE TITLE
os.chmod 666 doesn't seem stable on BSD based OS

### ISSUE THREAD

**Issue by XangoXCC** [gilesknap/gphotos-sync#201]
had a weird issue on my Freenas (BSD 11.3) Jail with this script. The script will execute and start downloading but then very quickly it hits a failure when attempting to change the file mask. (perhaps 20 files downloaded successfully)

  File "/root/.local/share/virtualenvs/gphotos-sync-IaHZ3P7Y/lib/python3.7/site-packages/gphotos/GooglePhotosDownload.py", line 274, in do_download_file
    **os.chmod(str(local_full_path), 0o666 & ~self.current_umask)**
**PermissionError: [Errno 1] Operation not permitted:** '/mnt/gphotos-sync/google_photos_sync/photos/2020/02/20200215_210110.jpg'

listing the dir shows that some files have been downloaded. Running the script again allows for a few more files to successfully download but it always fails quickly (1-5 seconds execute time)

 I have worked around the issue by just remarking out the OS.CHMOD line for now, but will attempt various other masks once I have a valid backup completed. 

----Update----
This appears to be related to the fact that if the filesystem uses any Windows ACL's then chmod is blocked from changing the filemask. It appears I would need to use getfacl/setfacl to clear any windows ACL's on the files/folders. As this folder is on a mixed network it seems to have inherited some file ACL's and thus the entire CHMOD line must be skipped. I could find no CHMOD values that would work.

**Comment by gilesknap** [comment]
Thanks for the detailed report.

The purpose of the chmod is to honour the user's filemask. The initial temporary file creation does not honour it so we change it after copying into place.

I imagine that this is not particularly relevant on a Windows filesystem so we could move it to an `else:` clause of the above ` if _use_win_32:`

Can you tell if gphotos-sync knows that your target filesystem is windows-like? if you run gphotos-sync with `--log-level info` you will see a message `Target filesystem XXX is YYY`. if YYY contains NTFS or FAT or 9P then your filesystem is considered windows-like. 

If it is windows like then the above fix will work for your case.

Let me know and I'll commit the fix.

**Comment by XangoXCC** [comment]
Target filesystem shows as ZFS, 

It would appear that if files are presented via SAMBA service they seem to inherit windows ACL's as soon as they are created. Furthermore, it appears that if any folders in the file path have windows ACL's on them they get propagated to all subfolders and files. I cannot create files or folders anywhere in my home directories without CHMOD failing. If i create files/or folders off the root of my volumes CHMOD works fine. 

I'm not a Linux/BSD expert nor familiar with Python but it seems that the SETFACL command is the updated command to use now. Not sure if that will help, disabling the CHMOD line seems to work perfectly, perhaps it isn't needed on ZFS based filesystems?

**Comment by XangoXCC** [comment]
I should note that the target filesystem I'm writing images to is a fstab mounted folder inside a BSD JAIL running on a Freenas server (11.3 release) and this inheritance behavior may be specific to Freenas only. I do not have any other BSD based systems to test on. My testing shows that chmod fails both from the host OS as well as inside the Jail.

**Comment by XangoXCC** [comment]
aaaaand one final note... the Authorize.py library also has an issue with this (line 71), my token wouldn't refresh properly and so I was limited to 1 hour of downloading ever. 

I've also found that running setfacl -b [filename] clears the ACL flags and allows CHMOD to function properly. I'll see if i can find a way to detect ACL entries on a file via Python but I'm more a powershell scripter than python coder :)

**Comment by gilesknap** [comment]
Thanks for the detailed analysis.

You are the first person to report this sort of a problem and I'm not clear about what is happening here. Do you know if ZFS natively support ACLs or is this something that is being imposed by the SAMBA service?

In my opinion, if your filesystem is using ACLs then the chmod in GooglePhotosDownload.py is likely to be unnecessary because ACLs usually inherit their parent permissions. Even if this is not the case then the chmod is only attempting to honour the group and all permissions defined by the user's filemask and I don't believe there is any relevance to that in a Windows ACL filesystem.

In the case of Authorize.py this is a bit of a concern since it is supposed to hide your authorization token from anyone except you.

If I want to manipulate ACLs in python I need to import a windows system library or a POSIX ACL implementation. 

Am I right in understanding that gphotos-sync is running on a BSD system? 
Please can you describe your setup in a little more detail?

**Comment by gilesknap** [comment]
@XangoXCC did you make any progress on this? Can you describe the filesystem setup you have?

Thanks.

**Comment by gilesknap** [comment]
Closing for now since I can'r reproduce and no responses.
