### ISSUE TITLE
Using NFS volume always produces WARNING  EXITING: database is locked 

### ISSUE THREAD

**Issue by kboom** [gilesknap/gphotos-sync#207]
Mount the NFS drive onto your machine.
Check that you can create and delete files there.
Once you run regular gphotos-sync command targeting that directory it will always fail with
`03-25 14:49:28 WARNING  EXITING: database is locked`

It actually creates the lock among other files there but even once I delete those it just recreates them and fails with the same error over and over. Works fine on regular directories though...

**Comment by gilesknap** [comment]
Hi, sorry I have not got around to adding this to known issues. See https://github.com/gilesknap/gphotos-sync/issues/167#issuecomment-566238360 for a workaround.

**Comment by gilesknap** [comment]
I have updated the readme here https://github.com/gilesknap/gphotos-sync/blob/master/README.rst#known-issues

**Comment by fahdi** [comment]
Looks like it was never resolved. I am having the same issue with a NAS Drive. Pretty low space on my Mac so I am stuck :(

@kboom Were you able to resolve it?
