### ISSUE TITLE
Unclear how to create OAuth client ID

### ISSUE THREAD

**Issue by p3k** [gilesknap/gphotos-sync#208]
In the README it says:

> Create a Client ID by following the setting up oauth 2.0 procedure with application type set to **Other**

However, in the gcloud console there is no such option; all I can select of are these:

![image](https://user-images.githubusercontent.com/16631/77580255-fb3a0c00-6edb-11ea-9311-d56352b05d9a.png)

**Comment by gilesknap** [comment]
It sounds like Google has changed the process a little. I'll have a go and
see if I can re-do the instructions.

**Comment by gilesknap** [comment]
Sorry, not looked at this yet but will do so sometime this week.

**Comment by gilesknap** [comment]
Sorry for the delay I have now written detailed instructions here https://docs.google.com/document/d/1ck1679H8ifmZ_4eVbDeD_-jezIcZ-j6MlaNaeQiz7y0/edit?usp=sharing please comment on the doc if they are not clear

**Comment by p3k** [comment]
great! i made it work following your instructions step by step and photos are downloaded now! thanks a lot.

**Comment by gilesknap** [comment]
That's great. Thanks for letting me know.
