### ISSUE TITLE
Support for Goitfy

### ISSUE THREAD

**Issue by tjsd** [gilesknap/gphotos-sync#209]
Hello!
Would love to have support for Gotify for this so I can track the job when it runs :)

**Comment by gilesknap** [comment]
Hi @tjsd I'll have to look into what is needed for this since I'm not familiar.
I've not got much time to spend on gphotos-sync right now but will look at this in the next few weeks.

**Comment by gilesknap** [comment]
sorry closing as won't do - I'm not spending much time on this project these days due to lack of response on the Google API issues.
