### ISSUE TITLE
FAILURE nnn downloading

### ISSUE THREAD

**Issue by blakeseufert** [gilesknap/gphotos-sync#213]
Hi there, after syncing my initial library ~170000 photos I notices it only had around 140000+ photos in directories. So when re-running the script i am getting a mixture of FAILURE and COMPLETED in the log. Just wonderirng if anyone can help?

I am using the docker image, on Unrarid:

I have read this might be related to a daily rate limit? If so what should i set it to in the Google Console? Thought i'd raise the bug regardless for lasting clarity. Thx again for an amazing script!

Some of the log:

`04-02 12:22:44 gphotos.GooglePhotosDownload INFO     downloading 401 photos/2009/07/P7290274.AVI
04-02 12:22:44 gphotos.GooglePhotosDownload DEBUG    COMPLETED 44 downloading photos/2009/07/P7290294.JPG
04-02 12:22:44 gphotos.GooglePhotosDownload DEBUG    COMPLETED 45 downloading photos/2009/07/P7290278.AVI
04-02 12:22:44 gphotos.GooglePhotosDownload DEBUG    COMPLETED 46 downloading photos/2009/07/P7290290.JPG
04-02 12:22:44 gphotos.GooglePhotosDownload DEBUG    COMPLETED 47 downloading photos/2009/07/P7290282.JPG
04-02 12:22:44 gphotos.GooglePhotosDownload DEBUG    COMPLETED 48 downloading photos/2009/07/P7290280.JPG
04-02 12:22:44 gphotos.GooglePhotosDownload DEBUG    COMPLETED 49 downloading photos/2009/07/P1000954.JPG
04-02 12:22:44 gphotos.GooglePhotosDownload DEBUG    COMPLETED 50 downloading photos/2009/07/P1000949.JPG
04-02 12:22:44 gphotos.GooglePhotosDownload ERROR    FAILURE 339 downloading photos/2009/07/P1000946.JPG
04-02 12:22:44 gphotos.GooglePhotosDownload ERROR    FAILURE 340 downloading photos/2009/07/P1000940.JPG
04-02 12:22:44 gphotos.GooglePhotosDownload INFO     downloading 402 photos/2009/07/P7290271.AVI
04-02 12:22:44 gphotos.GooglePhotosDownload INFO     downloading 403 photos/2009/07/P7290270.AVI
04-02 12:22:44 gphotos.GooglePhotosDownload INFO     downloading 404 photos/2009/07/P7290269.AVI
04-02 12:22:44 gphotos.GooglePhotosDownload INFO     downloading 405 photos/2009/07/P7290277.JPG
04-02 12:22:44 gphotos.GooglePhotosDownload INFO     downloading 406 photos/2009/07/P7290276.JPG
04-02 12:22:44 gphotos.GooglePhotosDownload INFO     downloading 407 photos/2009/07/P7290275.JPG
04-02 12:22:44 gphotos.GooglePhotosDownload INFO     downloading 408 photos/2009/07/P7290273.JPG
04-02 12:22:44 gphotos.GooglePhotosDownload INFO     downloading 409 photos/2009/07/P7290272.JPG
04-02 12:22:44 gphotos.GooglePhotosDownload INFO     downloading 410 photos/2009/07/P7290272 (2).JPG
04-02 12:22:44 gphotos.GooglePhotosDownload ERROR    FAILURE 341 downloading photos/2009/07/P7290271.AVI
04-02 12:22:44 gphotos.GooglePhotosDownload INFO     downloading 411 photos/2009/07/P7290268.JPG
04-02 12:22:44 gphotos.GooglePhotosDownload ERROR    FAILURE 342 downloading photos/2009/07/P7290274.AVI
04-02 12:22:44 gphotos.GooglePhotosDownload INFO     downloading 412 photos/2009/07/P7290268 (2).JPG
04-02 12:22:44 gphotos.GooglePhotosDownload ERROR    FAILURE 343 downloading photos/2009/07/P7290275.JPG
04-02 12:22:44 gphotos.GooglePhotosDownload INFO     downloading 413 photos/2009/07/P7290267.JPG
04-02 12:22:44 gphotos.GooglePhotosDownload ERROR    FAILURE 344 downloading photos/2009/07/P7290273.JPG
04-02 12:22:44 gphotos.GooglePhotosDownload INFO     downloading 414 photos/2009/07/P7290266.JPG
04-02 12:22:44 gphotos.GooglePhotosDownload ERROR    FAILURE 345 downloading photos/2009/07/P7290272 (2).JPG`

**Comment by gilesknap** [comment]
Hi,

There is a daily rate limit on API and on download URL. Gphotos-sync
reports the former correctly, but just errors on the second.

You need a pretty high speed connection to hit that though.

I can run 100mbits flat out for several hours.

If this is you issue it will go away after a day. Also I think I added the
error handling for this but it may still be in a branch.

The error handling just tells you what happened. Can't get around the
restriction.

**Comment by gilesknap** [comment]
Please can you pull the latest from the master branch and try that. It now gives more detail on failures in the download threads.

**Comment by blakeseufert** [comment]
Cool thanks!

**Comment by gilesknap** [comment]
@blakeseufert there is now a full release 2.14.2 with the improved error reporting, please give it a go.

**Comment by blakeseufert** [comment]
Thank you! Just got the latest docker, ran perfectly probably have to do a full sync to test the rate limiting. I'll let you know if i get some time to test that. Thank you again!

**Comment by gilesknap** [comment]
thanks for letting me know. closing
