### ISSUE TITLE
GPS

### ISSUE THREAD

**Issue by gosugimoto** [gilesknap/gphotos-sync#214]
Hi again,

I've tried the --get-locations but it doesn't seem to be recognised.  I realised that I had some photos with GPS (those were ones that i downloaded directly off phone...)  So I was mixed up to think they were from the script.

Has there been any movement with this to get GPS data for the pics?

Thanks!

**Comment by gilesknap** [comment]
sorry but my approach to scraping the GPS from google photos was blocked by google some time ago. I have removed the feature and dont yet have an alternative solution.

I don't think Google wants us to have all our data so you may never see a solution.

**Comment by gilesknap** [comment]
The readme has been updated to reflect the lack of GPS scraping.
