### ISSUE TITLE
Remove Duplicates?

### ISSUE THREAD

**Issue by swerb73** [gilesknap/gphotos-sync#215]
Hello Giles, awesome work with gphotos-sync, loving it!
I've been trying to find a way to remove duplicates from my google photos library and while I can find a way to identify them in a local filesystem I've been unable to figure how to resync that back to the library effectively removing those duplicates. Interesting using gphotos sync I've finally identified that I have roughly 38% duplicates (based only on the filename duplicates capability)!

Any thoughts or plan to add removal of duplicates to the roadmap?

**Comment by gilesknap** [comment]
Hi,

If the files are truely duplicates (they have the same EXIF ID) then Google Photos will only store one copy and link to it.

I think you mean you are using the gphotos-sync comparison feature?

How do you think these duplicate files came about? Do they have different dates. Can you post an example of where they occur (e.g. is it locally the same filename with (2) (3) etc. extensions)

I would recommend caution because filename match does not necessarily mean they are the same especially for early cameras.

If you are certain you have duplicates then gphotos-sync cant help with deletion because it is read only. But the database will contain enough info for you to discover the URL of each duplicate - some programming required to take advantage of this I'm afraid.

**Comment by swerb73** [comment]
Good morning Giles, thank you for the response.
 
Hmm, now that I dig deeper it appears while some are named the same they are different photos entirely (those ending in (2) and (3). I attached two examples (0941 and 0945) from May of last year.
 
I did find what I think is a duplicate in my google photos interface and when downloaded I get a (2) as well, attached is 0504 example.
 
If I were to have the path/URL to the actual photo that is a duplicate (now I’m worried that it isn’t all the (2) (3), etc photos) would it be possible to batch delete them?  This appears to be a problem all over the internet, can’t find an integrated way to find/delete duplicate photos in batch right from the google interface/API, I’d want to use EXIF info to be sure.  Some appear to be poking at it but I can’t find a finished product…

[NOTE: Realized I can't email the pics, is there another way for me to get you the examples?

Thanks for any guidance…
 
--Shannon

**Comment by gilesknap** [comment]
So Google won't store more than one copy of a photo. The one that you think
is a duplicate is probably a subtly edited version. I used to have massive
issues with duplicates when the sync was via Google drive. But these days,
the way that I index the photos via the API should only get one copy of
each photo, it will create multiple links to that photo of it appears on
more than one album.

In short, you are probably ok. Working out that two very similar photos are
similar is a manual process I'm afraid.

If you really do have duplicates then I don't think the API can help. As I
mentioned there are loads of restrictions. One of those is that it can only
delete photos created by the same App.

There are some examples of people driving the Google photos Web app with
Java script, however I would not risk my photo library with such a "hack".

**Comment by swerb73** [comment]
Hi Giles, thanks. I wonder if my prior use of Google Drive also created some of these issues since I can’t find a “duplicate” since May of last year. I use the iOS app on my phone as the source of truth to backup photos I take on my phone otherwise the webapp for anything I take outside the phone.

I suppose over time if it’s that big of a deal I can manually delete them.

Thanks for all your help.

**Comment by gilesknap** [comment]
If you used to sync through Google Drive then you may have "duplicates" that are different EXIF UIDS, but similar content.

Did you also synchronise your Google Drive to a local disk? I did using InSync.

If you edited your photo in a Google Drive linked tool, in Google Photos itself or on your PC then there is a chance that two photos represent the before and after of this edit. Obviously this includes subtle things like adjusting the light levels a little. I went to a lot of trouble to purge my library of such things and it involved custom code written to the Picassa API which was current when I switched to Google but also lots of manual intervention.

The worst offender is local edits and syncing local disk to Google Drive so if you did not do this then you may be OK.

**Comment by swerb73** [comment]
Hi Giles,
You’re probably onto it. I was using Google Drive and at various times would sync it as well, not realizing this may be part of the problem.

I’ve now experimented with uploading various duplicates, noting they don’t show up duplicate, likewise I’ve seen that if I upload an old pic with proper EXIF meta-data/date it ends up in the correct place in the overall album.

I remain surprised Google just doesn’t provide some simple capability to deal with this. I do appreciate your assistance.

Curious – when I use gphotos-sync, for example if I run it each day, does it touch the files/folders that already exist in the target director (running on Windows 10) which could cause other sync tools I use (like google sync, onedrive, etc) to want to retouch/sync all those files to the cloud?  I thought it just scanned the database to determine if it needed to get/delete any local files?

Thanks.

**Comment by gilesknap** [comment]
gphotos-sync should no touch any files that have not changed, but the links folders that represent the albums are completely recreated every time any changes occur in the library.

Perhaps this is what you are seeing?

**Comment by swerb73** [comment]
Ahh, yes, that’s it. I just tested and it appears it’s the album linked files.  Thanks again.

-- Shannon M. Werb
shannon@swerb.com

**Comment by gilesknap** [comment]
closing - feel free to continue the discussion if needed
