### ISSUE TITLE
Clarify in snap description that this is a CLI utility

### ISSUE THREAD

**Issue by Flimm** [gilesknap/gphotos-sync#217]
I found gphotos-sync when looking for a tool to download my photos in Google Photos to the desktop. I found this page describing the snap package: https://snapcraft.io/gphotos-sync

I couldn't find out from reading the description whether this tool uses a CLI or a GUI. I recommend modifying the description to say:

> gphotos-sync is a command-line utility that ...

**Comment by gilesknap** [comment]
I would have to defer this to @popey who manages the snap.

**Comment by gilesknap** [comment]
However there is a separate project underway to develop a GUI (its not a snap though) https://github.com/michael79bxl/gphotos-sync-ui

**Comment by popey** [comment]
Thanks for the feedback, and the ping. I have updated the first line of the description (that most people don't read ;) ) to say _Google Photos Sync is a command-line utility which downloads your Google Photos to the local file system._

**Comment by Flimm** [comment]
Thank you so much! One less paper cut.
