### ISSUE TITLE
Failure Disk or Database Full

### ISSUE THREAD

**Issue by ben-digitalhive** [gilesknap/gphotos-sync#219]
Setting up a new install and all seemed ok.  Running on Pi3B+.  Installed Samba and am getting a failure reporting disk or database full however df shows /media/usb is 84%

Had successfully run a number of syncs to /media/usb/GPhotosBackup/ then started getting failure so created /media/usb/GPhotosBackup1/  but still get the same issue.

pi@raspberrypi:~/gphotos-sync $ pipenv run gphotos-sync /media/usb/GPhotosBackup1/ --start-date 2020-01-01
04-14 09:11:06 WARNING  gphotos-sync 2.14.0 2020-04-14 09:11:06.936623
Please go here and authorize, https://accounts.google.com/o/oauth2/v2/auth?response_type=code&client_id=236512763732-b47m8405htdkcnqdjcuctriqnt7gatcm.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fphotoslibrary.readonly+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fphotoslibrary.sharing&state=VibmpuJScAFtwnVQMW4TkAG2hfvXQV&access_type=offline&prompt=select_account
Paste the response token here:4/ygFh6XZDh5xLwAi3bAvdjTk5FvNIdh11hZA1TW1GHovVY3rktw2lINk
04-14 09:11:43 WARNING  Indexing Google Photos Files ...
04-14 09:11:52 ERROR
Process failed.
Traceback (most recent call last):
  File "/home/pi/.local/share/virtualenvs/gphotos-sync-3r3jkhDp/lib/python3.7/site-packages/gphotos/Main.py", line 418, in main
    self.start(args)
  File "/home/pi/.local/share/virtualenvs/gphotos-sync-3r3jkhDp/lib/python3.7/site-packages/gphotos/Main.py", line 369, in start
    self.do_sync(args)
  File "/home/pi/.local/share/virtualenvs/gphotos-sync-3r3jkhDp/lib/python3.7/site-packages/gphotos/Main.py", line 333, in do_sync
    self.google_photos_idx.index_photos_media()
  File "/home/pi/.local/share/virtualenvs/gphotos-sync-3r3jkhDp/lib/python3.7/site-packages/gphotos/GooglePhotosIndex.py", line 182, in index_photos_media
    self.write_media_index(media_item, False)
  File "/home/pi/.local/share/virtualenvs/gphotos-sync-3r3jkhDp/lib/python3.7/site-packages/gphotos/GooglePhotosIndex.py", line 72, in write_media_index
    self._db.put_row(GooglePhotosRow.from_media(media), update)
  File "/home/pi/.local/share/virtualenvs/gphotos-sync-3r3jkhDp/lib/python3.7/site-packages/gphotos/LocalData.py", line 157, in put_row
    self.cur.execute(query, row.dict)
sqlite3.OperationalError: database or disk is full
04-14 09:11:52 WARNING  Done.

pi@raspberrypi:~/gphotos-sync $ df
Filesystem     1K-blocks      Used Available Use% Mounted on
/dev/root        1601904   1504996         0 100% /
devtmpfs          469540         0    469540   0% /dev
tmpfs             474148         0    474148   0% /dev/shm
tmpfs             474148      7284    466864   2% /run
tmpfs               5120         4      5116   1% /run/lock
tmpfs             474148         0    474148   0% /sys/fs/cgroup
/dev/mmcblk0p1    258095     53465    204631  21% /boot
/dev/sda1      488384508 405527964  82856544  84% /media/usb
tmpfs              94828         0     94828   0% /run/user/1000
pi@raspberrypi:~/gphotos-sync $

**Comment by ben-digitalhive** [comment]
[gphotos.log](https://github.com/gilesknap/gphotos-sync/files/4474023/gphotos.log)

**Comment by gilesknap** [comment]
Hi, this is interesting. Can you take a look at what size the database file is and report what type of filesystem your USB disk is formatted with?

Perhaps you have reached the max file size of your filesystem?

**Comment by ben-digitalhive** [comment]
OK so im a little new to Linux etc so will try to keep up.  Here is what I checked:

1. I thought it might be my fstab mounting option of ntfs so unmounted and did a manual mount with ntfs-3g - no change in behaivour

`sudo mount -t ntfs-3g /dev/sda1 /media/usb`

2. I thought it might again be spzce related but still hae 84% free

`
pi@raspberrypi:~/gphotos-sync $ df -T
Filesystem     Type     1K-blocks      Used Available Use% Mounted on
/dev/root      ext4       1601904   1535172         0 100% /
devtmpfs       devtmpfs    469540         0    469540   0% /dev
tmpfs          tmpfs       474148         0    474148   0% /dev/shm
tmpfs          tmpfs       474148      7256    466892   2% /run
tmpfs          tmpfs         5120         4      5116   1% /run/lock
tmpfs          tmpfs       474148         0    474148   0% /sys/fs/cgroup
/dev/mmcblk0p1 vfat        258095     53465    204631  21% /boot
tmpfs          tmpfs        94828         0     94828   0% /run/user/1000
/dev/sda1      fuseblk  488384508 405527996  82856512  84% /media/usb
`

3. I dont think its permissions as it created a new log file

To answer your questions specifically above:
a. the DB file is 10Mb only
b. file system is NTFS
c. im not sure there is a file size limit that would be broken here right?  Is there a way to check?

**Comment by ben-digitalhive** [comment]
OK I think the issue is my root folder is full and this is where /tmp is:
`/dev/root ext4 1601904 1535172 0 100% /`

I cleaned up some space and reran and seem to be working again.  This would correlate with me installing SAMBA.

This is the thread that pointed me to it https://discourse.beets.io/t/sqlite3-operationalerror-database-or-disk-is-full/150/9

Will let it run and uninstall SAMBA and see if the error comes back.

**Comment by ben-digitalhive** [comment]
Right so lesson learnt - Throw away all 2Gb MicrosSD cards so they dont get confused with decent sized ones!  This was in fact the issue and im happy to confirm it as not an issue with your application.

I dont know how feasible it is but checking the size of /tmp may be a good check in the application code?

**Comment by gilesknap** [comment]
Ben, thanks for the effort in debugging this.

Its a shame that the error message did not lead you more directly to tmp
file space, however I'm going to blame sqlite for that :-)
