### ISSUE TITLE
Backup restarts when external drive is reinserted

### ISSUE THREAD

**Issue by arewm** [gilesknap/gphotos-sync#22]
I am setting an external HD as my backup device. The backup runs to completion fine, but when I eject the HD and reinsert it later to back up again, `gphotos-sync` detects that all of the files have been modified and re-downloads them.

I know that you are not actively maintaining this, but do you know about this issue/have an idea why it might be happening?

**Comment by gilesknap** [comment]
That sounds odd. Can you give some details about what the path is to the root folder? does the second download overwrite the first or appear in a different location?

**Comment by gilesknap** [comment]
Just reviewing the Issues on this project. I think if you do not have a fstab entry for your external drive you may be getting an auto generated and different absolute path to your backup folder on each insertion.

gphotos works on full path - I wanted to fix this but may not get around to it. You can give your HD a permanent path by adding it to fstab though.

**Comment by gilesknap** [comment]
The new API version of gphotos 2.0 uses relative path and should fix this issue. @arewm can you give this a try if you are still interested? thanks.

**Comment by gilesknap** [comment]
I've tested this and it all seems good. Please reopen if you still have an issue.
