### ISSUE TITLE
Can you give us a command for the symbolic link because I don't know where to put it

### ISSUE THREAD

**Issue by Muda42** [gilesknap/gphotos-sync#228]

**Comment by gilesknap** [comment]
Sorry I don't understand.

What do you want the command to do?

**Comment by Muda42** [comment]
I would like to know where in my configuration should I create the symbolic link

**Comment by gilesknap** [comment]
You don't need to create any symbolic links.
gphotos-sync will create symbolic links from the albums folders to the photos for you.

If your filesysystem does not support symbolic links then you will be notified that it will not create any album folders.

If this is the error you are getting then please tell me what filesystem you are using as the sync folder. Or at least if you are running Windows/Linux/Mac?

Thanks, giles.

**Comment by Muda42** [comment]
What I meant is the symlink for the client token on Windows

**Comment by gilesknap** [comment]
No symlinks required for the client token.

- Follow the instructions here to get the token: [Ouath2 for gphotos-sync](https://docs.google.com/document/d/1ck1679H8ifmZ_4eVbDeD_-jezIcZ-j6MlaNaeQiz7y0/edit?usp=sharing)
- save the token file as ```C:\Users\<username>\AppData\Local\gphotos-sync\gphotos-sync\client_secret.json```

**Comment by Muda42** [comment]
Ok thanks !
