### ISSUE TITLE
Enabling Symlinks help

### ISSUE THREAD

**Issue by dazw86** [gilesknap/gphotos-sync#229]
Hi guys, I'm trying to run this on windows 10 and believe I have it installed ok. I did forget about symlinks until I went to run it and it show the error in the cmd window. I stopped, enabled them as per the instructions and then re-ran it. I still get the same error though.

Does anyone have any advice please?

Thank you!

**Comment by gilesknap** [comment]
Having enabled symlinks you may need to log out and log back in again.

**Comment by dazw86** [comment]
Hi, Thanks for the response. I have logged out still no joy. I even added the everyone group to see if that would help, nothing. Logged out and restarted. Still the same.

04-28 13:35:46 WARNING  gphotos-sync 2.14.0 2020-04-28 13:35:46.534456
04-28 13:35:46 ERROR    Symbolic links not supported
04-28 13:35:46 ERROR    Albums are not going to be synced - requires symlinks

**Comment by gilesknap** [comment]
I assume you are following the instructions at https://community.perforce.com/s/article/3472?

Can you perform the mlink command at the beginning of the article? If not then you have not managed to enable symlinks. If so then there is something wrong with gphotos-sync symlink detection.

Do you know which filesystem your gphotos-sync root directory is?

**Comment by dazw86** [comment]
Hi, sorry for the delay. Yes I followed that article and also a second one I found to make sure.

I have gone through all the steps again and it says the same thing. I have continued and it downloaded the photos ok but no albumn details.

No, sorry, how do I find out?

**Comment by gilesknap** [comment]
Please can you perform the mlink command at the beginning of the article?

**Comment by gilesknap** [comment]
> Now it is syncing the photos, does it continue to do this in the background?

gphotos-sync is designed to be run as a background process but you are responsible for setting up the cron job or equivalent to achieve this. I've not really thought about how to do this on Windows I'm afraid, but I guess there is a choice of scheduling mechanisms available.

Did you try the mlink command at the start of https://community.perforce.com/s/article/3472. This tests whether you have succeeded in setting up symlink support.

**Comment by gilesknap** [comment]
closing for now.
