### ISSUE TITLE
Script fails w/ AttributeError when syncing

### ISSUE THREAD

**Issue by szab100** [gilesknap/gphotos-sync#231]
Hi,

I just tried to use your script, but it fails with the following error (indexing has finished, the problem occurs at sync stage):

05-11 03:02:56 INFO     Indexed 5313 photos/2018/02/IMG_0722.PNG
05-11 03:02:56 INFO     Indexed 5314 photos/2018/02/IMG_0721.JPG
05-11 03:02:56 INFO     Indexed 5315 photos/2018/02/IMG_0718.JPG
05-11 03:02:56 INFO     Indexed 5316 photos/2018/02/IMG_0717.PNG
05-11 03:02:56 INFO     Indexed 5317 photos/2018/02/IMG_0704.JPG
05-11 03:02:56 INFO     Indexed 5318 photos/2018/02/IMG_0703.JPG
05-11 03:02:56 INFO     Indexed 5319 photos/2018/02/IMG_0702.JPG
05-11 03:02:56 INFO     Indexed 5320 photos/2018/02/IMG_0701.JPG
05-11 03:02:56 INFO     Indexed 5321 photos/2018/02/IMG_0699.JPG
05-11 03:02:56 INFO     Indexed 5322 photos/2018/02/IMG_0698.JPG
05-11 03:02:56 INFO     Indexed 5323 photos/2018/02/IMG_0700.MOV
05-11 03:02:56 INFO     Indexed 5324 photos/2018/02/IMG_0697.JPG
05-11 03:02:56 INFO     Indexed 5325 photos/2018/02/IMG_0696.MOV
05-11 03:02:56 INFO     Indexed 5326 photos/2018/02/IMG_0695.JPG
05-11 03:02:56 INFO     Indexed 5327 photos/2018/02/IMG_0694.PNG
05-11 03:02:56 INFO     Indexed 5328 photos/2018/02/IMG_0693.JPG
05-11 03:02:56 INFO     Indexed 5329 photos/2018/02/IMG_0692.JPG
05-11 03:02:56 INFO     Indexed 5330 photos/2018/02/IMG_0691.JPG
05-11 03:02:56 INFO     Indexed 5331 photos/2018/02/IMG_0690.PNG
05-11 03:02:56 INFO     Indexed 5332 photos/2018/02/IMG_0690 (2).PNG
05-11 03:02:56 INFO     Saving Database ...
05-11 03:02:57 INFO     Database Saved.
05-11 03:02:57 ERROR
Process failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gphotos/Main.py", line 418, in main
    self.start(args)
  File "/usr/local/lib/python3.7/site-packages/gphotos/Main.py", line 369, in start
    self.do_sync(args)
  File "/usr/local/lib/python3.7/site-packages/gphotos/Main.py", line 333, in do_sync
    self.google_photos_idx.index_photos_media()
  File "/usr/local/lib/python3.7/site-packages/gphotos/GooglePhotosIndex.py", line 164, in index_photos_media
    media_item_json, to_lower=self.case_insensitive_fs
  File "/usr/local/lib/python3.7/site-packages/gphotos/GooglePhotosMedia.py", line 25, in __init__
    if self.is_video():
  File "/usr/local/lib/python3.7/site-packages/gphotos/BaseMedia.py", line 33, in is_video
    return self.mime_type.startswith("video")
AttributeError: 'NoneType' object has no attribute 'startswith'
05-11 03:02:57 WARNING  Done.
05-11 03:02:57 INFO     Elapsed time = 0:02:35.420586

**Comment by gilesknap** [comment]
Yuk, uncaught exception! 

Which version are you using please? ```--help``` will show the version number.

Thanks

**Comment by szab100** [comment]
This is the 'latest' docker image.

**Comment by gilesknap** [comment]
please can you try the last tagged version docker pull gilesknap/gphotos-sync:2.14.0 and let me know how you get on.

Thanks

**Comment by szab100** [comment]
@gilesknap sure, I just pulled & ran 2.14.0 and got the same `exception:

`
ash-4.3# docker start -ai gphotos-sync
05-12 06:25:24 INFO     version: 2.10.4, database schema version 5.7
05-12 06:25:25 WARNING  Indexing Google Photos Files ...
05-12 06:25:25 INFO     searching for media start=None, end=None, videos=True
05-12 06:26:20 INFO     Saving Database ...
05-12 06:26:20 INFO     Database Saved.
05-12 06:26:20 ERROR
Process failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gphotos/Main.py", line 398, in main
    self.start(args)
  File "/usr/local/lib/python3.7/site-packages/gphotos/Main.py", line 351, in start
    self.do_sync(args)
  File "/usr/local/lib/python3.7/site-packages/gphotos/Main.py", line 329, in do_sync
    new_files = self.google_photos_idx.index_photos_media()
  File "/usr/local/lib/python3.7/site-packages/gphotos/GooglePhotosIndex.py", line 157, in index_photos_media
    media_item = GooglePhotosMedia(media_item_json, to_lower=self.case_insensitive_fs)
  File "/usr/local/lib/python3.7/site-packages/gphotos/GooglePhotosMedia.py", line 23, in __init__
    if self.is_video():
  File "/usr/local/lib/python3.7/site-packages/gphotos/BaseMedia.py", line 53, in is_video
    return self.mime_type.startswith('video')
  File "/usr/local/lib/python3.7/site-packages/gphotos/GooglePhotosMedia.py", line 81, in mime_type
    return self.__media_json['mimeType']
KeyError: 'mimeType'
05-12 06:26:20 WARNING  Done.
05-12 06:26:20 INFO     Elapsed time = 0:00:55.482922
ash-4.3#
`

**Comment by gilesknap** [comment]
OK, thanks, I'll investigate this evening (UK).

**Comment by gilesknap** [comment]
Hi I have just released 2.14.2. I've added a fix to cope with the possibility of an item having no mimetype  (at least in the line of code that is failing for you).

It might help, let me know how you get on.

There is perhaps something corrupted in your Google Photos Library since there has been no previous reports of an item with no mimetype. The  google metadata should always contain a value for this attribute as far as I know.

**Comment by szab100** [comment]
@gilesknap Thank you Giles for the quick fix, it is still running (for 3+ hours now), but seems to be working fine, so feel free to close this issue now. If you rely on the mimeType, maybe you could add a warning log entry there, so you can see if this issue becomes more frequent

Am I correct that with this docker image, as long as I am starting it every ? hours/days, the auth token gets auto-refreshed? So it should not require a browser authorization again? I am planning to run it on a headless system, scheduled with cron. Thanks!

**Comment by gilesknap** [comment]
I agree re having a warning. In the meantime it may be interesting to discover the scope of the issue for your library.
Please can you try this? (it will require installing sqlite3):
```
cd [your gphotos-sync target directory]
sqlite3 gphotos.sqlite
sqlite> select Path,  FileName, MimeType  from SyncFiles where MimeType=NULL or MimeType='';
```

Thanks!

**Comment by szab100** [comment]
Sure, see the output below.. sqlite's syntax seems to be a bit different.. but it seems there's only one item that caused the issue.. hope this helps. Thanks!

`
ash-4.3# sqlite3 gphotos.sqlite
SQLite version 3.10.2 2016-01-20 15:27:19
Enter ".help" for usage hints.
sqlite> select count(*) from SyncFiles where MimeType!=NULL and MimeType!='';
0
sqlite> select count(*) from SyncFiles;
16123
sqlite> select count(*) from SyncFiles WHERE MimeType is NOT NULL;
16122
sqlite> select Path,  FileName, MimeType from SyncFiles where MimeType is NULL;
photos/2018/02|A0A4BE5F-EAF7-419A-A0A9-4D72224A5E48-1559-0000016DB3AB6681.jp2|
sqlite>
`

**Comment by gilesknap** [comment]
OK I had never heard of JP2 file extension before so maybe Google does not have a mimeType for it. I'm pretty sure this is a benign issue and we have fixed it.

If you would like to find out what the file is, go look at 
```
[your gphotos-sync root folder]/photos/2018/02|A0A4BE5F-EAF7-419A-A0A9-4D72224A5E48-1559-0000016DB3AB6681.jp2
```
