### ISSUE TITLE
Without --rescan no new photos are downloaded

### ISSUE THREAD

**Issue by xyzulu** [gilesknap/gphotos-sync#237]
**Describe the bug**
Unless I use the --rescan switch, just running gphotos-sync each time doesn't download any new photos

**To Reproduce**
I'm using this on raspian, with a network mounted (but with symlink support) drive.
pipenv run gphotos-sync /nas/folder
^ first run works.

Add new photos:
pipenv run gphotos-sync /nas/folder
^ No new photos are downloaded, or even detected (I checked the logs)

Instead run:

pipenv run gphotos-sync --rescan /nas/folder
^New photos are detected and downloaded.

This isn't optimal, as the albums (symlinks) are all deleted and then relinked and the process takes a while of course (25mins to download 4 new photos I added as a test). Did I miss something? 

gphotos.Main INFO     version: 2.14.2, database schema version 5.7

**Comment by gilesknap** [comment]
gphotos-sync by default filters its indexing by the last scan date so you should get incremental downloads.

Potentially things could be awry if your clock is not set correctly, can you verify that your raspi has the correct time and timezone?

**Comment by gilesknap** [comment]
BTW it will always rebuild the album links from scratch if any new files are downloaded. However this is pretty quick. Indexing and entire big library will take time.

**Comment by xyzulu** [comment]
> gphotos-sync by default filters its indexing by the last scan date so you should get incremental downloads.
I did wait until the next day to run it again, but perhaps I need to wait 48hrs just to be sure.
 
> Potentially things could be awry if your clock is not set correctly, can you verify that your raspi has the correct time and timezone?
Time and timezone are correct, I just rechecked.

**Comment by gilesknap** [comment]
Lets take a look at what is being sent to Google.

Please can you run again with ```--log-level trace``` and send me the .log and .trace files from your target directory. You can send directly to gilesknap@gmail.com if you prefer but there should not be any particularly sensitive info in the logs.

Thanks.

**Comment by xyzulu** [comment]
The regular command, or the rescan command?

**Comment by gilesknap** [comment]
regular with no rescan.

**Comment by xyzulu** [comment]
Will do, I'll email you shortly.

**Comment by gilesknap** [comment]
In fact best thing to do would be.

- upload a new photo or two
- run with no rescan and trace
- send the log and trace 
- run again with --rescan and trace
- send me the files again (these will be huge if you have a large library - use file.io or similar)

**Comment by xyzulu** [comment]
Will do.. I will wait 48hrs after adding a new image just to be sure.
Thanks

**Comment by xyzulu** [comment]
So, as it turned out.. the issue was with pipenv and calling it via cron. Despite creating a script, unless you call pipenv in this way `/home/pi/.local/bin/pipenv run gphotos-sync sync_folder` instead of `pipenv run gphotos-sync sync_folder`

Setting it this way has allowed the cronjob to run.. and despite not waiting a full 48hrs, new photos are downloading.

**Comment by gilesknap** [comment]
> BTW it will always rebuild the album links from scratch if any new files are downloaded. However this is pretty quick. Indexing an entire big library will take time.

ah. I Just ran gphotos-sync on my library with my destination folder recently moved to my raspi NFS  NAS. The album link creation took 20 minutes, maybe its time for a rethink on this #238

**Comment by gilesknap** [comment]
> So, as it turned out.. the issue was with pipenv and calling it via cron. Despite creating a script, unless you call pipenv in this way
> `/home/pi/.local/bin/pipenv run gphotos-sync sync_folder`

Right, I think this is due to cron not loading your .profile and therefore /home/pi/.local/bin is not in your path (my cron script has exactly this). This is a good tip and I need a section in the readme on setting up cron.

Thanks for useful investigation.

**Comment by xyzulu** [comment]
Yip, I think some documentation about this would be good.
