### ISSUE TITLE
Feature request for multiple account

### ISSUE THREAD

**Issue by evazzoler** [gilesknap/gphotos-sync#239]
Hi, thank you for this useful amazing piece of software.
I have a little request...
I run gphotos-sync on a linux vm on my nas for backing up my pictures. I'd like to do it for everyone in my family without creating environments or different linux users increasing the management complexity.

It would be useful in my case that gphotos-sync would accept a parameter that optionally permits to specify the location of "client_secret.json" instead to keep it from a predefined location.

This way I could write down a bash script cron acted that sequentially (without overlapping) sync multiple accounts and notify issues or update the "last sync" on a snmp supervisor console.

Download speed limit would be another happy parameter, but I suppose is more time spending to implement.

Thanks!

**Comment by gilesknap** [comment]
Hi Enrico,

I'm glad you are enjoying gphotos-sync.

I already have you covered re client secret, see the option ```--secret```. Also note that you can see the whole list of options using ```--help```.

**Comment by evazzoler** [comment]
I apologize for my gap! I usually RTFM, and this is what I did for gphotos-sync. I really missed that option in the middle of the others. :-(
Sorry for having let you spend time for nothing!
Thank you!

**Comment by gilesknap** [comment]
No worries, is nice to have an easy ticket occasionally!
