### ISSUE TITLE
Can't seem to work anything

### ISSUE THREAD

**Issue by thebeyonder001** [gilesknap/gphotos-sync#240]
I am using ubuntu and to use the repo, i cloned the github repo in the home directory and when nothing seemed to work i even used "pip install gphotos-sync".Now i am in the /home/gphotos-sync directory and when i run "pipenv run gphotos-sync" or just "gphotos-sync" i get the error :
the use
`(gphotos-sync-vdyPsvd7) beyonder100000@beyonder100000-HP-Laptop-15-bs1xx:~/gphotos-sync$ gphotos-sync 
usage: gphotos-sync [-h] [--album ALBUM] [--log-level LOG_LEVEL]
                    [--logfile LOGFILE] [--compare-folder COMPARE_FOLDER]
                    [--favourites-only] [--flush-index] [--rescan]
                    [--retry-download] [--skip-video] [--skip-shared-albums]
                    [--album-date-by-first-photo] [--start-date START_DATE]
                    [--end-date END_DATE] [--db-path DB_PATH]
                    [--albums-path ALBUMS_PATH] [--photos-path PHOTOS_PATH]
                    [--use-flat-path] [--omit-album-date] [--new-token]
                    [--index-only] [--skip-index] [--do-delete] [--skip-files]
                    [--skip-albums] [--use-hardlinks] [--no-album-index]
                    [--case-insensitive-fs] [--max-retries MAX_RETRIES]
                    [--max-threads MAX_THREADS] [--secret SECRET] [--archived]
                    [--progress] [--max-filename MAX_FILENAME] [--ntfs]
                    root_folder
gphotos-sync: error: the following arguments are required: root_folder
`
when i use "gphotos-sync <ANY DIRECTORY>"
i get this:
`(gphotos-sync-vdyPsvd7) beyonder100000@beyonder100000-HP-Laptop-15-bs1xx:~/gphotos-sync$ gphotos-sync /gphotos/
Traceback (most recent call last):
  File "/home/beyonder100000/.local/share/virtualenvs/gphotos-sync-vdyPsvd7/bin/gphotos-sync", line 8, in <module>
    sys.exit(main())
  File "/home/beyonder100000/.local/share/virtualenvs/gphotos-sync-vdyPsvd7/lib/python3.7/site-packages/gphotos/Main.py", line 432, in main
    GooglePhotosSyncMain().main()
  File "/home/beyonder100000/.local/share/virtualenvs/gphotos-sync-vdyPsvd7/lib/python3.7/site-packages/gphotos/Main.py", line 395, in main
    root_folder.mkdir(parents=True, mode=0o700)
  File "/usr/lib/python3.7/pathlib.py", line 1258, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/gphotos'
`
Is there something that i am doing wrong??Help!

**Comment by gilesknap** [comment]
Hi.

You are running gphotos-sync correctly using pipenv in the first example above. You just need to supply a root folder, i.e. a path to a folder where you would like your synced photos to go to.

e.g. assuming you installed gphotos-sync in your home directory:
```
cd gphotos-sync 
pipenv run gphotos-sync ../photos_backup
```

**Comment by thebeyonder001** [comment]
`(gphotos-sync-vdyPsvd7) beyonder100000@beyonder100000-HP-Laptop-15-bs1xx:~/gphotos-sync$ pipenv run gphotos-sync ../new
05-25 15:03:08 WARNING  gphotos-sync 2.14.2 2020-05-25 15:03:08.281186 
05-25 15:03:11 ERROR    
Process failed. 
Traceback (most recent call last):
  File "/home/beyonder100000/.local/share/virtualenvs/gphotos-sync-vdyPsvd7/lib/python3.7/site-packages/gphotos/Main.py", line 417, in main
    self.setup(args, db_path)
  File "/home/beyonder100000/.local/share/virtualenvs/gphotos-sync-vdyPsvd7/lib/python3.7/site-packages/gphotos/Main.py", line 282, in setup
    scope, credentials_file, secret_file, int(args.max_retries)
  File "/home/beyonder100000/.local/share/virtualenvs/gphotos-sync-vdyPsvd7/lib/python3.7/site-packages/gphotos/authorize.py", line 46, in __init__
    secrets = all_json["installed"]
KeyError: 'installed'
05-25 15:03:11 WARNING  Done. 
this occured`

**Comment by thebeyonder001** [comment]
Is it something related to where my client_secret.json file is stored?

**Comment by gilesknap** [comment]
It looks to me as though it has found your client_secret.json but that the file does not contain the correct information.

It should look something like this:
```
{
    "installed": {
        "client_id": "redacted_jffirqf2.apps.googleusercontent.com",
        "project_id": "gphotos-sync-274719",
        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
        "token_uri": "https://oauth2.googleapis.com/token",
        "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
        "client_secret": "redacted",
        "redirect_uris": [
            "urn:ietf:wg:oauth:2.0:oob",
            "http://localhost"
        ]
    }
}
```

**Comment by thebeyonder001** [comment]
I opened it and it says "web" instead of "installed".
Do i need to get new client credentials or can i just edit it inside the file

**Comment by gilesknap** [comment]
I think you chose an incorrect option when creating the secret. Please follow this and you should be good [OAuth](https://docs.google.com/document/d/1ck1679H8ifmZ_4eVbDeD_-jezIcZ-j6MlaNaeQiz7y0/edit?usp=sharing).

If you did already follow the above then I may have a documentation bug.

**Comment by thebeyonder001** [comment]
Actually i did follow the steps properly
But there was no option of "others" as in the page 5 of the doc you shared

**Comment by gilesknap** [comment]
This issue came up before and I then published the document. That fixed it for the previous reporters so I think there is something subtle about the sequence of clicks that makes the others option not show.

It is always possible that Google has recently changed the pages.

If you would like me to diagnose what is going on for you then the only thing I can suggest is that you go through the steps again and screenshot them and send to me.

**Comment by thebeyonder001** [comment]
okay

**Comment by thebeyonder001** [comment]
What option should i choose?
https://docs.google.com/document/d/1-xIVgyNzGmg2UoHTkzAlQFeAjVaT-T6QYcqTEyZykpY/edit?usp=sharing

(the series of ss  took)

**Comment by gilesknap** [comment]
Hi indeed it looks like the Google pages have changed. I would guess that
the desktop app option is the one that you need.

If it works for you I'll update my document with your screenshot (if you
are OK with that)

Thanks.

**Comment by thebeyonder001** [comment]
Yes, that's alright.
I shall try out the desktop app option and send the screenshots

**Comment by thebeyonder001** [comment]
I tried out the desktop app option
and i after i ran :
` pipenv run gphotos-sync ../new`
and then the authorization step
My doubt where do i find the downloaded photos;I have searched all the relevant directories.

**Comment by thebeyonder001** [comment]
`pipenv run gphotos-sync ../new

05-25 19:21:26 WARNING  gphotos-sync 2.14.2 2020-05-25 19:21:26.432048 

05-25 19:23:39 WARNING  Indexing Google Photos Files ... 

05-25 19:23:41 WARNING  indexed 3 items 

05-25 19:23:41 WARNING  Downloading Photos ... 

05-25 19:24:42 ERROR    
Process failed. 
Traceback (most recent call last):
  File "/home/beyonder100000/.local/share/virtualenvs/gphotos-sync-vdyPsvd7/lib/python3.7/site-packages/gphotos/Main.py", line 418, in main
    self.start(args)
  File "/home/beyonder100000/.local/share/virtualenvs/gphotos-sync-vdyPsvd7/lib/python3.7/site-packages/gphotos/Main.py", line 369, in start
    self.do_sync(args)
  File "/home/beyonder100000/.local/share/virtualenvs/gphotos-sync-vdyPsvd7/lib/python3.7/site-packages/gphotos/Main.py", line 337, in do_sync
    files_downloaded = self.google_photos_down.download_photo_media()
  File "/home/beyonder100000/.local/share/virtualenvs/gphotos-sync-vdyPsvd7/lib/python3.7/site-packages/gphotos/GooglePhotosDownload.py", line 155, in download_photo_media
    self.do_download_complete(futures_left)
  File "/home/beyonder100000/.local/share/virtualenvs/gphotos-sync-vdyPsvd7/lib/python3.7/site-packages/gphotos/GooglePhotosDownload.py", line 306, in do_download_complete
    e = future.exception(timeout=timeout)
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 470, in exception
    raise TimeoutError()
concurrent.futures._base.TimeoutError
05-25 19:24:42 WARNING  Done. 
`

**Comment by thebeyonder001** [comment]
Hey it worked out.
#169 was the solution and then i re-executed the commands.
Thanks for the support .

**Comment by gilesknap** [comment]
I've updated the document with your change. Thanks.

**Comment by HiFish8472** [comment]
I ha the Same issue as OP, no "other"available and google suggests/preselects web application. After creating a new secret with "Desktop app" everything is fine!

**Comment by gilesknap** [comment]
@HiFish8472 where did you read about 'other'? I thought the docs were updated to sat Desktop app.
