### ISSUE TITLE
Improve documentation for the autorization process with docker after submitting the given autorization link

### ISSUE THREAD

**Issue by oweitman** [gilesknap/gphotos-sync#243]
i have a setup with the docker container.
the documentation lacks information about of the best practice to enter the authorization code after granting access for the application.

1) running docker container
2) let the docker container run
3) delete all files in the config directory except the file "client_secret.json"
4) start a console into the docker container
5) start the gphotos-sync application with the same settings you configured in your docker-startup file for my special case with mounted NAS with NFS and addidtional debug settings
`gphotos-sync /storage --log-level trace --use-hardlinks --progress --db-path /config
`
6) after the start of the application you get the google-link, enter the link in a browser and copy the secret code
7) paste the code in the docker-console of your gphotos-sync container
8) exit the console
9) restart your container and after that it should index and download your photos

**Comment by gilesknap** [comment]
Thanks, I need to add a separate Docker configuration page. (I'm not particularly familiar with docker since the scripts were provided by a contributor).

**Comment by jkaplon** [comment]
+1 from another Docker user.
The auth-process is infrequent enough that I completely forget how it's supposed to go each time.

Thanks for this project (especially the Docker and Snap support), it's been a great refuge after google cut all ties between drive and photos.

**Comment by gilesknap** [comment]
@jkaplon do the steps outlined above by @oweitman work for you?

If so I will add into the readme for now (I'm not getting much time to spend on this project currently)

**Comment by jkaplon** [comment]
The steps are a little different than my recollection from 6-months ago, but they're definitely helpful.
I think I ran my container interactively, so steps 1-5 were blended together for me.
Most important thing is to mention is the need to visit the URL in a browser and paste code back into the container console.

**Comment by Darkwolf1515** [comment]
Yeah, my synology nas through docker is the only way ill be able to run this, can anyone help me get it up and running?

**Comment by gilesknap** [comment]
@Darkwolf1515 do the steps above https://github.com/gilesknap/gphotos-sync/issues/243#issue-635408619 work for you?

**Comment by KienHui** [comment]
@Darkwolf1515 
> 
> Yeah, my synology nas through docker is the only way ill be able to run this, can anyone help me get it up and running?

Steps 1-6 are straight forward. Go to the Log tab in the Docker GUI on the synology to get the link to paste. Step 7, you go to the terminal tab and just paste the secret you got back from Google and enter. It's waiting for you to give secret response back.  But because there's no newline after the prompt, the log isn't ingesting the line with the prompt.

@gilesknap: can we have a newline after the prompt?

**Comment by gilesknap** [comment]
Sure. I have not found much time to work on this project in recent months
but will try to do some of the issues and get a release out soon.

**Comment by gilesknap** [comment]
Added a newline after the prompt. Its in master and will be in the next release.

Sorry for the delay!
