### ISSUE TITLE
is gphotos-sync bidirectional?

### ISSUE THREAD

**Issue by maphew** [gilesknap/gphotos-sync#245]
Is if feasible to use gphotos-sync to get a complete local copy of Google Photos library, delete, rearrange and otherwise munge to suit, and then upload all of those changes back to Google Photos?

_Creating an issue as I don't see a place for discussion and questions. Sorry if this is out of place._

**Comment by maphew** [comment]
urk. not sure how there's two commits here. I used the web editor. Apologies for the noise.

**Comment by gilesknap** [comment]
gphotos sync is deliberately one way only since the Google API is crippled such that it is not symmetrical between upload and download.

If you would like to contribute your documentation change then you should perform a pull request.
