### ISSUE TITLE
Docker Image on Synology NAS - Error 

### ISSUE THREAD

**Issue by nwdcben** [gilesknap/gphotos-sync#247]
**Describe the bug**
Having the common error from docker the following arguments are required "root_folder"  I'm new to docker, so I've literally just installed it on my NAS, installed your image and run it.  Just a note this is entirely a GUI interface for Docker, and I can't see where to add arguments after the executable.

Complete docker novice here, but I can see a lot of synology NAS users doing the same thing if this works well.

**To Reproduce**
Installed Docker, Installed your image from registry, started image (it stops with this error).

Thanks again, possibly adding this to the readme for Synology users with a GUI interface.  I'm sure this is rather simple.

**Comment by nwdcben** [comment]
Disregard.  If you SSH in to the synology you can type out the command exactly as you stated and it works great.

**Comment by johnposten** [comment]
I just ran into this exact same issue.

Do you know what the difference here is with how the GUI runs containers?  I'd rather not have to ssh into my Synology to fix this if at all possible.

**Comment by nwdcben** [comment]
I setup a second container for a second account and I had to ssh in to get
it working.  To be honest it's not hard at all as the exact step by step
instructions on here are all you need.

**Comment by johnposten** [comment]
Oh, I know I've done it before.  I just try to avoid SSHing into my synology as more of a personal choice.  I use other docker hosts (that aren't exposed to the internet) for that.

So some quick tinkering and it appears that it has to do with the `/storage` argument passed on the end of the example run command.  

Modifying the Dockerfile to have `ENTRYPOINT [ "gphotos-sync", "/storage" ]` as the last line seems to fix it in my local environment but I'm not sure of the right way to fix this without studying some more.
