### ISSUE TITLE
Error message when running with pipenv

### ISSUE THREAD

**Issue by cocoonkid** [gilesknap/gphotos-sync#253]
**Describe the bug**

08-05 07:36:20 gphotos.Main WARNING  gphotos-sync 2.14.2 2020-08-05 07:36:20.454277
08-05 07:36:20 gphotos.Utils DEBUG    MINIMUM_DATE = 1800-01-01 00:00:00
08-05 07:36:20 gphotos.Checks INFO     Target filesystem /volumes/extreme/gphotos/cocoonkid is exfat
08-05 07:36:20 gphotos.Checks DEBUG    Checking if is filesystem supports symbolic links...
08-05 07:36:20 gphotos.Checks DEBUG    attempting to symlink /Volumes/Extreme/gphotos/cocoonkid/test_src_135670731 to /Volumes/Extreme/gphotos/cocoonkid/test_dst_646684938
08-05 07:36:20 gphotos.Checks DEBUG    Checking if File system supports unicode filenames...
08-05 07:36:20 gphotos.Checks INFO     Filesystem supports Unicode filenames
08-05 07:36:20 gphotos.Checks DEBUG    Checking if File system is case insensitive...
08-05 07:36:20 gphotos.Checks INFO     Case insensitive file system found
08-05 07:36:20 gphotos.Checks INFO     Max Path Length: 1024
08-05 07:36:20 gphotos.Checks INFO     Max filename length: 255
08-05 07:36:20 gphotos.Main INFO     version: 2.14.2, database schema version 5.7
08-05 07:36:20 gphotos.Main ERROR
Process failed.
Traceback (most recent call last):
  File "/Users/cocoonkid/.local/share/virtualenvs/gphotosync-ZYrU_1QA/lib/python3.8/site-packages/gphotos/Main.py", line 417, in main
    self.setup(args, db_path)
  File "/Users/cocoonkid/.local/share/virtualenvs/gphotosync-ZYrU_1QA/lib/python3.8/site-packages/gphotos/Main.py", line 281, in setup
    self.auth = Authorize(
  File "/Users/cocoonkid/.local/share/virtualenvs/gphotosync-ZYrU_1QA/lib/python3.8/site-packages/gphotos/authorize.py", line 46, in __init__
    secrets = all_json["installed"]
KeyError: 'installed'
08-05 07:36:20 gphotos.Main WARNING  Done.
08-05 07:36:20 gphotos.Main INFO     Elapsed time = 0:00:00.017937

**To Reproduce**
Steps to reproduce the behaviour:

Follow the instructions.

I tried running it on my synolgy NAS where it failed with the same error.

I'd love to get it working. I finally need to get off google. :)

**Comment by cocoonkid** [comment]
I tried setting `--db-path .` 
but that didn't work either.

**Comment by cocoonkid** [comment]
I created a service worker account initially.

Now I was able to create an Oauth account by selecting "TV and Limited Input".

it's indexing now and looks good :)

**Comment by gilesknap** [comment]
@cocoonkid  https://docs.google.com/document/d/1ck1679H8ifmZ_4eVbDeD_-jezIcZ-j6MlaNaeQiz7y0/edit?usp=sharing says to use "Desktop App" was that option no longer available?

Thanks
