### ISSUE TITLE
Cannot sync to fat32 destination folder

### ISSUE THREAD

**Issue by djdailey** [gilesknap/gphotos-sync#254]
Was trying to sync to a folder so I can put on a USB drive to place in a television.

During the sync, several files arrive intact, but eventually, a warning appears "Operation not permitted".
It appears to be trying to chmod 666 to a file in a fat32 folder

pipenv run gphotos-sync --album "face recognition album" --db-path ~ /mnt/usb_share

Perhaps, have a setting to skip ownership modifications for old filesystems.

Note: It is not exactly a USB drive, it is a Raspberry pi Zero, connected to a television. (like this https://magpi.raspberrypi.org/articles/pi-zero-w-smart-usb-flash-drive ) I have it sharing a folder, which is accessed through the USB port on a television. I am using google to do automatic face recognition and just have pictures of my child, and have it appear in my parents' television. Everything seems to be working except for this step.

**Comment by gilesknap** [comment]
Hi thanks for the report. It should be pretty easy to add this to the filesystem checks. I'll look into it.

**Comment by gilesknap** [comment]
I'm releasing a new version of gphotos-sync and closing stale issues. Please reopen if you still want me to look at this. Thanks.
