### ISSUE TITLE
Error with mkdir

### ISSUE THREAD

**Issue by uberparagon** [gilesknap/gphotos-sync#258]
I'm receiving this error:

```pipenv run gphotos-sync --start-date 2019-12-01 --end-date 2020-01-01 --skip-index --progress --ntfs "/media/drew/Data HDD/Photos"
09-20 22:40:18 WARNING  gphotos-sync 2.14.2 2020-09-20 22:40:18.463341 
09-20 22:40:18 WARNING  Downloading Photos ... 
09-20 22:40:18 WARNING  Downloaded 0 Items, Failed 0, Already Downloaded 50563 
09-20 22:40:18 ERROR    
Process failed. 
Traceback (most recent call last):
  File "/home/drew/.local/share/virtualenvs/gphotos-sync-dFOK5dCx/lib/python3.8/site-packages/gphotos/Main.py", line 418, in main
    self.start(args)
  File "/home/drew/.local/share/virtualenvs/gphotos-sync-dFOK5dCx/lib/python3.8/site-packages/gphotos/Main.py", line 369, in start
    self.do_sync(args)
  File "/home/drew/.local/share/virtualenvs/gphotos-sync-dFOK5dCx/lib/python3.8/site-packages/gphotos/Main.py", line 337, in do_sync
    files_downloaded = self.google_photos_down.download_photo_media()
  File "/home/drew/.local/share/virtualenvs/gphotos-sync-dFOK5dCx/lib/python3.8/site-packages/gphotos/GooglePhotosDownload.py", line 148, in download_photo_media
    local_folder.mkdir(parents=True)
  File "/usr/lib/python3.8/pathlib.py", line 1279, in mkdir
    self._accessor.mkdir(self, mode)
OSError: [Errno 22] Invalid argument: '/media/drew/Data HDD/Photos/photos\\2019\\12'
09-20 22:40:18 WARNING  Done. 
```

It looks like maybe there is something wrong with the forward slash/backslashes?

I started running gphotos-sync on Windows, and then later on Linux (Pop_OS), writing to the same library. Could that be the problem? Any fix, or do I just have to start over?

**Comment by gilesknap** [comment]
Hi, yes your switch of OS will be the problem. I should probably not store paths as strings in the DB. But this is a corner case and easily resolved.

If you run with --flush-index it will clear the DB and rescan all of your photos. The already downloaded photos will remain.

Cheers

**Comment by gilesknap** [comment]
@uberparagon  Let me know if the above fixed your problem. Thanks.

**Comment by uberparagon** [comment]
Yes, that did the trick.
I did have to use the "case insensitive file system" option to prevent it from redownloading everything. I still don't quite understand what's going on with that, but I think everything is working now!

**Comment by gilesknap** [comment]
Oh yeah. That does make sense since on window the FS is case insensitive so the files will all be in lower case on your synced copy.

That's a little annoying but your workaround shuttle be fine.
