### ISSUE TITLE
new error

### ISSUE THREAD

**Issue by gosugimoto** [gilesknap/gphotos-sync#261]
All was going well, and nothing changed - as far as I'm aware, but now am faced with this error..

```
(.venv) gomachan@Gos-Mac-Pro gphotos-sync % gphotos-sync /Volumes/Stuff/Go/Photography/mobile/go --skip-shared-albums --archived --skip-albums
zsh: /Volumes/Stuff/_temp/gphotos-sync/.venv/bin/gphotos-sync: bad interpreter: /Volumes/Stuff/_temp/gphotos-sync/.venv/bin/python: no such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/gphotos-sync", line 11, in <module>
    load_entry_point('gphotos-sync==2.14.2', 'console_scripts', 'gphotos-sync')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Python/2.7/site-packages/gphotos_sync-2.14.2-py2.7.egg/gphotos/Main.py", line 45
    self.data_store: LocalData = None
                   ^
SyntaxError: invalid syntax

```

**Comment by gilesknap** [comment]
Hi,

I can see from the error that you have somehow loaded the python 2.7 interpreter instead of python 3 required by gphotos-sync. 

This may be due to some system change that has modified your default interpreter.

**Comment by gilesknap** [comment]
I recommend using Pipenv to set up the virtual environment which determines which Python version you get. I can't remember if you are using that? But if so have you preloaded the environment with "pipenv shell"?

Send me details of how you are launching gphotos-sync if you need help diagnosing.

**Comment by gosugimoto** [comment]
Hi,
These are my commands that have been working perfectly before that I run as a script.

```
#!/bin/bash
cd /Volumes/Stuff/_temp/gphotos-sync
source .venv/bin/activate
gphotos-sync /Volumes/Stuff/Go/Photography/mobile/go --skip-shared-albums --archived --skip-albums
```

**Comment by gosugimoto** [comment]
my default looks like it's running python 3.8.5...

any further thoughts?  or is this calling for a reinstall?

**Comment by gosugimoto** [comment]
Now I'm getting this error instead - fooled around with some updates and such..

```
/Users/gomachan/Desktop/gphotos\ sync\ scripts/go_sync ; exit;
gomachan@Gos-Mac-Pro ~ % /Users/gomachan/Desktop/gphotos\ sync\ scripts/go_sync ; exit;
/Users/gomachan/Desktop/gphotos sync scripts/go_sync: /Volumes/Stuff/_temp/gphotos-sync/.venv/bin/gphotos-sync: /Volumes/Stuff/_temp/gphotos-sync/.venv/bin/python: bad interpreter: No such file or directory
```

**Comment by gilesknap** [comment]
Hi. I feel that the only explanation is that your virtual environment in.venv has been overwritten with a python 2.7 one.

Can you delete that folder and recreate the venv as you did before?

**Comment by gosugimoto** [comment]
Do you meant to delete the photos folder where the photos are synced to?
Does that meant to try and resync everything over?

**Comment by gilesknap** [comment]
No. Just the .venv folder.

Only thing is I don't know how you created it, hopefully you recall how you
did? Maybe if you don't I can look through previous GitHub issues since I'm
sure we discussed this in the past.

**Comment by gosugimoto** [comment]
Hmmm, ok will dig around, but not sure at first instance...

**Comment by gosugimoto** [comment]
This is what I've found, which was an instruction from yourself that worked
perfectly.  Not sure though how I remove the venv...

   - cd to the gphotos directory
   - brew cleanup
   - brew update
   - brew upgrade python3
   - python3 -m pip install virtualenv
   - virtualenv .venv -p python3
   - source .venv/bin/activate
   - pip install .
   - python3 ./gphotos-sync --help

**Comment by gosugimoto** [comment]
Right, so all I changed was after I do:
*source .venv/bin/activate*

Instead of this:

*gphotos-sync /Volumes/Stuff/Go/Photography/mobile/go --skip-shared-albums
--archived --skip-albums*

I did:
*python3 gphotos-sync /Volumes/Stuff/Go/Photography/mobile/go
--skip-shared-albums --archived --skip-albums*

and now seems to be working again!
--
iamgo.net

**Comment by gilesknap** [comment]
Closing as fixed.
