### ISSUE TITLE
put the same date as the gphoto photos in the downloaded ones

### ISSUE THREAD

**Issue by ghost** [gilesknap/gphotos-sync#266]
I do not understand if it was not implemented or I have not configured something well ...

**Comment by gilesknap** [comment]
Hi, gphotos-sync is supposed to set the file date to the same as the photo's exif date. Which filesystem are you using?

**Comment by 0xFEDERICO** [comment]
Hi @gilesknap, thanks for the reply.
I'm using the ext4 filesystem on debian.
I think the problem is not related about your software because if I download a photo from gphoto or i request my gphoto's data, I can't see the EXIF date with exiftool or jhead... The date is always wrong.
Do you know how I can solve this problem?
Thanks in advance.

**Comment by gilesknap** [comment]
I have not heard of google photos breaking the EXIF date even though they do mess with it and remove GPS.

Are you sure your camera is creating the correct date in the first place? How are you uploading your photos to Google?

**Comment by 0xFEDERICO** [comment]
_Assuming that I upload/download the photos from google photo by browser and when I say "get my google data" I mean takeout.google.com_

The photos taken by the camera write the date metadata correctly while all the others have only the modification date "correct".
For example these are the relevant metadata of file **Screenshot_2020-11-09_15-48-21.jpg** done from my pc:
     File Modification Date/Time        : 2020:11:09 06:49:46+01:00
     File Access Date/Time                : 2020:11:09 15:55:12+01:00
     File Inode Change Date/Time     : 2020:11:09 15:54:51+01:00
The correct date should be that of the file name but this is not reflected in the metadata of the file (I read the file's metadata after asking Google for my data of google photo).

I don't know if I have explained myself well but I can see all the dates in the google photo gallery well (they are in chronological order) while as soon as I get my data of google photo nothing remains of the correct date.

**Comment by gilesknap** [comment]
sorry for the delay, I've just got around to reviewing issues for this project. I don't think I understand your issue.

please can you give an example of a photo, showing the date in Google Photos and the date on the file system like this:
![image](https://user-images.githubusercontent.com/964827/103697499-ea084a80-4f97-11eb-8069-a1e7e32b33e1.png)

![image](https://user-images.githubusercontent.com/964827/103699193-7b78bc00-4f9a-11eb-976a-73324ba3bdc6.png)

**Comment by gilesknap** [comment]
I'm releasing a new version of gphotos-sync and closing stale issues. Please reopen if you still want me to look at this. Thanks.
