### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by VerusK** [gilesknap/gphotos-sync#267]
Almost all library downloaded, but then I got this error and script don't do anything:
```
ERROR    FAILURE 1 downloading photos/2019/02/IMAGE 2019-02-02 13:20:22.jpg - [Errno 2] No such file or directory: '/Volumes/photo/GPhotos/photos/2019/02/tmpl4ujrurm' -> '/Volumes/photo/GPhotos/photos/2019/02/IMAGE 2019-02-02 13:20:22.jpg'
```

command:
```
pipenv run gphotos-sync --progress --secret secret.json --log-level DEBUG --db-path ~/Projects/gphotos-sync /Volumes/photo/GPhotos
```

**Comment by VerusK** [comment]
Don't know exactly what is wrong with this file, had to delete it from library.

**Comment by gilesknap** [comment]
That looks a little strange. It is almost as if the http fetch did not copy
the file down but reported that it was ok. Then the copy from temp download
file name failed because of this.
