### ISSUE TITLE
Meta Information like GPS

### ISSUE THREAD

**Issue by andreas83** [gilesknap/gphotos-sync#268]
I just noticed that all of my photos from the last 10 Years dont have any gps infos anymore :cry: 
Please add meta information like gps infos as well.

**Comment by gilesknap** [comment]
Sorry - look at known issues in the readme. Google strip it in their API. I believe it is a deliberate lock-in policy.

**Comment by andreas83** [comment]
Thank you anyway, i really hoped google would not be that evil!
