### ISSUE TITLE
"An error occurred when saving your app" while following Google Docs instructions

### ISSUE THREAD

**Issue by lukelbd** [gilesknap/gphotos-sync#269]
I get an error trying to set up the "Oauth consent screen" following your current Google Docs instructions.

In the most recent Google Cloud Platform version, you are required to add two email addresses: a contact email and "developer" emails.

<img width="550" alt="Screen Shot 2020-11-25 at 1 50 12 AM" src="https://user-images.githubusercontent.com/19657652/100204011-90086580-2ec0-11eb-8b11-bfb732e81d1d.png">

<img width="547" alt="Screen Shot 2020-11-25 at 1 55 40 AM" src="https://user-images.githubusercontent.com/19657652/100204637-5421d000-2ec1-11eb-9d32-7212e251afea.png">

When I try to do this following your Google Docs instructions, I get the error message "An error occurred while saving your app" and my screen looks like this:

![Kg2nK](https://user-images.githubusercontent.com/19657652/100204136-bc23e680-2ec0-11eb-8a5d-6c474c866b14.png)

After some googling, [this stackoverflow answer](https://stackoverflow.com/a/64040236/4970632) solved the problem for me! I just set the "Firebase" email associated with the project to my email address.

If this problem was not just isolated to me, I recommend adding this Firebase step to your Google Docs instructions.

**Comment by gilesknap** [comment]
Thanks for this - it seems I have to keep updating the instructions every few months!

**Comment by gilesknap** [comment]
This will be fixed in releaese 3.0 which will have new docs on how to create the id

**Comment by gilesknap** [comment]
@YashMaan06 are you following the instructions here https://gilesknap.github.io/gphotos-sync/main/tutorials/oauth2.html

**Comment by YashMaan06** [comment]
Hello @gilesknap :) yes following Similar steps 

Creating project
Enabling API
OAuth consent screen (error)

Only change is the API I am using for my project is Google assistant and in OAuth screen I am entering the project name got from firebase.

**Comment by YashMaan06** [comment]
Hey, it suddenly worked I just logged into cloud then on consent screen my project name was waiting to be edited i entered the email and boom it saved without error.....literally I wasted 2 hrs yesterday night. Maybe a bug or something .... Thanks anyways!

**Comment by gilesknap** [comment]
transient Google service error ? :-)

**Comment by YashMaan06** [comment]
Yes it seems :) maybe firebase is enough to solve the main issue and maybe we should wait few hours to let it do its job.
