### ISSUE TITLE
Upgrade to support official Google Photos API

### ISSUE THREAD

**Issue by felciano** [gilesknap/gphotos-sync#27]
Looks like a great tool, and appears to already address https://github.com/yannrouillard/gphotos-sync/issues/9

Your points about this using a deprecated Picasa API are well taken. Do you have any plans for moving to the now-official Google Photos API (https://developers.google.com/photos/)?

**Comment by gilesknap** [comment]
Yes, I have started to experiment with the new API, I have some code to build a client interface to the new rest API with a simple test. I have not progressed it much but might do so if there is some interest.

See https://github.com/gilesknap/gphotos-sync

**Comment by gilesknap** [comment]
sorry, i meant gphoto-sync2 https://github.com/gilesknap/gphotos-sync2

**Comment by felciano** [comment]
Very cool @gilesknap -- I'm happy to help test once you think you have a fairly stable release candidate. What's the best way to be notified of this?

**Comment by gilesknap** [comment]
A little sooner than promised, version 2.0 has been released and uses the new API. @felciano please give it a try. Thanks for encouraging me to get this done.
