### ISSUE TITLE
0 byte files

### ISSUE THREAD

**Issue by qwertycody** [gilesknap/gphotos-sync#270]
**Describe the bug**
- Have a significant amount of files in the hundreds that are just 0 bytes.

**To Reproduce**
- Not Sure yet.

**Comment by qwertycody** [comment]
Nevermind - I forgot I ran this in docker and have all the container logs. 

Here is an output of "cat output.log | grep -i error" if you have any thoughts @gilesknap 

`12-02 19:50:18 ERROR    bad link to /storage/photos/2017/08/img_20170831_192151254_hdr.jpg 
12-02 19:50:18 ERROR    bad link to /storage/photos/2017/08/img_20170831_192158415_hdr.jpg 
12-02 19:50:18 ERROR    bad link to /storage/photos/2017/08/img_20170831_192204156_hdr.jpg 
12-02 19:50:18 ERROR    bad link to /storage/photos/2017/08/img_20170831_192206855_hdr.jpg 
12-02 19:50:18 ERROR    bad link to /storage/photos/2017/08/img_20170831_192216361_hdr.jpg 
12-02 19:50:18 ERROR    bad link to /storage/photos/2017/08/img_20170831_192302205_burst000_cover.jpg 
12-02 19:50:18 ERROR    bad link to /storage/photos/2017/08/img_20170831_192302205_burst000_cover-animation.gif 
12-02 19:50:18 ERROR    bad link to /storage/photos/2017/08/img_20170831_192309175.jpg 
12-02 19:50:18 ERROR    bad link to /storage/photos/2017/08/img_20170831_192316504.jpg 
12-02 19:50:18 ERROR    bad link to /storage/photos/2017/08/img_20170831_192318511.jpg 
12-02 19:50:18 ERROR    bad link to /storage/photos/2017/08/img_20170831_193044059.jpg 
12-02 19:50:18 ERROR    bad link to /storage/photos/2017/08/img_20170831_193047095.jpg 
12-02 19:50:18 ERROR    bad link to /storage/photos/2017/08/img_20170831_193057168.jpg 
12-02 19:50:18 ERROR    bad link to /storage/photos/2017/08/img_20170831_195524622.jpg 
12-02 19:50:18 ERROR    bad link to /storage/photos/2017/08/img_20170831_195552564.jpg 
12-02 19:50:18 ERROR    bad link to /storage/photos/2017/08/img_20170831_195555056.jpg 
12-02 19:50:18 ERROR    bad link to /storage/photos/2017/08/img_20170831_195559867.jpg 
12-02 19:50:18 ERROR    bad link to /storage/photos/2017/08/img_20170831_195604541.jpg 
12-02 19:50:18 ERROR    bad link to /storage/photos/2017/09/img_20170831_200705293.jpg 
12-02 19:50:18 ERROR    bad link to /storage/photos/2017/09/img_20170831_200706489.jpg 
12-02 19:50:18 ERROR    bad link to /storage/photos/2017/09/img_20170831_204543781_burst036-animation.gif 
12-02 21:32:20 ERROR    bad link to /storage/photos/2017/08/img_20170831_192151254_hdr.jpg 
12-02 21:32:20 ERROR    bad link to /storage/photos/2017/08/img_20170831_192158415_hdr.jpg 
12-02 21:32:20 ERROR    bad link to /storage/photos/2017/08/img_20170831_192204156_hdr.jpg 
12-02 21:32:20 ERROR    bad link to /storage/photos/2017/08/img_20170831_192206855_hdr.jpg 
12-02 21:32:20 ERROR    bad link to /storage/photos/2017/08/img_20170831_192216361_hdr.jpg 
12-02 21:32:20 ERROR    bad link to /storage/photos/2017/08/img_20170831_192302205_burst000_cover.jpg 
12-02 21:32:20 ERROR    bad link to /storage/photos/2017/08/img_20170831_192302205_burst000_cover-animation.gif 
12-02 21:32:20 ERROR    bad link to /storage/photos/2017/08/img_20170831_192309175.jpg 
12-02 21:32:20 ERROR    bad link to /storage/photos/2017/08/img_20170831_192316504.jpg 
12-02 21:32:20 ERROR    bad link to /storage/photos/2017/08/img_20170831_192318511.jpg 
12-02 21:32:20 ERROR    bad link to /storage/photos/2017/08/img_20170831_193044059.jpg 
12-02 21:32:20 ERROR    bad link to /storage/photos/2017/08/img_20170831_193047095.jpg 
12-02 21:32:20 ERROR    bad link to /storage/photos/2017/08/img_20170831_193057168.jpg 
12-02 21:32:20 ERROR    bad link to /storage/photos/2017/08/img_20170831_195524622.jpg 
12-02 21:32:20 ERROR    bad link to /storage/photos/2017/08/img_20170831_195552564.jpg 
12-02 21:32:20 ERROR    bad link to /storage/photos/2017/08/img_20170831_195555056.jpg 
12-02 21:32:20 ERROR    bad link to /storage/photos/2017/08/img_20170831_195559867.jpg 
12-02 21:32:20 ERROR    bad link to /storage/photos/2017/08/img_20170831_195604541.jpg 
12-02 21:32:20 ERROR    bad link to /storage/photos/2017/09/img_20170831_200705293.jpg 
12-02 21:32:20 ERROR    bad link to /storage/photos/2017/09/img_20170831_200706489.jpg 
12-02 21:32:20 ERROR    bad link to /storage/photos/2017/09/img_20170831_204543781_burst036-animation.gif 
`

**Comment by qwertycody** [comment]
In addition - what lead me to uncover the 0 byte files is that I wrote a follow-up script to archive the outputs of gphotos-sync.

Here is a screenshot of the 0 byte files - you'll note that they don't line up with the error grep from above.

![image](https://user-images.githubusercontent.com/4968312/100934712-2807df80-34bd-11eb-93ba-bc443e298f30.png)

**Comment by qwertycody** [comment]
Follow-up data:

Let the archive zip script run for a second and did a count of the amount of errors that appeared that are associated with the 0 bytes issue.

12723 is the current number I am getting - in regards to files that seem to be 0 bytes - the archival hasn't finished yet but this is a significant sample size of issues from the google photos api download.

There doesn't seem to be any commonality between specific years that I've seen so far.

I've got 0 byte files from 2011, 2017, 2019, 2020, etc.

**Comment by qwertycody** [comment]
I see the issue - a bit of RTFM on my part. 

Closing this issue.

![image](https://user-images.githubusercontent.com/4968312/100936025-e9732480-34be-11eb-9fa5-7c1b18c19288.png)

**Comment by gilesknap** [comment]
Hi, the errors are significant if you want the backup to include your album information. They do not represent a loss of the photos themselves. 

On Windows you would need to enable symlink support and this may be the reason for your error. See https://community.perforce.com/s/article/3472
