### ISSUE TITLE
Photo download completes, but album creation times out

### ISSUE THREAD

**Issue by kebbob** [gilesknap/gphotos-sync#274]
Sync quits with the following in the log;
```
\.virtualenvs\gphotos-sync-scs8zf9n\lib\site-packages\gphotos\GooglePhotosDownload.py", line 322, in do_download_complete
    e = future.exception(timeout=timeout)
  File "C:\Python36\Lib\concurrent\futures\_base.py", line 467, in exception
    raise TimeoutError()
concurrent.futures._base.TimeoutError
12-16 20:49:49 gphotos.Main WARNING  Done.
12-16 20:49:49 gphotos.Main INFO     Elapsed time = 0:37:17.660951
```
Photo's are kept up to date, but my album folder remains empty. Happened with the latest 'release' version, and also continues now I've moved over to a git clone.
I've also set PIPENV_TIMEOUT to 480, and that hasn't made any difference.

My last tried options were;
`pipenv run gphotos-sync "O:\4 PHOTOS\GPhotos" --flush-index --retry-download --album-date-by-first-photo --db-path "O:\4 PHOTOS\GPhotos" --do-delete --case-insensitive-fs --max-retries 70 --ntfs`

Any tips on how to trouble shoot, or how to provide further info?

**Comment by gilesknap** [comment]
Hi sorry for slow response. This is not related to pipenv timeout which would only affect the installation phase.

This is a timeout on the network download. If your connection is really slow then this would make sense. One thing you could try is to reduce the number of threads and hence the load on your network, try changing --max-threads.

Failing that it looks like I have the timeouts hardcoded here:
https://github.com/gilesknap/gphotos-sync/blob/master/gphotos/GooglePhotosDownload.py#L71-L72

Try editing those on your local copy and if it works I could provide a command line option to extend these timeouts

**Comment by gilesknap** [comment]
Maybe it is failing at the end on a large video file - that might be why you started seeing it. Other threads would download the rest of the new files and then the one doing the large file would timeout after 2000secs. If this is the cause then reducing threads won't help so you will need option 2 above.

**Comment by gilesknap** [comment]
I'm changing this to enhancement - to provide parameter for download timeouts.

**Comment by kebbob** [comment]
Sorry for the delayed reply. I tried several times with different numbers (didn't really know what range to be looking at).
But the same thing keeps happening. Is there any further debugging I can do to father more useful information?

**Comment by gilesknap** [comment]
if you specify --log-level INFO or maybe DEBUG you will be able to see which file is starting download and not completing. I suggest  setting the video timeout to maybe 100000 seconds.

**Comment by kebbob** [comment]
After running multiple times a day over the last couple of weeks, and trawling through the logs each time with nothing standing out, I finally picked out the video file causing the issue. It was a video with zero length. Deleted it from Google Photos and now things are running perfectly once again.

Odd thing is the file was from 2019, so no idea why it suddenly started causing an issue.

**Comment by gilesknap** [comment]
Thanks for the info. If zero length causes indefinite download I might be able to check that before attempting download.

**Comment by gilesknap** [comment]
I'm releasing a new version of gphotos-sync and closing stale issues. Please reopen if you still want me to look at this. Thanks.
