### ISSUE TITLE
Broad try/except swallows exceptions while returning success

### ISSUE THREAD

**Issue by mensi** [gilesknap/gphotos-sync#276]
`main()` has a very broad try-except and while it does log [an error](https://github.com/gilesknap/gphotos-sync/blob/master/gphotos/Main.py#L433), there is no difference in return code.

This makes it very hard to do error handling in automation. I myself for example have a nightly systemd trigger syncing some albums - and somehow managed to lose the OAuth token (not gphotos-sync's fault). The failing syncs went unnoticed for a long time since gphotos-sync still exited successfully and thus did not trigger any failure notifications.

I'd propose making sure that gphotos-sync exits with a non-zero return code in addition to the error-level logging so failures can be caught / notified.

**Comment by gilesknap** [comment]
Yes, this should be fixed, I'll put it in the next release.

**Comment by gilesknap** [comment]
This is fixed in master. Will be in next release.
