### ISSUE TITLE
OAuth Scope Issues

### ISSUE THREAD

**Issue by amurikurthy** [gilesknap/gphotos-sync#284]
Trying to setup gphotos-sync in docker and I downloaded the client_secret.json from google cloud platform. I followed the google doc and found that scopes setup is missing from it. I tried adding all scopes, no scopes, some scopes that don't require verification, nothing works. Let me know if I'm doing something wrong.

Authorization Error
Error 400: invalid_request
Missing required parameter: scope

**Comment by gilesknap** [comment]
perhaps Google have changed the steps in secret key generation again - I'll need to review and see if I can work out what has changed.

**Comment by gilesknap** [comment]
Try v3.0 when released (soon) it should fix auth flow issues.

**Comment by gilesknap** [comment]
I'm releasing a new version of gphotos-sync and closing stale issues. Please reopen if you still want me to look at this. Thanks.
