### ISSUE TITLE
Albums with same names?!

### ISSUE THREAD

**Issue by lutzky** [gilesknap/gphotos-sync#288]
After locally working around #285, I ran into a whole bunch of `bad link to...` errors. After modifying the code to output the error, I see some (but not most) files are linked twice in some albums: 

```
01-23 23:37:43 gphotos.GoogleAlbumsSync DEBUG    adding album link ../../../photos/2013/05/20130529_232833.jpg -> /media/lutzky-takeout/photos/backup/albums/2013/0601 London 2013/0033_20130529_232833.jpg
01-23 23:37:48 gphotos.GoogleAlbumsSync DEBUG    adding album link ../../../photos/2013/05/20130529_232833.jpg -> /media/lutzky-takeout/photos/backup/albums/2013/0601 London 2013/0033_20130529_232833.jpg
01-23 23:37:48 gphotos.GoogleAlbumsSync ERROR    bad link to /media/lutzky-takeout/photos/backup/photos/2013/05/20130529_232833.jpg
[Errno 17] File exists: '../../../photos/2013/05/20130529_232833.jpg' -> '/media/lutzky-takeout/photos/backup/albums/2013/0601 London 2013/0033_20130529_232833.jpg'
```

When searching for this file in the Google Photos web UI, it helpfully indicated that it's in two albums... both of which, horrifyingly, have the same name. A quick sample appears to show that this is the case for all of the files for which I received the `bad link to...` error.

I'm going to clean up my person Google Photos account, but... perhaps this could be handled better. In all cases I saw, the filename was identical (it would have to be, wouldn't it?), so the code could just silently ignore it.

**Comment by gilesknap** [comment]
Isn't this only an issue for albums of the same name containing files of the same name? If so it's relatively benign to not duplicate this in the download.

**Comment by lutzky** [comment]
Yep, needs to be album of same name with file of same name. I think the *download* doesn't duplicate it, but the linking does. Perhaps just test the link to see if it already points at the desired destination file, and if so - do nothing?

**Comment by gilesknap** [comment]
Yes I think that would be fine.

**Comment by lutzky** [comment]
Since #309, I have more details. The errors are all of this form:

> 04-17 01:00:41 ERROR    bad link to /media/lutzky-takeout/photos/backup/photos/2021/04/PXL_20210404_121813364.jpg: [Errno 17] File exists: '../../../photos/2021/04/PXL_20210404_121813364.jpg' ->
'/media/lutzky-takeout/photos/backup/albums/2021/0404 Family & friends/0000_PXL_20210404_121813364.jpg'

This "0404 Family & friends" album is an auto-created one; one of those "Live Albums". I've deleted it, it does not show up neither on the website nor on the app, but apparently gphotos-sync is still trying to sync it (and two copies of it, for good measure). Any ideas?

**Comment by gilesknap** [comment]
you could try --do-delete which removes from the DB things that no longer exist on Google

**Comment by lutzky** [comment]
Yep, with `--do-delete` that did indeed work! (The new output from #310 no longer shows up)

**Comment by lutzky** [comment]
Combining deleting the duplicate album, using `--do-delete`, and #309 + #310, this is no longer an issue. Thank you!
