### ISSUE TITLE
Unable to run the app in docker on synology

### ISSUE THREAD

**Issue by brianrook** [gilesknap/gphotos-sync#291]
I had this up and running a few weeks ago.  I had to uninstall docker this week and I'm setting up again, but it doesn't appear to work the same.

I've documented my steps here:
https://bullyrooks.com/index.php/2021/02/02/backing-up-google-photos-to-your-synology-nas/

I was able to get a client secrets.json and put it in the mapped config directory.  However when I start docker using this command:

sudo docker run \
   -ti \
   --name gphotos-sync \
   -v /volume1/brian/b2-backup/google-photos:/storage \
   -v /volume1/docker/gphotosync:/config \
   gilesknap/gphotos-sync \
  /storage

I get this output:
02-02 03:35:01 WARNING  gphotos-sync 2.14.2 2021-02-02 03:35:01.545800
02-02 03:35:01 ERROR
Process failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gphotos/Main.py", line 417, in main
    self.setup(args, db_path)
  File "/usr/local/lib/python3.7/site-packages/gphotos/Main.py", line 282, in setup
    scope, credentials_file, secret_file, int(args.max_retries)
  File "/usr/local/lib/python3.7/site-packages/gphotos/authorize.py", line 46, in __init__
    secrets = all_json["installed"]
KeyError: 'installed'
02-02 03:35:01 WARNING  Done.

The new google oauth creds is different than what you have, but they were different a few weeks ago and I managed to squeak through it and get it working.  Previously, I would be given a link to authenticate in a browser with, but this makes me think that the secrets file is different or missing something (and changed in the last couple of weeks?)

FWIW, my secrets file now looks like this:
{"web":{"client_id":"876...jdc.apps.googleusercontent.com","project_id":"photosync-3xxxx2","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"V...T"}}

**Comment by gilesknap** [comment]
Hi @brianrook it looks like you do have the wrong 'kind' of secrets file. One of the application options used to be 'web' and it looks like you have that. This is an area that keeps changing in the Google web interface to secret creation the type we want used to be called 'other' and more recently 'Desktop App'. In your documented steps - the page 'Create OAuth Client' shows application type as 'Web Application' which is consistent with your secret - what other options were there for that dropdown?

**Comment by brianrook** [comment]
Great.  I knew I screwed it up somehow and did it different than before.  

That worked like a charm.

I've updated my docs here
https://bullyrooks.com/index.php/backing-up-google-photos-to-your-synology-nas/

Let me know if I can help (like giving a PDF of the docs?) to get other people going.

**Comment by gilesknap** [comment]
Thanks for the offer. Your document is now the most up to date log of how to create the client secret.

If you don't mind I may reference it from the README? I'd also use your site as instructions for Synology users.

**Comment by gilesknap** [comment]
Or if you fancy adding a PDF to this repo and linking it from the README then feel free to make a PR.

**Comment by brianrook** [comment]
I'd love the traffic.

**Comment by brianrook** [comment]
I'd just add that this documentation should be useful for any docker install.  It just happens to be directed at synology users.

**Comment by gilesknap** [comment]
you are linked twice in the readme. You may see some moderate traffic: https://github.com/gilesknap/gphotos-sync/graphs/traffic
