### ISSUE TITLE
ERROR bad link to ....

### ISSUE THREAD

**Issue by renoir789** [gilesknap/gphotos-sync#292]
**Describe the bug**
Some files are reporting bad links to certain files, however those files are healthy and acessible in the folder structure. I take it the video files failing is still a known issue and cannot be fixed?

**To Reproduce**
gphotos-sync /storage

02-04 09:48:32 WARNING gphotos-sync 2.14.0 2021-02-04 09:48:32.071516

02-04 09:50:30 ERROR FAILURE 223 downloading photos/2008/01/P7100030.MOV
02-04 09:50:31 ERROR FAILURE 224 downloading photos/2008/01/P7100029.MOV
02-04 09:50:31 ERROR FAILURE 225 downloading photos/2008/01/P7100028.MOV
02-04 09:50:31 ERROR FAILURE 226 downloading photos/2008/01/EM-0084-16.mov
02-04 09:50:31 WARNING Downloaded 15 Items, Failed 226, Already Downloaded 70093
02-04 09:50:31 WARNING Creating album folder links to media ...
02-04 09:50:45 ERROR bad link to /storage/photos/2021/01/IMG_20210104_104239.jpg
02-04 09:50:45 ERROR bad link to /storage/photos/2021/01/IMG_20210103_101532.jpg
02-04 09:50:45 ERROR bad link to /storage/photos/2021/01/IMG_20210103_101528.jpg
02-04 09:50:45 ERROR bad link to /storage/photos/2020/12/IMG_20201226_103103.jpg
02-04 09:50:45 ERROR bad link to /storage/photos/2020/12/IMG_20201223_190750.jpg
02-04 09:50:45 ERROR bad link to /storage/photos/2020/12/IMG_20201223_190738.jpg
02-04 09:50:45 ERROR bad link to /storage/photos/2020/12/VID_20201216_095320.mp4
02-04 09:50:45 ERROR bad link to /storage/photos/2020/12/IMG_20201215_114924.jpg
02-04 09:50:45 ERROR bad link to /storage/photos/2020/12/VID_20201206_102853.mp4
02-04 09:50:45 ERROR bad link to /storage/photos/2020/12/VID_20201206_102853~2.mp4
02-04 09:50:45 ERROR bad link to /storage/photos/2020/11/IMG_20201107_115515.jpg

**Comment by gilesknap** [comment]
The mov files are probably broken. You can try searching in the Web UI for the filename and downloading manually - it will likely fail.

I don't understand what is happening with the other files. If you type:
```
 ls /storage/photos/2021/01/IMG_20210104_104239.jpg
```
do you see the file?

**Comment by renoir789** [comment]
> The mov files are probably broken. You can try searching in the Web UI for the filename and downloading manually - it will likely fail.
> 
> I don't understand what is happening with the other files. If you type:
> 
> ```
>  ls /storage/photos/2021/01/IMG_20210104_104239.jpg
> ```
> 
> do you see the file?

Yes! File is there, intact, and viewable. What more logs can I provide.

Regarding the .MOV files, yes they are not downloadable. However there are some mp4's that are failing above that which aren't working either.

**Comment by gilesknap** [comment]
The mp4 issue is with the Google API see #119. The links to jpgs failing is still a mystery. Does it happen if you run sync again ( and those files are already there)

**Comment by tom-james-watson** [comment]
I'm also seeing the same - things like this in logs:

```
04-13 02:00:32 ERROR    bad link to /<path>/DSC_1174.JPG 
```

but the file is intact and viewable at that path.

**Comment by gilesknap** [comment]
I'm releasing a new version of gphotos-sync and closing stale issues. Please reopen if you still want me to look at this. Thanks.
