### ISSUE TITLE
Provide a requirements.txt file

### ISSUE THREAD

**Issue by ikwyl6** [gilesknap/gphotos-sync#293]
Hi - I've cloned the repo and created a virtualenv but when I try to run say ```./gphotos-sync -h``` just to make sure the program runs correctly, I continuously get a list of 'package not installed' (ie: appdirs, requests, psutil, and so on...)

I know there are the instructions of how to Install and configure https://github.com/gilesknap/gphotos-sync#install-and-configure but there is not options for someone who wants to clone and to also use ```virtualenv``` (unless I'm blanatly missing something), and without ```pipeenv``` and don't want to install from pypi.. If there was a requirements file created and provided then I guess this could be used with -r for pip instead of installing all the individual pkgs that are needed.

**Comment by gilesknap** [comment]
I think you would be ok with

pip install -e .

after enabling your venv.

The -e is so that you can make changes to the source that are seen by the
venv.

**Comment by gilesknap** [comment]
closing, please reopen if you have further questions
