### ISSUE TITLE
Duplicate albums

### ISSUE THREAD

**Issue by lutzky** [gilesknap/gphotos-sync#294]
I've been getting some error of this form:

```
gphotos.GoogleAlbumsSync ERROR    bad link to [snip]/photos/2008/05/20080513_002331.jpg
```

Apparently, the relevant album is being linked twice:

```
$ grep -B1 20080513_002331.jpg gphotos.log.1
02-07 01:00:43 gphotos.GoogleAlbumsSync DEBUG    adding album link ../../../photos/2008/05/19xplulua628y.jpg -> /media/lutzky-takeout/photos/backup/albums/2021/0121 Family & friends/2270_19xplulua628y.jpg
02-07 01:00:43 gphotos.GoogleAlbumsSync DEBUG    adding album link ../../../photos/2008/05/20080513_002331.jpg -> /media/lutzky-takeout/photos/backup/albums/2021/0121 Family & friends/2271_20080513_002331.jpg
--
02-07 01:00:45 gphotos.GoogleAlbumsSync DEBUG    adding album link ../../../photos/2008/05/17ofym3civgxu.jpg -> /media/lutzky-takeout/photos/backup/albums/2009/0625 Technion/0040_17ofym3civgxu.jpg
02-07 01:00:45 gphotos.GoogleAlbumsSync DEBUG    adding album link ../../../photos/2008/05/20080513_002331.jpg -> /media/lutzky-takeout/photos/backup/albums/2009/0625 Technion/0041_20080513_002331.jpg
--
02-07 01:00:46 gphotos.GoogleAlbumsSync ERROR    bad link to /media/lutzky-takeout/photos/backup/photos/2008/05/19xplulua628y.jpg
02-07 01:00:46 gphotos.GoogleAlbumsSync DEBUG    adding album link ../../../photos/2008/05/20080513_002331.jpg -> /media/lutzky-takeout/photos/backup/albums/2021/0121 Family & friends/2271_20080513_002331.jpg
02-07 01:00:46 gphotos.GoogleAlbumsSync ERROR    bad link to /media/lutzky-takeout/photos/backup/photos/2008/05/20080513_002331.jpg
```

This is occurring for a few specific albums:

```
$ grep -B1 'bad link' gphotos.log.1 | grep adding | sed -e 's/.*albums//' | cut -d'/' -f3 | sort -u
0121 Family & friends
0601 London 2013
0726 England & Norway 2015
[one more with redacted name]
```

Looking at `gphotos.sqlite`:

```
sqlite> select * from (select count(1) as c, AlbumName from Albums group by AlbumName order by c) where c > 1;
2|Copy of Untitled Album
2|England & Norway 2015
2|Family & friends
2|Greece 2009
2|Greece 2010
2|Ireland 2013
2|London 2013
2|[that album with the redacted name]
2|Ohad's late birthday 2019
3|Paris 2015
3|none
```

So it's not the *same* set of albums, but it is a superset.

```
sqlite> select * from Albums where AlbumName = 'London 2013';
ADu20N3zDluIvVye_xmvZ0YyEYRcRhYSv518rDLIuESHz0LHShz1fBM|London 2013|42||2013-05-26 14:51:51|2013-06-01 12:50:07|2021-01-23 23:21:36|1
ADu20N02BUFhwd4TGi-bbloR4udFTHOjJe28kxbHpCVoVCzW4auJJs0|London 2013|57||2013-05-26 14:51:51|2013-06-01 12:50:07|2021-02-07 12:11:10|1
```

How can I safely remove the duplicates, without re-downloading all of my photos? I believe this is coming from an album I had already deleted. (However, neither of the `RemoteId` values seem to match the URL for my album in gphotos).

**Comment by gilesknap** [comment]
I'm not sure that gphotos-sync  can cope with two albums of the same name (but probably ok if they are not dated the same month). However if the duplicate albums did not contain any of the same photos we would probably get away with it. In this instance you would see one album folder with the photos from both of the duplicate albums.

However if you have duplicate photos in the duplicate named albums then we get a clash when creating the links.

This is a bug and I'd have to think of a way of fixing it. However I also think the affects are benign except that you get error messages and a single folder to represent one or more albums with the same name.

**Comment by lutzky** [comment]
Ah, but the two albums of the same name no longer exist. I'm curious if there's a safe but fast way to recreate the DB to reflect that.

**Comment by gilesknap** [comment]
you will need to use --flush-index for that. It wont be very quick since it will re-scan all of your index but it wont download any files that are already downloaded.

**Comment by lutzky** [comment]
Yep, `--flush-index` worked, thanks!
