### ISSUE TITLE
MOV Date Taken

### ISSUE THREAD

**Issue by wills721** [gilesknap/gphotos-sync#295]
https://github.com/gilesknap/gphotos-sync/issues/122

The MOV files I download from Google all appear to have an empty date taken.  I found above -- which says something was added to gphotos-sync to somehow account for this? However --help does not show anything obvious I can see.

Thanks for any help,
Will

**Comment by gilesknap** [comment]
Hi, I get the date from Google's own metadata, I suspect that they will use the file's timestamp if there is no metadata inside the file

**Comment by wills721** [comment]
Amazon doesn't.  They appear to use Date Taken. When its empty -- it falls into a black hole.

**Comment by wills721** [comment]
It would be the media create date from what I can tell

ExifTool Version Number         : 11.88
File Name                       : IMG_4163.MOV
Directory                       : .
File Size                       : 23 MB
File Modification Date/Time     : 2021:02:19 17:31:57-05:00
File Access Date/Time           : 2021:02:23 05:53:59-05:00
File Inode Change Date/Time     : 2021:02:19 13:35:29-05:00
File Permissions                : rw-r--r--
File Type                       : MP4
File Type Extension             : mp4
MIME Type                       : video/mp4
Major Brand                     : MP4 v2 [ISO 14496-14]
Minor Version                   : 0.0.0
Compatible Brands               : isom, mp42
Movie Header Version            : 0
Create Date                     : 0000:00:00 00:00:00
Modify Date                     : 0000:00:00 00:00:00
Time Scale                      : 30000
Duration                        : 0:00:38
Preferred Rate                  : 1
Preferred Volume                : 100.00%
Preview Time                    : 0 s
Preview Duration                : 0 s
Poster Time                     : 0 s
Selection Time                  : 0 s
Selection Duration              : 0 s
Current Time                    : 0 s
Next Track ID                   : 3
Track Header Version            : 0
Track Create Date               : 0000:00:00 00:00:00
Track Modify Date               : 0000:00:00 00:00:00
Track ID                        : 1
Track Duration                  : 0:00:38
Track Layer                     : 0
Track Volume                    : 0.00%
Image Width                     : 1920
Image Height                    : 1080
Compressor ID                   : avc1
Source Image Width              : 1920
Source Image Height             : 1080
X Resolution                    : 72
Y Resolution                    : 72
Bit Depth                       : 24
Video Frame Rate                : 29.97
Graphics Mode                   : srcCopy
Op Color                        : 0 0 0
Matrix Structure                : 1 0 0 0 1 0 0 0 1
Media Header Version            : 0
Media Create Date               : 0000:00:00 00:00:00
Media Modify Date               : 0000:00:00 00:00:00
Media Time Scale                : 44100
Media Duration                  : 0:00:38
Media Language Code             : und
Handler Type                    : Audio Track
Handler Description             : ISO Media file produced by Google Inc.
Audio Format                    : mp4a
Audio Channels                  : 2
Audio Bits Per Sample           : 16
Audio Sample Rate               : 44100
Balance                         : 0
Media Data Size                 : 24280488
Media Data Offset               : 19580
Image Size                      : 1920x1080
Megapixels                      : 2.1
Avg Bitrate                     : 5.05 Mbps
Rotation                        : 0

**Comment by gilesknap** [comment]
closing, please reopen if you want to discuss further.
