### ISSUE TITLE
Videos no longer have a date in their metadata

### ISSUE THREAD

**Issue by Flavien** [gilesknap/gphotos-sync#298]
**Describe the bug**
Videos downloaded from gphotos-sync don't seem to have any date available in their metadata, even if the original file did.

This is the original file as downloaded from photos.google.com:

    [QuickTime]     Create Date                     : 2021:01:24 10:27:09
    [QuickTime]     Modify Date                     : 0000:00:00 00:00:00

This is the file sync'd by gphotos-sync:

    [QuickTime]     Create Date                     : 0000:00:00 00:00:00
    [QuickTime]     Modify Date                     : 0000:00:00 00:00:00

This doesn't happen with all the video files, but certainly with the videos shot on my Pixel 4.

**Comment by gilesknap** [comment]
Unfortunately Google transcode the videos downloaded through the API. I have no idea why they would remove the date. If you look at #119 you will see there are a couple of bugs open with Google regarding their treatment of videos. I'm afraid they have not moved on these bugs in over a year.
