### ISSUE TITLE
Tons of duplicate photos

### ISSUE THREAD

**Issue by Flavien** [gilesknap/gphotos-sync#299]
**Describe the bug**
When syncing my Google Photos library, I get tons of duplicated (binary-identical) pictures and videos. They are not duplicated in my Google Photos library. Searching for the filename returns a single item.

What I have noticed is that for some of them at least, is that the dates on each of the duplicates is different (and sometimes ending up in two different folders, e.g. `photos/2009/11/CIMG7874.AVI` and `2009/09/CIMG7874.AVI`). One of the dates is the original date on the Exif data (as written by the camera), and the second date is the date as modified on Google Photos (as Exif date was not accurate).

**Comment by Flavien** [comment]
Ok, I'm slowly getting to the bottom of this. This is what the database contains about this file:

![image](https://user-images.githubusercontent.com/296540/108783681-cdcf6580-7565-11eb-8d71-77d97b2da65c.png)

As you can see, the duplicated one with the wrong date comes from a shared album. The one in my library is the one with the corrected date. So it seems shared libraries cause duplicates.

Is there a way to skip syncing albums? I'm only interested in my own library and don't want to sync albums anyway.

**Comment by gilesknap** [comment]
It seems as though Google is delivering different meta data for the items when searching all items vs searching in folders. That is a bit of a pain.
However for your use case you have the following command line options:
--skip-shared-albums
--skip-albums
--albums-regex

try --help for details of the above options.

**Comment by Flavien** [comment]
Thanks, that solves the problem.
