### ISSUE TITLE
Error 500 while downloading some videos

### ISSUE THREAD

**Issue by Flavien** [gilesknap/gphotos-sync#301]
**Describe the bug**

During the download, some of my videos are returning an error 500 and don't get downloaded. What's interesting is that if I request a Takeout archive, these videos are also missing from the archive (the JSON exists, but the corresponding video is missing). Is that a known issue with Google Photos? Any known workaround?

```
02-23 15:49:19 gphotos.BadIds DEBUG    BAD ID ABRd85LLd<redacted> for photos/2006/07/CIMG0410.AVI
Traceback (most recent call last):
  File "/usr/lib64/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ec2-user/.local/share/virtualenvs/gphotos-sync-xvL8wJQh/lib/python3.7/site-packages/gphotos/GooglePhotosDownload.py", line 272, in do_download_file
    response.raise_for_status()
  File "/home/ec2-user/.local/share/virtualenvs/gphotos-sync-xvL8wJQh/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://video-downloads.googleusercontent.com/<redacted>
```

**Comment by Flavien** [comment]
Also, when trying to open the video URL (which normally works) for one of those found in the bad ID file, I get a page saying:

> Can’t access photo
> This photo doesn’t exist or your current account doesn’t have permission to view it.

(I do have permission)

**Comment by gilesknap** [comment]
Hi,
Yes I have seen videos go 'bad' in the library. The ultimate test is to use the web UI to search for the filename and see if you can open it that way. In the past I have found I cannot. The video is not recoverable at that point. Its probably due to some transcoding issue - Google does not like your raw files taking up their disk space I guess.

**Comment by Flavien** [comment]
I can search the filenames of the videos just fine on the website, and they play without any problem. I can even download them from there.

**Comment by gilesknap** [comment]
So I have historically seen this too. Note that 500 means the server crashed trying to service a request so its a google issue. See the first (crossed out) issue in #119.

You may notice that I have kind of given up on Google fixing the remaining problems :-(

**Comment by Flavien** [comment]
I did a bit more digging in the API, and I have found that these problem items are showing as processing:

```
    {
      "id": "xxx",
      "productUrl": "xxx",
      "baseUrl": "xxx",
      "mimeType": "video/mp4",
      "mediaMetadata": {
        "creationTime": "2009-09-12T01:07:09Z",
        "video": {
          "status": "PROCESSING"
        }
      },
      "filename": "CIMG7875.AVI"
    },
```

Which is odd as some of these have been uploaded months, if not years ago. The app and the web UI don't show the video as processing and it's able to play it just fine...

**Comment by gilesknap** [comment]
That is interesting and maybe worth opening another bug with Google. It's
an easy to identify symptom so there is some chance they will fix!

**Comment by Flavien** [comment]
I've opened this bug: https://issuetracker.google.com/issues/181055574.

**Comment by gilesknap** [comment]
Thanks. have upated #119 to include your new info and will close this ticket.
