### ISSUE TITLE
RFE: automatically convert HEIC images to JPG

### ISSUE THREAD

**Issue by Dmitry-Klymenko** [gilesknap/gphotos-sync#302]
For those of us using this to backup all photos AND use the downloaded to view and browse on TV, etc - some players won't support HEIC formats (like Plex) and just skip it. 
I think it would be handy to have a configuration key to convert heic download to jpg deleting or not original heic.

Thank you

**Comment by gilesknap** [comment]
I'm sure we could do this. Hopefully there is a python library for the conversation.

**Comment by DmitryKlymenkoAU** [comment]
For example this one :)
https://pypi.org/project/heic-to-jpg/

Thank you

**Comment by gilesknap** [comment]
I'm releasing a new version of gphotos-sync and closing stale issues. Please reopen if you still want me to look at this. Thanks.

**Comment by Dmitry-Klymenko** [comment]
I still think this would be useful

**Comment by gilesknap** [comment]
@Dmitry-Klymenko OK I'll keep it on the list - reopening.

**Comment by gilesknap** [comment]
I'm going to confess that I will not be getting around to implementing this. So closing as won't fix. 

It's probably not that difficult to do but would be fiddly with respect to making the index recognise the renamed files.
