### ISSUE TITLE
Downloading Photos and Videos in Original Quality

### ISSUE THREAD

**Issue by snowmaker56** [gilesknap/gphotos-sync#303]
Hello,
I just tried this nice piece of software. I installed the docker image und performed a backup.
But the photos and videos are just in "high quality" instead of "original quality".
For example a downloaded photo is about 2MB while the original file in Google Photos is about 11MB.
My usecase for this software would be to create a real backup of my photos and videos on my storage.

**Comment by alerque** [comment]
This is mentioned in #119 along with a bevy of other bugs that boil down to Google Photos API issues. This particular one is [tracked upstream here](https://issuetracker.google.com/issues/112096115).

**Comment by gilesknap** [comment]
@snowmaker56 yes unfortunately @alerque is correct. The Google API is crooked in this respect and cannot give you a true backup.

I've had several bugs open with them for a couple of years now. So have given up on them fixing them. I've come to believe the limitations are deliberate and there to create lock in to Google's service.
