### ISSUE TITLE
Sqlite and Log / Lock files in CONFIG

### ISSUE THREAD

**Issue by synman** [gilesknap/gphotos-sync#304]
Just a thought... I was surprised to find the internal sqlite db, associated lock, trace, bad_ids.yaml, and log files in the storage directory.  Shouldn't they be in config?

It's probably semantics as "storage" is a fairly broad term.  It would be nice if we could keep our actual photos library "clean" with just the photos and albums directories in it.

**Comment by synman** [comment]
Will take a look... thanks for the pointer!  a logs location option would be cool too... I'll be sure to see if you already exposed it as well.

**Comment by synman** [comment]
Just wanted to report back I was able to get the desired behavior with my docker container by using the following arguments:

```
docker run --rm \
     --name gphotos-sync-shelldude \
     -v /volume1/shared/gphotos/shelldude:/storage \
     -v /volume1/docker/gphotosync/shelldude:/config \
     gilesknap/gphotos-sync \
     --db-path /config \
     --logfile /config/gphotos-shelldude.log 
     /storage
```

With this setup my "storage" folder only contains the photos and albums directories and everything else (logs / db / lock) are in my config directory with the expception of gphotos.bad_ids.yaml.  It remains in my /storage directory.  It looks like it is tied to the specified root_folder.

I then tried to unbox the photos and albums directories but it didn't matter what path I tried, it always created them in whatever I specified for the root_folder.

```
docker run --rm \
     --name gphotos-sync-shelldude \
     -v /volume1/shared/gphotos/shelldude:/storage \
     -v /volume1/docker/gphotosync/shelldude:/config \
     gilesknap/gphotos-sync \
     --photos-path ../storage/photos \
     --albums-path ../storage/albums /
     /config
```

**Comment by gilesknap** [comment]
Thanks for the detailed info. 

I will look at the problem with album and photo directories when I have a moment. (But currently am very busy on my first containers project - I'm finally understanding what the fuss is about!)

**Comment by gilesknap** [comment]
I'm releasing a new version of gphotos-sync and closing stale issues. Please reopen if you still want me to look at this. Thanks.
