### ISSUE TITLE
Token expires every 7 days

### ISSUE THREAD

**Issue by Raelx** [gilesknap/gphotos-sync#306]
I just go this setup about a month ago. And it works great, thank you very much for all the hard work @gilesknap

However my OAuth token is expiring every 7 days. Running with --new-token and consenting again will fix it for 7 days but then it will fail again. I think I have found the reason for this but not a solution. It seem that for the type or project account I have this is the intended behavior.

Google mentions the following, here: https://developers.google.com/identity/protocols/oauth2

> A Google Cloud Platform project with an OAuth consent screen configured for an external user type and a publishing status of "Testing" is issued a refresh token expiring in 7 days.

When I look at my project details I am in Testing and External users. I can not change the project to Internal "Because you’re not a Google Workspace user, you can only make your app available to external (general audience) users.". And publishing the project to move it out of testing sounds like something that I might not want to do.

**Comment by synman** [comment]
seeing the same here... like clockwork... every 7 days.

```
03-22 07:00:10 gphotos.Main WARNING  gphotos-sync 2.14.2 2021-03-22 07:00:10.848722
03-22 07:00:11 gphotos.Utils DEBUG    MINIMUM_DATE = 1800-01-01 00:00:00
03-22 07:00:11 gphotos.Checks INFO     Target filesystem /storage is btrfs
03-22 07:00:11 gphotos.Checks DEBUG    Checking if is filesystem supports symbolic links...
03-22 07:00:11 gphotos.Checks DEBUG    attempting to symlink /storage/test_src_570967139 to /storage/test_dst_1937788367
03-22 07:00:11 gphotos.Checks DEBUG    Checking if File system supports unicode filenames...
03-22 07:00:11 gphotos.Checks INFO     Filesystem supports Unicode filenames
03-22 07:00:11 gphotos.Checks DEBUG    Checking if File system is case insensitive...
03-22 07:00:11 gphotos.Checks INFO     Case sensitive file system found
03-22 07:00:11 gphotos.Checks INFO     Max Path Length: 4096
03-22 07:00:11 gphotos.Checks INFO     Max filename length: 255
03-22 07:00:11 gphotos.Main INFO     version: 2.14.2, database schema version 5.7
03-22 07:00:12 gphotos.Main ERROR    
Process failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests_oauthlib/oauth2_session.py", line 478, in request
    url, http_method=method, body=data, headers=headers
  File "/usr/local/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 198, in add_token
    raise TokenExpiredError()
oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired) 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gphotos/Main.py", line 417, in main
    self.setup(args, db_path)
  File "/usr/local/lib/python3.7/site-packages/gphotos/Main.py", line 309, in setup
    self.google_photos_client = RestClient(photos_api_url, self.auth.session)
  File "/usr/local/lib/python3.7/site-packages/gphotos/restclient.py", line 38, in __init__
    service_document = self.auth_session.get(api_url).json()
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests_oauthlib/oauth2_session.py", line 497, in request
    self.auto_refresh_url, auth=auth, **kwargs
  File "/usr/local/lib/python3.7/site-packages/requests_oauthlib/oauth2_session.py", line 446, in refresh_token
    self.token = self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/local/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 421, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/usr/local/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 431, in parse_token_response
    validate_token_parameters(params)
  File "/usr/local/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 438, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/usr/local/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 405, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidGrantError: (invalid_grant) Token has been expired or revoked.
03-22 07:00:12 gphotos.Main WARNING  Done.
03-22 07:00:12 gphotos.Main INFO     Elapsed time = 0:00:01.666550

```

**Comment by gilesknap** [comment]
My token had lasted for a couple of years. So either Google has recently changed something or you have done something a little different when getting your client secret set up. I'm not sure I saw any testing options when writing the documentation for client secret so maybe it is the former. 

Please can you go through client secret creation again and let me know if what you see differs from the Google Doc I wrote, linked from the readme

**Comment by Raelx** [comment]
@gilesknap what type of google account is yours setup under. Personal account or Gsuite?

**Comment by gilesknap** [comment]
It's a personal

**Comment by synman** [comment]
I followed the directions as provided in your gdoc word for word about 3 week ago and have had to renew my token twice now... this is for two separate gphotos libraries tied to two separate google accounts.  

As as google, and my container setup is concerned, it's like two separate entities end to end.... and yet they both expire every 7 days.

**Comment by Raelx** [comment]
It sure looks like this is a change on Google's side to have newly created OAuth tokens expire after 7 days as they state in their developer docs I linked above. Sounds like the only way to get around this are to use a GSuite account or publish the project out of Testing to Production. Not sure what that would take and if you can still limit access to prevent someone else from burning thru our individual API call allotment.
