### ISSUE TITLE
Restrict downloads to certain time period, perticuarly last 'X' days

### ISSUE THREAD

**Issue by djsmiley2k** [gilesknap/gphotos-sync#317]
Due to the fact my wife and I have sharing turned on, and I have her photos saved to my google photos collection, if I ever send her photos, and her phone backs them up, I can end up with duplicates.

This gets worse if she's then shared them in other messaging apps etc, and she's turned on backups for those too (because she's lost images she's wanted to keep in the past, she just backs up everything, fair enough).

I don't expect the app to be able to identify these dupes, I can manage that - but is it possible to get a feature where it'll only download files from the last X number of days? So I run this weekly, if I could limit it to only get photos from the last 30 days uploads, I can then dedupe anything older than that 'offline' happily, knowing they won't be re-fetched?

**Comment by gilesknap** [comment]
Hi @djsmiley2k. 

The option you are looking for is --start-date. Use --help to get details.

Also I am of the opinion that Google will handle the duplicates for you and only list the photo that is in both of your accounts once. This would only work if you send your wife photos via Google Photos Sharing. If you use whatsapp or something else then you are making a (downgraded resolution) copy of the photo and the libraries would then store two versions.

**Comment by gilesknap** [comment]
closing for now but I'll still respond if you post here
