### ISSUE TITLE
Live photos - not syncing .mov files

### ISSUE THREAD

**Issue by brazilian812** [gilesknap/gphotos-sync#318]
I am syncing Live Photos taken on my iPhone to Google Photos as a HEIC and MOV file pair.  When I ran gphoto-sync, only the HEIC files got Indexed and Downloaded.  Is that a known limitation?

I saw in the readme that the API used to have issues with some movie formats but it's been marked as fixed.

Thanks for this utility though, it worked super well otherwise!

**Comment by gilesknap** [comment]
Thanks for reporting. My wife got an iPhone recently and I had not noticed this.

I just took a look at it and in my library the live photos appear as a singe image with a button that animates them. So it is not obvious if their are two files in the library. Is that how yours appear? In the downloads with gphotos-sync I get a single HEIC file only but have yet to test if it still contains the animation.

**Comment by brazilian812** [comment]
It does appear as an image I can "play" in Google Photos.

If I try to save it on my phone it gives me the option to save it as a pic
or a video.  If I do it on a computer, I actually get a zip file with the
HEIC and MOV files

And if I redownload the HEIC file from my NAS (where I ran gphoto-sync) it
is just a picture file, no animation, as far as I can tell

**Comment by gilesknap** [comment]
So it looks like they don't have support for this in the API yet. You could have a go at reporting this to Google see #119 for some examples of API bug reports.

**Comment by gilesknap** [comment]
I'm releasing a new version of gphotos-sync and closing stale issues. Please reopen if you still want me to look at this. Thanks.
