### ISSUE TITLE
All mp4 files failing

### ISSUE THREAD

**Issue by gcaliber** [gilesknap/gphotos-sync#319]
All video files are failing with a similar error.

`07-07 10:55:55 ERROR    FAILURE 104 downloading photos/2019/12/VID_20191228_210621.mp4 - 400 Client Error: Bad Request for url: https://video-downloads.googleusercontent.com/AGQNM9KqF-wX74r8SyxeOrlM5CPXMEWEM36zwscDtXdrH6Z50aJZFLHB16yqvXRyvAPk7RRu3s9H0QIS4QlCSnWp7S6pKZKLgkKzvaWOiwpQ8OMcJDhPws4jgXD0Pm8rHuPAgEdmjZ9EbnSHvBpIY0xcG19vnW6cYQsk-loXZmUb6xe1ZNyZbX9_1CzNIurpJy17V4bNGjDhmQ__kjj6-0eq38TAw0uLUzY6uxNgjcBGFbQMB696q2TK1Wv9AcfsHGdfNKM1tgG0smBVDi2qqlC0dknCWjISdhp0wXashguKFTXB9tpFvBVLuNzpEiLcR9GP642Sq8yl6GSuy8h11JmH_LhRPSXPHYgovsq40r0NLPqT2m_pqk9_ykvmCY70Pfxq9oTgk2qmsHyZUuLiq7MPTrO4GbgigWHTM8rd9k-UqejeIUeWXDg-grWZnIAX8aAhy4OY9780aXthHSnXlItGyucEB4-e4mJo4BWkaWAihHh31fgO-oGpBskZn2s0f6ASXDDujBmCEW8nYVdr8QW3eUAXPY0VvsJti287Z4sVMlpHoHfq5qvCApXgUbbEvbyfX26hxtei9FM1W-texO39PsL9gyYOSuD7mG3-U33SDGo5OywFY6l2BEw20hH-mVxwfWxtqkl3uSA_-lrixfNcqCOnRvrl7ZG97xVfR4CpYWOtx0fJUsMEAFXxPBoril_3YNRnBkS5xxFQtQ9PDzAOUuKuJ0yXbHvajHGs2mzFjojvc4Lxqp-EWISjHEof_OXXla75pIui1PWa7FG4k1uQ6jD54LtvGILxj47oGfXmsRqEe0cJrrU0EUot5sIb184aDS9NFVXjqo6EElIVeb4oNBuDTEowri8ZgYhcrI-NZXHqNjIUhpdBem4LPYA07F2GM7g5ua0g4N2oX778Z6ZYKIElVP9Rp4FHfVwC463kstgmN_Kb2CUnWLa3eiIRydKBHQEMjzy9`

This is the first sync I am trying to do with my wife's account and I am trying to figure out if it was something I did.

**Comment by gilesknap** [comment]
Sorry I did not get back to you on this. My attention has been away from this project for some time. But I'm back.

I'm releasing a new version of gphotos-sync and closing stale issues. Please reopen if you still want me to look at this. Thanks.
