### ISSUE TITLE
v2: Downloaded 0 Photos. Everything Skipped

### ISSUE THREAD

**Issue by stloewen** [gilesknap/gphotos-sync#32]
Using the newest version (b04a7e8430f272e94bc23a82d98aa8503ea2dfc5) gphotos-sync won't download any files.

It creates all the albums with symlinks just fine, but the symlinks point to non-existing files.
Sqlite database (table "SyncFiles") lists all my photos correctly but the logfile lists them all as skipped. E.g.:
```
01-17 10:44:46 gphotos.Photos DEBUG    Skipped 16 photos/2019/01/IMG_20190116_130626.jpg
```

Any idea how I can help debug this?

**Comment by stloewen** [comment]
Previous commit f95c72cedd8f0a74b1501ce248f062ad70cd4aaa works fine. So the problem lies in commit b04a7e8430f272e94bc23a82d98aa8503ea2dfc5

**Comment by gilesknap** [comment]
Hi,
A new feature is that the DB records what it has previously downloaded and won't check again unless you use the new option --retry-download.

Does using this option work? Is this a bad choice of default behaviour?

**Comment by gilesknap** [comment]
Hang on, I just tested a brand new folder and it showed your issue. Must be a bug in the 'already downloaded' logic. Investigating ...

**Comment by gilesknap** [comment]
Fixed in latest commit.

Sorry about that. The project has CI but my system tests are very thin since the API update, better test coverage is my next task.

**Comment by stloewen** [comment]
> Hi,
> A new feature is that the DB records what it has previously downloaded and won't check again unless you use the new option --retry-download.
> 
> Does using this option work? Is this a bad choice of default behaviour?

Sounds reasonable.

The problem was that nothing was downloaded in a brand new folder. This is fixed now. Thank you very much!
