### ISSUE TITLE
DB of all photos without download

### ISSUE THREAD

**Issue by xclaim494** [gilesknap/gphotos-sync#324]
I apologize for this question in advance .. but is there a way to query all google photos (maybe download metadata in a db) without having to download all the images ?

metadata like
filename, size, date crrated, CRC, other exif information

i am finding it difficult to figure out if this is possible ?

I do have other SW that does deltas like Backblaze, RSYNCH etc etc but will be surprised if Google Photos api's dont allow this ?

TY in advance.

**Comment by gilesknap** [comment]
Sure.
```
pipenv run gphotos-sync --index-only
```
This creates the sqlite database only and does no downloads.

try --help for a full list of the options, you can also filter by date range etc.

**Comment by xclaim494** [comment]
> 
> 
> Sure.
> 
> ```
> pipenv run gphotos-sync --index-only
> ```
> 
> This creates the sqlite database only and does no downloads.
> 
> try --help for a full list of the options, you can also filter by date range etc.

awesome TY so much... Very cool tool Bravo
