### ISSUE TITLE
Symbolic links not supported - Again yes Again!

### ISSUE THREAD

**Issue by bamsnow** [gilesknap/gphotos-sync#327]
I am receiving the following symlinks errors:

11-03 13:xx:xx ERROR    Symbolic links not supported
11-03 13:xx:xx ERROR    Albums are not going to be synced - requires symlinks

The setup is running in pipenv on 20.04, saving databases and logs locally, with the /storage a local directory mounted to a Synology NAS. I think I have checked every box to allow symlinks on the Synology, but perhaps I am missing something? Is there some hidden linux setting to allow symlinks on a mounted SMB share?

**Comment by gilesknap** [comment]
can you make a symlink in /storage manually from the command line?

**Comment by bamsnow** [comment]
No, attempting to create a symoblic link from the command line results in error:

ln: failed to create symbolic link 'symlinkedfile.txt': Operation not supported

I am not sure where the permission issue is here.

**Comment by gilesknap** [comment]
Is your client windows or linux? Windows needs policy changes to support this.
Otherwise I don't know - SMB is supposed to support symlinks.

**Comment by gilesknap** [comment]
I'm going to close this as not a gphotos issue as such. Happy to continue to discuss here if you wish.

**Comment by bamsnow** [comment]
The client is Ubuntu 20.04 mounting a shared SMB folder from a Synology NAS.

**Comment by gilesknap** [comment]
I use the same client but nfs for the file server and that works well.

**Comment by bamsnow** [comment]
Wow @gilesknap based upon your comment I switched the mount to NFS instead of SMB and now symlinks work perfectly. Thank you for you help!

**Comment by gilesknap** [comment]
no worries
________________________________
