### ISSUE TITLE
Initiate automated pipenv from crontab? [Linux]

### ISSUE THREAD

**Issue by bamsnow** [gilesknap/gphotos-sync#328]
Does anyone know a working way to initiate gphoto-sync in linux via crontab. I have tried many iterations of something like this:

in /etc/crontab

1,30 * * * * USERNAME cd /home/USERNAME && /usr/local/bin/pipenv run ./gphotos-sync --db-path /home/USERNAME/gphoto_db --logfile /tmp /home/USERNAME/gphoto_local/gphoto 2>&1

...but I cannot get it to work. 

Running the following from the command line works fine:

pipenv run gphotos-sync --db-path ~/gphoto_db --logfile /tmp ~/gphoto_local/gphoto

The idea is to run it every 30 mins.  Any help?

**Comment by gilesknap** [comment]
I'm not sure why your approach does not work. However I have a script that does the cd and then invokes pipenv (annoying feature of pipenv is that it only works off of cwd). Then call that script from crontab.

**Comment by gilesknap** [comment]
I think this is resolved? closing.
