### ISSUE TITLE
Empty album folders 

### ISSUE THREAD

**Issue by wildestden** [gilesknap/gphotos-sync#331]
Hi. 
Did everything according to the instructions of Bullyrook.  downloaded normally, there are photos in folders by year and month, and the album folders are empty.  Tell me what could be the problem?

**Comment by gilesknap** [comment]
Sorry for the very late reply. I'm back to being active on this project now.

I'm releasing a new version of gphotos-sync and closing stale issues. Please reopen if you still want me to look at this. Thanks.
