### ISSUE TITLE
using --index-only but only got index log in photos but not albums 

### ISSUE THREAD

**Issue by beckietech** [gilesknap/gphotos-sync#334]
**Describe the bug**
I send some command like pipenv run gphotos-sync --index-only my root file 
after succesfully done I checked log file in root directory 

but I can only find 91 records in photos, Is that correct? I paste alone with log

**To Reproduce**
Steps to reproduce the behaviour:
01-06 14:26:00 gphotos.Checks DEBUG    Checking if File system supports unicode filenames...
01-06 14:26:00 gphotos.Checks INFO     Filesystem supports Unicode filenames
01-06 14:26:00 gphotos.Checks DEBUG    Checking if File system is case insensitive...
01-06 14:26:00 gphotos.Checks INFO     Case sensitive file system found
01-06 14:26:00 gphotos.Checks INFO     Max Path Length: 4096
01-06 14:26:00 gphotos.Checks INFO     Max filename length: 255
01-06 14:26:00 gphotos.Main INFO     version: 2.14.2+52.gf47e578.dirty, database schema version 5.7
01-06 14:26:04 gphotos.LocalData INFO     Saving Database ...
01-06 14:26:04 gphotos.LocalData INFO     Database Saved.
01-06 14:26:04 gphotos.LocalData INFO     Saving Database ...
01-06 14:26:04 gphotos.LocalData INFO     Database Saved.
01-06 14:26:05 gphotos.BadIds DEBUG    no bad_ids file, bad ids list is empty
01-06 14:26:05 gphotos.GooglePhotosIndex WARNING  Indexing Google Photos Files ...
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     searching for media start=None, end=None, videos=True
01-06 14:26:05 gphotos.GooglePhotosIndex DEBUG    mediaItems.list ...
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 1 photos/2019/07/IMG_0007.PNG
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 2 photos/2019/07/IMG_0006.PNG
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 3 photos/2019/07/IMG_0005.PNG
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 4 photos/2019/07/IMG_0004.PNG
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 5 photos/2019/07/IMG_0003.PNG
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 6 photos/2019/07/IMG_0002.PNG
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 7 photos/2019/07/IMG_0001.PNG
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 8 photos/2015/05/7390047d-04ec-46b4-883d-d32e1ebb793f.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 9 photos/2015/03/10530762_1407652379528354_3786546398829862332_n.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 10 photos/2015/03/04_01.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 11 photos/2015/03/04.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 12 photos/2015/03/03_01.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 13 photos/2015/03/03.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 14 photos/2015/03/02_01.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 15 photos/2015/03/01_01.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 16 photos/2015/03/02.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 17 photos/2015/03/01.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 18 photos/2015/03/愛面族頁面.png
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 19 photos/2015/03/愛面族產品2.png
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 20 photos/2015/03/愛面族產品1.png
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 21 photos/2015/03/愛面族-給愛當面交易的族群.png
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 22 photos/2015/03/愛面族-給愛當面交易的族群 (2).png
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 23 photos/2015/03/愛面族 - iPhone  amp; iPad備份還原服務中心.png
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 24 photos/2015/03/愛面族 - iPhone   iPad備份還原服務中心.png
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 25 photos/2015/03/下載.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 26 photos/2015/03/upload_file_38.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 27 photos/2015/03/logo.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 28 photos/2015/03/iphone6-peque_ad_l.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 29 photos/2015/03/PASTA PANDA.JPG
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 30 photos/2015/03/Redocn_2012022103051414.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 31 photos/2015/03/275d2f69-b240-42a9-8a48-45987a44c56a.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 32 photos/2015/03/1918254_414020622463_6326022_n.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 33 photos/2015/03/10470735_1407651762861749_6540768186121776369_n.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 34 photos/2015/03/IMG_0005.JPG
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 35 photos/2015/03/IMG_0004.JPG
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 36 photos/2015/02/愛面族-給愛當面交易的族群.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 37 photos/2015/02/愛面族-給愛當面交易的族群 (2).jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 38 photos/2015/02/20150205_153246.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 39 photos/2015/02/20150205_153120.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 40 photos/2015/02/20150205_153002.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 41 photos/2015/02/20150205_152943.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 42 photos/2015/02/20150205_152111.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 43 photos/2015/02/20150205_152102.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 44 photos/2015/01/S__10084373.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 45 photos/2014/04/DSC_2034-2.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 46 photos/2014/04/DSC_2033-2.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 47 photos/2014/04/DSC_2032-2.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 48 photos/2014/04/DSC_2031.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 49 photos/2014/04/DSC_2030.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 50 photos/2014/04/DSC_2027.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 51 photos/2014/04/DSC_2026.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 52 photos/2014/04/DSC_2025.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 53 photos/2014/04/DSC_2024.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 54 photos/2014/04/DSC_2022.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 55 photos/2014/04/DSC_2021.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 56 photos/2014/04/DSC_2020.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 57 photos/2014/04/DSC_2015.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 58 photos/2014/04/DSC_2014.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 59 photos/2014/04/DSC_2013.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 60 photos/2014/04/DSC_2012.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 61 photos/2014/04/DSC_2011.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 62 photos/2014/04/DSC_2010.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 63 photos/2014/04/DSC_2009.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 64 photos/2014/04/DSC_2008.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 65 photos/2014/04/DSC_2007.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 66 photos/2014/04/DSC_2006.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 67 photos/2014/04/DSC_2005.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 68 photos/2014/04/DSC_2004.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 69 photos/2014/04/DSC_2003.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 70 photos/2014/04/DSC_2002.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 71 photos/2014/04/DSC_2001.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 72 photos/2014/04/DSC_2000.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 73 photos/2014/04/DSC_1999.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 74 photos/2014/03/BBox-17.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 75 photos/2014/03/BBox-16.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 76 photos/2014/03/BBox-15.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 77 photos/2014/03/BBox-14.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 78 photos/2014/03/BBox-13.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 79 photos/2014/03/BBox-12.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 80 photos/2014/03/BBox-11.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 81 photos/2014/03/BBox-10.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 82 photos/2014/03/BBox-09.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 83 photos/2014/03/BBox-08.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 84 photos/2014/03/BBox-07.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 85 photos/2014/03/BBox-06.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 86 photos/2014/03/BBox-05.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 87 photos/2014/03/BBox-04.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 88 photos/2014/03/BBox-03.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 89 photos/2014/03/BBox-02.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 90 photos/2014/03/BBox-01.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex INFO     Indexed 91 photos/2014/03/BBox-led燈.jpg
01-06 14:26:05 gphotos.GooglePhotosIndex DEBUG    search_media parsed 91 media_items with 100 PAGE_SIZE
01-06 14:26:05 gphotos.GooglePhotosIndex WARNING  indexed 91 items
01-06 14:26:05 gphotos.LocalData INFO     Saving Database ...
01-06 14:26:06 gphotos.LocalData INFO     Database Saved.
01-06 14:26:06 gphotos.Main WARNING  Done.
01-06 14:26:06 gphotos.Main INFO     Elapsed time = 0:00:05.491312

**Comment by gilesknap** [comment]
Sorry for the very late reply. The index will only index new files since the last sync. 

Use --index-only --rescan to see all your files.
