### ISSUE TITLE
[feature request]. add cli flag to allow for deletion of all remote images

### ISSUE THREAD

**Issue by cocoonkid** [gilesknap/gphotos-sync#337]
[feature request]. add cli flag to allow for deletion of all remote images

This would be very helpful indeed.

I'm currently using https://github.com/mrishab/google-photos-delete-tool but a flag to do it automatically after all photos have been synced a.k.a cleanup would be great.

Thank you for considering.

**Comment by gilesknap** [comment]
Thanks for the request. My policy with gphotos-sync is to keep it read only, so I'm not going to implement this. Having a separate tool to do the job feels safer!

**Comment by frankenstein91** [comment]
after buying a new Pixel phone and no longer having unlimited storage on Google Photos, I would like to have this feature after the vacations. So I would have a simple solution after the vacation to pull the pictures on the NAS and enough storage again for the next vacation at Google.

**Comment by gilesknap** [comment]
@frankenstein91 sorry its still a no. Your need is quite simple, there are lots of tutorials on deleting all of your google photos.

**Comment by frankenstein91** [comment]
@gilesknap maybe a no from you... But someone else with enough knowledge could see the need and start a fork of your project where it would be yes
