### ISSUE TITLE
dodanie informacji o ścieżce w widoku duplikatów

### ISSUE THREAD

**Issue by tomaasz** [gilesknap/gphotos-sync#338]
1. Czy można prosić o dodanie kolumny "Ścieżka" po kolumnie "Nazwa" w widoku Duplikaty?
2. Czy można prosić o możliwość sortowania po kolumnach tak aby można było łatwo usunąć wszystkie duplikaty z wybranej lokalizacji ?

system: Linux Mint 20.3 64bit

![image](https://user-images.githubusercontent.com/3982973/153046353-dd70e922-8b66-477a-bf40-911225cc7b2f.png)
![image](https://user-images.githubusercontent.com/3982973/153046775-8662fa9a-ed01-465d-943b-786851c45c49.png)

**Comment by gilesknap** [comment]
I think you have posted in the wrong repo? This is for the command line tool gphotos-sync
