### ISSUE TITLE
Moving out of folders

### ISSUE THREAD

**Issue by gosugimoto** [gilesknap/gphotos-sync#34]
Would love to use this script to first:
- have a synchronized local copy
- organise photos into existing photo structure (combining camera and mobile photos in one catalogue)
- ensure already downloaded photos don't get re-downloaded

**Comment by gilesknap** [comment]
gphotos-sync keeps a DB of the files it has indexed and there are two factors that mean it will not re-download a file that has been removed from the photos folder (or renamed).

1.  It keeps a 'downloaded' flag for each file and won't attempt a re-download for individual files that are already flagged. This can be overridden with the option --retry-download.
1. It also keeps a 'last scan' date once it has done a complete scan of all files in the library. It will filter all searches on google photos with this as the starting date for all subsequent scans. This can be overridden with the option --rescan

So if you want to re-organize your files then:-
 
- keep your gphotos.sqlite file safe
- don't use --rescan or --retry-download

CAVEAT: if you upgrade the version of gphotos-sync and that upgrade includes an upgrade to the DB schema it will currently flush the DB and rescan from scratch. I could pledge to provide upgrade scripts for the DB but this is quite a bit of extra work and testing - So I think it would be easiest to provide a way to set the 'last scan' date in the DB, or a way to export/import a list of 'already downloaded' files.
