### ISSUE TITLE
Cannot Download 3.0.x Docker Image on Synology NAS

### ISSUE THREAD

**Issue by recrudesce** [gilesknap/gphotos-sync#354]
Synology Docker requires an endpoint on the Docker Registry that GitHub CR doesn't support, so it's not possible to pull the latest Docker image for 3.0.x.

See here for details: https://github.community/t/correct-link-to-add-to-docker-registry/160636

Can 3.0.x be added to DockerHub directly so those with Synology NAS's can get the latest version to support the OAuth changes ?

Thanks :)
/rec

**Comment by gilesknap** [comment]
I'm just about to release a change to CI that pushes to DockerHub as well as ghcr.io.
