### ISSUE TITLE
got an unexpected keyword argument 'allowed_methods'

### ISSUE THREAD

**Issue by dantreble** [gilesknap/gphotos-sync#365]
```
06-03 12:57:44 WARNING  gphotos-sync 3.0.3 2022-06-03 12:57:44.837338
06-03 12:57:44 ERROR
Process failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gphotos_sync/Main.py", line 496, in main
    self.setup(args, db_path)
  File "/usr/local/lib/python3.8/dist-packages/gphotos_sync/Main.py", line 345, in setup
    self.auth.authorize()
  File "/usr/local/lib/python3.8/dist-packages/gphotos_sync/authorize.py", line 112, in authorize
    retries = Retry(
TypeError: __init__() got an unexpected keyword argument 'allowed_methods' 
```

Fixed by updating 

urllib3                1.25.8 > 1.26.9
requests               2.22.0 > 2.27.1

```pip3 install --upgrade urllib3```

and maybe requests as well

```pip3 install --upgrade requests```

Thanks!

**Comment by gilesknap** [comment]
Thanks for the report. This issue has been reported on Windows too. The documentation now recommends creating a new venv for the install. 

I Probably need to provide upgrade instructions too.

**Comment by richardwiden** [comment]
Why not specify the minimum version needed and let pip sort it out?

**Comment by gilesknap** [comment]
Um, good point @richardwiden !

TODO: put some min dependency versions in setup.cfg

**Comment by gilesknap** [comment]
OK I have pinned all runtime dependencies in e074651 this will go in the next release (today hopefully)
