### ISSUE TITLE
Issues running terminal mac

### ISSUE THREAD

**Issue by antoinevanla** [gilesknap/gphotos-sync#366]
Hello,

I have been looking for that kind of tool for a long time. I am not good at programming; I only know a bit of Python. I followed the tutorial, but it did not seem to work. I downloaded my client_secret.json file and then saved it under ~/Library/Application Support/gphotos-sync/ as indicated. Was I supposed to create that "gphotos-sync" file, or did I miss something?
It is said in the tutorial that I should be ready to run gphotos-sync for the first time, either locally or inside of a container. 
I created a new empty TARGET DIRECTORY file as said and then entered the gphotos-sync <TARGET_DIRECTORY> command in the terminal, but this `happens` zsh: parse error near ``\n.'`

Could someone help me with this, please?
I'm sorry I'm a beginner regarding computer stuff

Thank 👏

**Comment by gilesknap** [comment]
Hi, please can you post the output of your `pip install` command? And maybe a screenshot of your attempt to run gphotos-sync ?

It's a little hard for me to support Mac as I do not have one. However - the CI does run tests on Mac so it should work. 

Maybe if you take a look at the log of the Mac tests it might give you a clue? https://github.com/gilesknap/gphotos-sync/runs/6857681963?check_suite_focus=true

**Comment by antoinevanla** [comment]
Hi, thanks for your quick answer. I attached a screenshot of the outputs.

<img width="653" alt="Screenshot 2022-06-18 at 13 42 07" src="https://user-images.githubusercontent.com/107718125/174435948-f6e89ce0-a28e-40d8-a69d-36feb71a5b95.png">

I looked also the log of the Mac tests to see if it could help me but it did not...

Thanks

**Comment by gilesknap** [comment]
Hi,

You need to supply your own target directory. E.g.
```
mkdir myphotos
gphotos-sync myphotos
```

Maybe I need to make that clearer in the docs.

**Comment by antoinevanla** [comment]
Hi, thanks for your answer.

<img width="585" alt="Screenshot 2022-06-18 at 14 30 17" src="https://user-images.githubusercontent.com/107718125/174437742-ea3f8957-099e-4bc7-95c5-7dc72b2cfd1d.png">

It seems to work. However, it indexed only 1239 items and I have thousands more. Is there something more that needs to be done?

Thank you so much

**Comment by gilesknap** [comment]
The Google API does have bugs that mean some photo libraries don't get all their photos downloaded.

One thing to ask is do you have library sharing enabled with another account? In this case not all the photos you see in the web UI are actually in your own library (you can select them and choose to add them via the web UI)

**Comment by antoinevanla** [comment]
I managed to download everything with the --album command! Thanks for solving my issue 👏
