### ISSUE TITLE
Already Downloaded count is unintuitive

### ISSUE THREAD

**Issue by stloewen** [gilesknap/gphotos-sync#37]
I think I understand your thought behind what the reported "Already Downloaded"-number denotes.
But I find it quite unintuitive. I have a complete backup of my Google Photos collection and when I run gphotos-sync and there are no changes I get:

```
Downloaded 0 Items, Failed 0, Already Downloaded 0
```

This always has me thinking "wait. there are 0 items? But I already hat 22k last time. What happened?"
Having "Already Downloaded" print the full number of mediaitems that are already downloaded would be more intuitive to me. Even if you want to stick to the current logic behind this I'd find outputting library size (in number of items) helpful (mainly for reassuring that everything is backed up).

**Comment by gilesknap** [comment]
I've made  "Already Downloaded" count the number of items in the DB already marked as downloaded or the number of files found to already exist when --retry-downloaded is specified.

Does that work?

**Comment by gilesknap** [comment]
fixed

**Comment by stloewen** [comment]
Sorry for the late response.
That is more intuitive, yes. Thanks a lot for your effort.
