### ISSUE TITLE
How to authente without browser in localhost

### ISSUE THREAD

**Issue by NiepozornyDrwal** [gilesknap/gphotos-sync#375]
Hi, 
I am trying to set up sync my QNAP with google photos. The problem is that I cannot install the browser on my QNAP. I tried to visit URL on another computer, copy the response URL and post it with curl, but it didn't work.
Does anyone have any idea how to walk around this?

**Comment by gilesknap** [comment]
You can do the initial authentication on a workstation with browser and then copy over the token file.

see https://gilesknap.github.io/gphotos-sync/main/tutorials/installation.html#headless-gphotos-sync-servers

**Comment by robex2005** [comment]
You need to setup Gphotos Sync also on windows. After setup, when you log in from cmd, a browser windows will open to autenticate.
After succesfull authentication, copy over the token file to linux
I had the same problem, from a headless linux setup...

**Comment by gilesknap** [comment]
@NiepozornyDrwal Hopefully the above has resolved your issue. Reopen if you are still having issues.
