### ISSUE TITLE
401 Client Error:

### ISSUE THREAD

**Issue by nigfasa** [gilesknap/gphotos-sync#376]
Hello! 
I was downloading my photos and videos and some internet connection problem happened. After that, I canceled it so I could restart the process but each time I run the program I get a 401 error with unathenticaded which is pretty weird as I was using the same client_secret.json. I created some new credentials and they throw the same error. 

Here is the error after the connection broke
`Retrying (Retry(total=19, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='lh3.googleusercontent.com', port=443): Read timed out. (read timeout=60)")': /l
`

Current errors. 
`07-26 21:30:09 ERROR    Request failed with status 401: b'{\n  "error": {\n    "code": 401,\n    "message": "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",\n    "status": "UNAUTHENTICATED"\n  }\n}\n'`

`requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://photoslibrary.googleapis.com/v1/mediaItems?pageSize=100`

Do you know how could I solve it?

**Comment by nigfasa** [comment]
Update: it started working once again. No reason at all.

**Comment by gilesknap** [comment]
I'd say that sounds like a temporary glitch at the Google Servers end.
