### ISSUE TITLE
How to upgrade to newer version

### ISSUE THREAD

**Issue by robex2005** [gilesknap/gphotos-sync#377]
Hello, 

I wanted to upgrade to new 3.0.4 version (from 3.0.3), but i cant find any info on this
Cannot find a pip command to upgrade

Any advice?

Thanks,

**Comment by gilesknap** [comment]
This version cannot release to pypi until google accepts my PR or I do some other workaround.

However the changes to 3.0.4 only affect containers and the 3,0,4 container is released to DockerHub.

TLDR: you don't need to pip install 3.0.4
