### ISSUE TITLE
documentation for Synology

### ISSUE THREAD

**Issue by bvdbos** [gilesknap/gphotos-sync#379]
With help of @brianrook on
https://bullyrooks.com/index.php/2021/02/02/backing-up-google-photos-to-your-synology-nas/
I managed to setup my Synology-Synch, not a specialist in docker-things. I think it would be a good thing to expand the documentation. For one thing in the redirect-url after authentication was localhost where it should be the Synology-URL. For that to work the port had to be added to the command:
` sudo docker run -ti --name gphotos-sync -p 8080:8080 -v /volume3/photo/googlephotos:/storage -v /volume3/docker/gphotos-sync/config/gphotos-sync/:/config gilesknap/gphotos-sync:latest /storage
`
and after that manually replace the localhost-url on the error-page to the url of your synology-device.

**Comment by gilesknap** [comment]
Hi @bvdbos. Honestly I'm surprised that your replacing of the URL worked!

The new google auth flow only supports localhost so the recommendation in the docs is to make the token on a workstation and then copy it over. 

Would you be interested in contributing a short description of your steps to add to the docs. OR doing a PR?

Thanks,
giles

**Comment by bvdbos** [comment]
> Hi @bvdbos. Honestly I'm surprised that your replacing of the URL worked!
> ...
> Would you be interested in contributing a short description of your steps to add to the docs. OR doing a PR?

Will make a PR that but it will mostly be a blatant copy of the documentation of @brianrook if he doesn't mind :)

**Comment by gilesknap** [comment]
@bvdbos thanks! I suggest a separate RST dedicated to Synology.

**Comment by Arn0uDz** [comment]
Thanks this fixed it for me.

**Comment by gilesknap** [comment]
Consolidating docs issues here #417
