### ISSUE TITLE
Original file not downloading

### ISSUE THREAD

**Issue by i-rupesh** [gilesknap/gphotos-sync#390]
gphotos-sync is not downloading original file from google photos. It is a downloading lower version of file.

**Comment by gilesknap** [comment]
Yes you are correct. Sorry about that but the Google API is crippled and it does not look like they will fix it anytime soon
https://gilesknap.github.io/gphotos-sync/main/explanations/googleapiissues.html

Maybe I need to highlight these issues more prominently in the README.

**Comment by mupsje** [comment]
Yes, please add a highlight comment to the README.
I just found this thread , so my search for the "missing video" is over ;)

thanks

**Comment by gilesknap** [comment]
I have made a prominent warning in the main README. Closing this issue.

**Comment by gilesknap** [comment]
@mupsje for a list of the commands 
```
gphotos-sync --help
```
