### ISSUE TITLE
FreeBSD error "ModuleNotFoundError: No module named '_sqlite3'"

### ISSUE THREAD

**Issue by irgipaulius** [gilesknap/gphotos-sync#393]
## system:
- a TrueNAS jail with FreeBSD 12.2-RELEASE-p13
- followed instructions [here](https://gilesknap.github.io/gphotos-sync/main/tutorials/installation.html)
- python version 3.9.15
- pip version 22.0.4 for the python 3.9

## issue command:
``` 
gphotos-sync --version
```
as well as:
```
gphotos-sync /media/gphotos --skip-files --skip-albums --skip-index
```

## expected result:

> some version code

or

> something else, really

## actual result:
```
(venv) root@myjail:~ # gphotos-sync --version
Traceback (most recent call last):
  File "/root/gphotos/venv/bin/gphotos-sync", line 5, in <module>
    from gphotos_sync.Main import main
  File "/root/gphotos/venv/lib/python3.9/site-packages/gphotos_sync/Main.py", line 13, in <module>
    from gphotos_sync import Utils, __version__
  File "/root/gphotos/venv/lib/python3.9/site-packages/gphotos_sync/Utils.py", line 6, in <module>
    from sqlite3 import Timestamp
  File "/usr/local/lib/python3.9/sqlite3/__init__.py", line 57, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.9/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
```

<hr/>

## description

I tried installing gphotos-sync from pkg, as well as from the git repository. same issue.

How do I install sqlite? I don't understand how python packages are built, so please be specific, or provide links to resources. pretty please <3

thanks!

**Comment by gilesknap** [comment]
Hmmm.

I'm not sure what is happening here but have zero experience of FreeBSD.

Normally pip will pull all the dependencies you need.

Please could you post all the output when you run.

```
pip install gphotos-sync
```

**Comment by gilesknap** [comment]
Oh and then the output from
```
pip freeze
```

**Comment by gilesknap** [comment]
Sorry for very late reply. I'm going to say that as sqlite is not a pure python package you are out of luck on BSD. Closing as 'sorry we don't support BSD' But feel free to re-open if you think there is any hope.
