### ISSUE TITLE
Can't get usable token

### ISSUE THREAD

**Issue by Iceman248** [gilesknap/gphotos-sync#396]
I installed this app on Windows through Python just to generate a token file, then tried to copy that token and eventually the entire folder, but neither way worked. I just get this error. I had read that someone used Python to generate, thought token was for account so therefore it would work, but apparently not. How can I get this going on unRAID? Before, it would just end up at some locahost server in the browser, but I never saw a token generated, so that is why I tried it through Windows.

`Request failed with status 401: b'{\n  "error": {\n    "code": 401,\n    "message": "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",\n    "status": "UNAUTHENTICATED"\n  }\n}\n' 
11-06 15:26:25 ERROR    
Process failed. 
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/gphotos_sync/Main.py", line 497, in main
    self.start(args)
  File "/usr/lib/python3.9/site-packages/gphotos_sync/Main.py", line 437, in start
    self.do_sync(args)
  File "/usr/lib/python3.9/site-packages/gphotos_sync/Main.py", line 401, in do_sync
    self.google_photos_idx.index_photos_media()
  File "/usr/lib/python3.9/site-packages/gphotos_sync/GooglePhotosIndex.py", line 148, in index_photos_media
    items_json = self.search_media(
  File "/usr/lib/python3.9/site-packages/gphotos_sync/GooglePhotosIndex.py", line 116, in search_media
    return self._api.mediaItems.list.execute(  # type: ignore
  File "/usr/lib/python3.9/site-packages/gphotos_sync/restclient.py", line 106, in execute
    result.raise_for_status()
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://photoslibrary.googleapis.com/v1/mediaItems?pageSize=100
11-06 15:26:25 WARNING  Done. `

**Comment by Iceman248** [comment]
I actually seem the get the same error using the app on Windows that was just working. Ugh.

**Comment by Iceman248** [comment]
Regenerating token worked. Hopefully it doesn't have to be done every few hours.

**Comment by Iceman248** [comment]
It does have to be done every few hours or so. I don't recall reading anything about that. Is that actually how this works?

**Comment by gilesknap** [comment]
You should never need to regenerate the token, it should be automatically refreshed as needed.

Are you getting the same error above now or do you get 'token expired'?

**Comment by Iceman248** [comment]
Well, it just worked this time. Strange. It did appear to regenerate, as the token date is from when I just tried to run it.

I'll monitor and see if it stops working again.
