### ISSUE TITLE
ImportError: cannot import name 'external_account_authorized_user' from 'google.auth' - Solved for ArchLinux

### ISSUE THREAD

**Issue by wdirksen** [gilesknap/gphotos-sync#398]
This is meant to be both a report of a dependency compatibility issue but also a workaround. Recently  gphotos-sync stopped working in ArchLinux with this error:

`ImportError: cannot import name 'external_account_authorized_user' from 'google.auth' (/usr/lib/python3.10/site-packages/google/auth/__init__.py)`

I came accross this:
https://stackoverflow.com/questions/74189694/cannot-import-name-external-account-authorized-user-from-google-auth

Downgrading from python-google-auth-oauthlib-0.7.1-2 to python-google-auth-oauthlib-0.5.2-1 fixed it

**Comment by gilesknap** [comment]
Thanks @wdirksen, I need to sort out some dependency pins as per #397

**Comment by gilesknap** [comment]
OK the dependency pins are in and a new release will be going out today.
