### ISSUE TITLE
Push to production requires verification

### ISSUE THREAD

**Issue by TheNore** [gilesknap/gphotos-sync#399]
when trying to publish the app i am prompted with the following screen to enter additional detals, that I can not verify (app domain/policies etc.) 

Steps:
![image](https://user-images.githubusercontent.com/16988567/205324072-fd3c28ab-15c4-4981-9ec5-4bcba40b3eb6.png)

Result:
![image](https://user-images.githubusercontent.com/16988567/205324004-e02f4f08-7d95-4e6d-97bb-4a9875514ed9.png)

![image](https://user-images.githubusercontent.com/16988567/205324192-8aedf48b-f4f3-4334-9f23-7a1b2a6dbada.png)

![image](https://user-images.githubusercontent.com/16988567/205324222-fd79f4a5-6470-4d1b-9953-4f127976b5a4.png)

Another error:
Before verification this is the redirect I receive in "testing"
![image](https://user-images.githubusercontent.com/16988567/205340250-b65d387f-cb49-4be2-88ef-2bb5637bfc87.png)

**Comment by gilesknap** [comment]
this sounds bad. If Google has changed the policy then I'm not sure we will all want to publish our individual versions of gphotos-sync app.

I'm going to go through the secret creation process (yet again!) and verify if this is a new issue.

**Comment by gilesknap** [comment]
I've walked through the steps in https://gilesknap.github.io/gphotos-sync/main/tutorials/oauth2.html

It worked OK for me, so I think you have done one of the configuration steps differently to the instructions. Please can you try to go through the steps again?

I get the following dialogue when publishing which specifically says that verification is not required:
![image](https://user-images.githubusercontent.com/964827/205890373-05cd30f7-5e87-4089-b451-3e2dda66d890.png)

**Comment by brianmiller** [comment]
It's because a logo was used.  I've experienced this in my other apps.  Don't use a logo.  The logo requires branding validation.

![image](https://user-images.githubusercontent.com/342276/219883794-6c94a14c-e6be-46be-a7b5-d394c4e7775e.png)

**Comment by gilesknap** [comment]
@brianmiller thanks that is useful info. Closing this issue.
