### ISSUE TITLE
Documentation fixes

### ISSUE THREAD

**Issue by europacafe** [gilesknap/gphotos-sync#401]
After publishing the project, I run the following sync command in Unraid console:
`docker exec -it GooglePhotosSync gphotos-sync /storage`
It did provide a link and I followed the link, and chose my google user, then it said not safe due to not a verified app, but I proceed anyway. Then I checked how I want to access Google Photo, then it forwarded to the following URL which can't be found. I'm not sure how to proceed because I didn't see any syncing going.
http://[localhost](http://localhost:8080/?state=8hs7KYyUvqfQbH5FswLsfb19TcjuAn&code=4/0AfgeXvsN8t__rDR3r8mQPnG2MkHDvLHUw54fp0W07tsraGoWvt6s2F4Wlyvfs0kbSoXz_w&scope=https://www.googleapis.com/auth/photoslibrary.sharing%20https://www.googleapis.com/auth/photoslibrary.readonly):8080/?state=8hs7KYyUvqfQbH5FswLsfb19TcjuAn&code=4/0AfgeXvsN8t__rDR3r8mQPnG2MkHDvLHUw54fp0W07tsraGoWvt6s2F4Wlyvfs0kbSoXz_w&scope=https://www.googleapis.com/auth/photoslibrary.sharing%20https://www.googleapis.com/auth/photoslibrary.readonly

**Comment by gilesknap** [comment]
From this issue I think you may be running gphotos-sync on a sever? The auth process runs a web process that serves on 8080 but you need to run locally on a machine with a browser for the first run. See if this helps https://gilesknap.github.io/gphotos-sync/main/tutorials/installation.html#headless-gphotos-sync-servers

**Comment by europacafe** [comment]
Thanks. I don't know I have to install gphotos-sync on my Windows and follow the whole process on Windows till I got the token and then copy the token to my Unraid gphotos-sync storage folder. It is working now...thanks.

**Comment by gilesknap** [comment]
@europacafe thanks for letting me know. I think the documentation does not highlight this fact well as it is hidden in container discussion. I'll take a look at restructuring.

**Comment by europacafe** [comment]
I can only partly follow the headless command lines as described in the document. Maybe it was due to my python installation on my Windows. I somehow had to improvise it till it is working now. For example, my Windows can't find the "source" and gphotos-sync commands even I add path. Anyway, I'm happy now and thank you again.

**Comment by gilesknap** [comment]
Reopened as issues with Docs

- Promote the headless instructions to the main flow, not just for the containers users
- Add Windows/Mac descriptions where skeleton docs have assumed Linux

**Comment by caseyjhol** [comment]
Also, in the "Running gphotos-sync" section, the `--max-threads` option is incorrectly listed as `--threads`.

**Comment by gilesknap** [comment]
Consolidating docs issues into #417
