### ISSUE TITLE
Downloading fails for certain name strings

### ISSUE THREAD

**Issue by locomuco** [gilesknap/gphotos-sync#404]
For some reason some of my google photos contain ```:nopm:``` at the end of the filename in gphotos 

```
01-06 07:01:38 ERROR    FAILURE 2 downloading photos/2014/05/IMG_20140502_155004:nopm:.jpg - [Errno 22] Invalid argument: '/media/matthias/029A75499A7539ED/google-photos/photos/2014/05/tmp292e6om1' -> '/media/matthias/029A75499A7539ED/google-photos/photos/2014/05/IMG_20140502_155004:nopm:.jpg' 

```

Expectation would be correct download handling, or dropping with a notice

**Comment by gilesknap** [comment]
@locomuco which filesystem are you saving your photos too?

**Comment by locomuco** [comment]
ntfs

**Comment by gilesknap** [comment]
So colon is illegal for ntfs I believe. I think that means that gphotos-sync is not picking up on your filesystem correctly.

Please try the command line option ``--ntfs`` which forces it to use ntfs file naming.

**Comment by gilesknap** [comment]
I'm closing this as I hope the `--ntfs` fixed your problem. Please re-open if you still have questions.
