### ISSUE TITLE
Disable album backups

### ISSUE THREAD

**Issue by brianbgarber** [gilesknap/gphotos-sync#409]
Hello, I've noticed that I'll get either hard or symbolic links stored on one of my cache drives in Unraid when using the gphotos-sync. It appears as though these links are created by Google Photo albums and that Unraid mover has no action to move files onto array devices and keeps them on cache devices. 

Since I don't really care about Albums is there a way I can disable those backups?

**Comment by gilesknap** [comment]
Sure, just add `--skip-albums` to the command line.
See `--help` for the full set of options.
