### ISSUE TITLE
ghcr.io/gilesknap/gphotos-sync container seems limited

### ISSUE THREAD

**Issue by brianmiller** [gilesknap/gphotos-sync#410]
I may be doing something wrong.  I followed the docs:

```
#!/bin/bash

CONFIG="/mnt/cerebrum/media/Photos/MyGooglePhotos/config"
STORAGE="/mnt/cerebrum/media/Photos/MyGooglePhotos/storage"

podman run --rm -v $CONFIG:/config -v $STORAGE:/storage -p 8080:8080 -it ghcr.io/gilesknap/gphotos-sync /storage
```

This syncs all of my photos+videos to $STORAGE, which is great, but when I run it a second time it gives me:

`OSError: [Errno 39] Directory not empty: '/storage/.gphotos_check'`

A few questions:

- Is this expected behavior?  How do I keep my local copy in-sync if I have to start with an empty $STORAGE destination every time?
- Is there a way to provide arguments to the container?  There are gphotos-sync options I'd like to use.
- Is there a way to instruct gphotos-sync to delete source photos when successfully sync'd locally? My entire goal is to stop burning so much google cloud storage.

So far, fantastic tool!  I'm super pleased to see more people are looking for these options and talented devs are willing to put the time in.

**Comment by gilesknap** [comment]
Hi @brianmiller your result is unexpected. Please can you post the whole error if there is any more to it? I don't have any guesses as to the issue right now.

**Comment by gilesknap** [comment]
Digging a bit, my guess is that for some reason the removal of the filesystem check folder is failing silently here:
https://github.com/gilesknap/gphotos-sync/blob/61f0a8f2456ac0a47ce532dccbbe60ed3f6bfdc5/src/gphotos_sync/Checks.py#L117

So the next run it blows up.

What filesystem is your /mnt/cerebrum/media/Photos/MyGooglePhotos/storage ?

**Comment by brianmiller** [comment]
Thanks for the reply.   /mnt/cerebrum/media/Photos/MyGooglePhotos/storage is an NFS export on top of XFS via Unraid.

If I wait a few minutes, .gphotos_check disappears by itself and runs fine.  It must be related to NFS sync--maybe exporting with 'sync' instead of 'async' will fix this.  I'll poke around.

**Comment by gilesknap** [comment]
I'm closing this as an issue with your filesystem please reopen if you think there are bugs that need addressing.
