### ISSUE TITLE
Albums folders are empty

### ISSUE THREAD

**Issue by Floooowk** [gilesknap/gphotos-sync#412]
Hello,

I use the tool from Docker, on a Synology NAS.
It works almost perfectly, although as a beginner, I had to do several tests by installing/uninstalling the container several times until I found the configuration that suited me.

Here is the command line I run to create my container: `sudo docker run --name gphotos-sync -v /volume1/docker/PhotoSync:/config -v /volume1/homes/mydrive/GooglePhotos:/storage -p 8080:8080 -it ghcr.io/gilesknap/gphotos-sync /storage --port 8080 --omit-album-date --rescan --flush-index --do-delete `
I then run a scheduled task once a day to keep my folder up to date.

The "photos" folder works perfectly and synchronizes correctly (add & delete photos).

On the other hand, the "albums" folder does create the album folders, but they are empty. However, it seems to me that I have seen in my previous installations these folders filled. Each time I reinstall the container, I delete the folders, I tried to delete the options in my command line, but nothing works.

**Comment by gilesknap** [comment]
Hi @Floooowk I've never used --omit-album-date. What happens if you leave that option out?

**Comment by gilesknap** [comment]
The other likely issue is to do with softlinks support on your filesystem. gphotos sync uses sofrlinks to create the albums files, so they do not take up extra space on your drive. Not all filesystems support this (although I would usually expect that to throw an error).

If this is the issue it might help to use --use-hardlinks

**Comment by gilesknap** [comment]
BTW --rescan is redundant if you use --flush-index (although adding it is benign)

**Comment by Floooowk** [comment]
Thanks again @gilesknap! It seems to work with this command line. `
sudo docker run --name gphotos-sync -v /volume1/docker/PhotoSync:/config -v /volume1/homes/fcastillon/GooglePhotos:/storage -p 8080:8080 -it ghcr.io/gilesknap/gphotos-sync /storage --port 8080 --omit-album-date --use-hardlinks --flush-index --do-delete `
I'll see in use if everything goes as planned.

I would have liked to have a structure like YYYY/photo.xxx (instead of YYYY/MM/photo.xxx) for the pictures. But I did not find how to use the options -month-format or -photos-path or -path-format).  That said, it's already very good as it is.

**Comment by gilesknap** [comment]
Yep I don't think changing the photos folders layout options ever got implemented. It makes the incremental backup harder to manage. 

Closing as I think you are generally happy!
