### ISSUE TITLE
Documentation Issues

### ISSUE THREAD

**Issue by gilesknap** [gilesknap/gphotos-sync#417]
I'm using this issue to collect a number of documentation problems into one place:

- Make sure venv creation instructions are clear to non python experts https://github.com/gilesknap/gphotos-sync/issues/374#issuecomment-1193109290
- Add use of -u $(id -u):$(id -g) in docker args for nice file permissions
- Promote installing on a server to a heading in the docs - review the whole how to do remote / container section
- add the remote installation hack approach https://github.com/gilesknap/gphotos-sync/issues/379#issuecomment-1221191662
- consider a Synology specific page as per #379
- Add Windows/Mac descriptions where skeleton docs have assumed Linux see # 401
- Also, in the "Running gphotos-sync" section, the --max-threads option is incorrectly listed as --threads.
- Windows can't find the "source" and gphotos-sync commands even I add path. Hmmmm this is such a pain on Windows. Maybe recommend docker on Windows??
- Add docs on how to use docker compose from #414 See https://github.com/gilesknap/gphotos-sync/issues/414#issuecomment-1475118798
- document use of --id and --gid in docker invocation. See #279

**Comment by KjeldsenDK** [comment]
Haha, this reads as a blog of the night i had yesterday, gave up on windows, installed WSL, more issues, finally got it up and running on a Mac (not in a virtual environment, that threw an error). But i have to say, compared to so many other other docs, this at least gave me a chance.

Imho, there are so many steps and dependencies that people without any real knowledge of Python and Linux will be in trouble. Guides like this are typically created on a machine that have some or all of the needed software installed and gives the author zero chance of knowing what will happen at the end user. The only easy way is a binary :-/ 

Anyway, this piece of software (i it works when i am done hitting Google Quotas, 10.000 urls.. please!) is a godsend. Getting out of Google's grabbing hands is almost impossible with 2980 albums and hundred thousands of photos.

**Comment by gilesknap** [comment]
@KjeldsenDK sorry about that -  I'm not spending much time on this project due to #119.

Be Warned. Google's crippling of the API means gphotos-sync is not your ticket to exiting Google's grabbing hands unless you accept several limitations - see #119

**Comment by gilesknap** [comment]
Closing as completed.
