### ISSUE TITLE
Application breaks when run on linux and it tries to create links on NTFS-like target FS

### ISSUE THREAD

**Issue by mucst** [gilesknap/gphotos-sync#425]
I'm running the application in docker (today's latest version: 3.1.2), git revision a631449f252f624b8109f3134620d3a412b543d7. Host Device is a Raspberry PI 2, attached an exFat filesystem external HDD.
When I try to run the application, it fails with:
```
docker run --rm -v /home/pi/mediacenter/gphotos/config:/root/.config/gphotos-sync -v /media/myHdd/gphotos:/storage -p 8080:8080 -it ghcr.io/gilesknap/gphotos-sync --album MY_ALBUM --start-date 2023-04-01 /storage
# Note: I tried to add --ntfs option, did not help.

04-08 20:59:15 WARNING  gphotos-sync 3.1.2 2023-04-08 20:59:15.194045
04-08 20:59:15 ERROR    Symbolic links not supported
04-08 20:59:15 ERROR    Albums are not going to be synced - requires symlinks
04-08 20:59:16 WARNING  Downloading Photos ...
04-08 20:59:16 WARNING  Downloaded 0 Items, Failed 0, Already Downloaded 2
04-08 20:59:16 WARNING  Indexing Shared (titled) Albums ...
04-08 20:59:17 WARNING  Indexed 3 Shared (titled) Albums
04-08 20:59:17 WARNING  Indexing Albums ...
04-08 20:59:18 WARNING  Indexed 2 Albums
04-08 20:59:18 WARNING  Downloading Photos ...
04-08 20:59:18 WARNING  Downloaded 0 Items, Failed 0, Already Downloaded 2
04-08 20:59:18 WARNING  Creating album folder links to media ...
04-08 20:59:18 ERROR
Process failed.
Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/gphotos_sync/Main.py", line 507, in main
    self.start(args)
  File "/root/.local/lib/python3.10/site-packages/gphotos_sync/Main.py", line 447, in start
    self.do_sync(args)
  File "/root/.local/lib/python3.10/site-packages/gphotos_sync/Main.py", line 436, in do_sync
    self.google_albums_sync.create_album_content_links()
  File "/root/.local/lib/python3.10/site-packages/gphotos_sync/GoogleAlbumsSync.py", line 329, in create_album_content_links
    os.symlink(relative_filename, link_file)
PermissionError: [Errno 1] Operation not permitted: '../../../photos/2023/04/IMG_8133.MOV' -> '/storage/albums/2023/0405 MY_ALBUM/0000_IMG_8133.MOV'
04-08 20:59:18 WARNING  Done.
```

Apparently it tried to create a symlink on the storage which failed. Is there a chance to avoid this error by for example omitting symlink creation? I don't need it for my usecase anyway. I however want to synchronize a specific album.

**Comment by gilesknap** [comment]
Hi @mucst. If you try `gphotos-sync --help` you will see a few things you can try.

--use-hardlinks will use hardlinks instead of symlinks 
--ntfs declares that you are using an ntfs-like FS if detection has fails

I'm not convinced these will help though. If you are using Windows I say to enable symlinks or not sync albums. So unless you can support some kind of links in your FS I don't think gphotos-sync will work for albums.

**Comment by gilesknap** [comment]
Thanks for the detailed report.

The intention of `skip-albums` is entirely not creating symlinks. So either it's completely broken or using --album with it causes an issue.

Re symlinks on Windows. I do have windows users of this tool and it does work if you enable symlinks in the policy manager as documented here https://gilesknap.github.io/gphotos-sync/main/how-to/windows.html#symlinks. Also the CI tests in Github actions run against a WIndows VM (but I don't know for sure that it uses NTFS). 

I assume therefore that os.symlink does work on modern Windows versions at least. Can't remember the journey to make this tool work on Windows but I did testing on my linux/Windows dual boot.

**Comment by mucst** [comment]
Right. I'm surprised about the ability to enable symlinks on windows, but that explains. I'm _sure_ that the VMs run NTFS or alike filesystem because windows does not support ext fs of any kind. But ok, let's leave it at that. Thanks for the clarification.

**Comment by gilesknap** [comment]
leaving this open - TODO look at behaviour of --skip-albums with and without --album

**Comment by gilesknap** [comment]
closing as I'm tracking this in #428
