### ISSUE TITLE
Is this a product from the lead developers or endorsement?

### ISSUE THREAD

**Issue by pinamahn** [gilesknap/gphotos-sync#426]
At the bottom of README.rst there is 

> For a commercial product that backs up your library to the cloud see: See https://photovaultone.com/

Is this a product from the lead developers or endorsement for quality/privacy or security?

**Comment by gilesknap** [comment]
It's totally separate. I have tried it and it works well. I can't vouch for its security/privacy. (Maybe I should elaborate on this in README line).
