### ISSUE TITLE
Photos deleted from Google Photos are not deleted on local copy

### ISSUE THREAD

**Issue by shlomki** [gilesknap/gphotos-sync#427]
I've deleted an album and some photos, then ran a sync, but they weren't deleted from my local copy.
Since this is supposed to be a sync, I expected that the local copy would be deleted as well.
Is that normal behavior?

**Comment by gilesknap** [comment]
This is the default behaviour add `--do-delete` to remove local files that are no longer in the library. See `--help` for all the options.
