### ISSUE TITLE
Videos no longer backing up, photos still work

### ISSUE THREAD

**Issue by christophershad** [gilesknap/gphotos-sync#429]
I use a Pixel 4a phone to take pictures and videos.  I have noticed in the past several days, any videos (mp4) that I take are not coming down from Google to my gphotos-sync box.  Pictures taken before and after are coming down normally.  I've verified that the video is backing up to Google from my phone, and is visible in Google Photos, and can be downloaded manually from Google Photos, but nothing downloads from gphotos-sync.  This seems to have started 2-3 days ago.  Also, nothing about my Google Account, Google photo setup, phone, or gphotos-sync box has changed.

**Comment by gilesknap** [comment]
If nothing has changed and this has started happening, it sounds like a server side change has occurred.

I'll check to see if I am seeing this.

**Comment by christophershad** [comment]
Some additional information: I've gone back through my Google photos account, and it is intermittent or specific in some way.  Some mp4 files are downloading, some are not.  I am looking at the properties of the .mp4 files in Google Photos to see if there is any difference in properties.  gphotos-sync does not give any errors, or put anything in the gphotos.bad_ids.yaml, or show any skipped or missed files.

**Comment by shad00m** [comment]
```
04-23 17:42:05 gphotos_sync.GooglePhotosDownload ERROR    FAILURE 1 downloading photos\2020\06\vid_202xxx_xxxx_xxxx.mp4 - 404 Client Error: Not Found for url: https://video-downloads.googleusercontent.com/[redacted]
04-23 17:42:05 gphotos_sync.BadIds DEBUG    BAD ID [redacted2] for photos\2020\06\vid_202xxx_xxxx_xxxx.mp4
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\gphotos_sync\GooglePhotosDownload.py", line 278, in do_download_file
    response.raise_for_status()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://video-downloads.googleusercontent.com/{redacted]
```

same problem here - some mp4 work, some dont

**Comment by gilesknap** [comment]
I've run a local sync and will check the results this eve to see if I'm getting this issue.

@shad00m when you see 400 or 404 it is usually an intermittent network issue. Do you see files in your gphotos.bad_ids.yaml file in the root of your sync folder? If so you can try deleting this file to retry the download of those files in error.

**Comment by shad00m** [comment]
> I've run a local sync and will check the results this eve to see if I'm getting this issue.
> 
> @shad00m when you see 400 or 404 it is usually an intermittent network issue. Do you see files in your gphotos.bad_ids.yaml file in the root of your sync folder? If so you can try deleting this file to retry the download of those files in error.

thank you for your reply
interestingly, i tried the links in the yaml file yesterday and they were 404ing for me in the browser as well
today they worked... I guess google had a hickup or so. All worked now <3

**Comment by gilesknap** [comment]
apologies. although I got around to running a sync I have yet to find the time to go through it and look for missing videos.

Will get to this soon.

**Comment by gilesknap** [comment]
@christophershad I've taken a look at my last few months of library syncs and I can't find any missing videos.

Did you get any further with identifying a pattern for the missing files?

**Comment by gilesknap** [comment]
closing as stale. please reopen if required.
