### ISSUE TITLE
Local comparison feature

### ISSUE THREAD

**Issue by gilesknap** [gilesknap/gphotos-sync#43]
I'd like to be able to point at a root folder and index all the photos in there. Then compare these against the Google Photos LIbrary and create a folder of symlinks that point to the files that would need to be uploaded to make the library match.

The upload itself would need to be done by an official Google Tool (Windows or Web). This is because of the quota issue.

This is in lieu of being able to do proper sync. It will help me restore my Insync trashed Photos Library. More importantly, it will serve as a proxy for two way sync.

The feature would be designed so that it can point at its own download folder and hence almost give two-way sync. I would suggest that the folder hierarchy by create date need to be enforced for this otherwise I'll have a very complicated problem and probably do an Insync on someone's filesystem eventually.

**Comment by gilesknap** [comment]
Done.

**Comment by ikwyl6** [comment]
What if you already have local copies of some photos. Is there a way to move your local copy (when gphotos-sync has verified that local copy is on GP) to the YYYY/MM structure so there aren't duplicates on local hard drive?

**Comment by gilesknap** [comment]
This is a nice idea. But it would be impossible to do a good implementation because:
The most reliable way to verify that you are looking at the correct file is through the EXIF UID and this is the primary way gphotos-sync does matching. GP does not expose this as meta-data, so I scan the contents of your library for this information after it is already downloaded.

Thus the comparison feature currently only compares two local hierarchies of files and does not compare against its index of GP files alone. To verify a GP file matched an existing local file would require it was downloaded first anyway.
