### ISSUE TITLE
 No module named 'gphotos_sync' after upgrade to Debian Bookworm

### ISSUE THREAD

**Issue by robex2005** [gilesknap/gphotos-sync#439]
Hello, 

The script worked flawlessly until upgraded Dietpi Distro from Debian Bullseye to Bookworm
The error i'm getting is:

 root@DietPi:~/gphotos_venv# /root/gphotos_venv/bin/python3 /root/gphotos_venv/bin/gphotos-sync  --secret /root/gphotos_venv/DB2/client_secret.json --db-path /root/gphotos_venv/DB2 /mnt/backup/GPhotos/ $@ >> /root/gphotos_venv/gphotos.log --logfile /tmp
Traceback (most recent call last):
  File "/root/gphotos_venv/bin/gphotos-sync", line 5, in <module>
    from gphotos_sync.Main import main
ModuleNotFoundError: No module named 'gphotos_sync'

I reinstalled Gphotos-Sync:

root@DietPi:~# which gphotos-sync
/usr/local/bin/gphotos-sync
root@DietPi:~# gphotos-sync --version
3.1.3
root@DietPi:~# which python3
/usr/bin/python3

Any pointers to check?

Thanks, 
Robert

**Comment by gilesknap** [comment]
Hi @robex2005 

how did you reinstall ?
what is the contents of /usr/local/bin/gphotos-sync ?

I'm not clear how you are getting the venv activated. In the first command line you directly refer to the venv python and binary but after re-install you are apparently using a script /usr/local/bin/gphotos-sync

**Comment by robex2005** [comment]
Hello, sorry for the late reply

I reinstalled with the pip command, but in the meantime, i found out from the DietPi developers, that i need to reinstall the virtual enviroment also, after upgrading to bookworm
So, i reinstalled the venv also, and i edited the cron script to reflect the new path..
All is ok now

Thanks,

**Comment by gilesknap** [comment]
:+1:
