### ISSUE TITLE
Question about setuptools and wheel version pin

### ISSUE THREAD

**Issue by tjni** [gilesknap/gphotos-sync#441]
Hello!

I am working on Python packaging in [nixpkgs](https://github.com/NixOS/nixpkgs), and we have been updating setuptools and wheel. Do you still remember the context surrounding the irreproducibility that led to pinning those dependencies? I would be interested in investigating if that can be resolved in the latest versions of the tools.

**Comment by gilesknap** [comment]
Hi @tjni 

This project is based on a python3-pip-skeleton but has not merged the latest for some time. If you take a look at https://github.com/DiamondLightSource/python3-pip-skeleton-cli/blob/main/pyproject.toml then you will see that indeed whatever the issue was it has been resolved.

**Comment by gilesknap** [comment]
I think we can close this?
