### ISSUE TITLE
CloudFormation multiple resource file error?

### ISSUE THREAD

**Issue by wills721** [gilesknap/gphotos-sync#442]
After revising/updating the app.js of my Lambda function created as a result of amplify add api (REST API) I begin to encounter:

⚠️ NDCProductCodeAPI has more than one CloudFormation definitions in the resource folder which isn't permitted.
⚠️ thioscanner7b83a3c5 has more than one CloudFormation definitions in the resource folder which isn't permitted.
⚠️ amplifyDatasource has more than one CloudFormation definitions in the resource folder which isn't permitted.
⚠️ NDCProductCodeAPI has more than one CloudFormation definitions in the resource folder which isn't permitted.
⚠️ thioscanner7b83a3c5 has more than one CloudFormation definitions in the resource folder which isn't permitted.

....I attempt a amplify pull -- and then all is blown away in the function dir. 

Any idea?

**Comment by gilesknap** [comment]
I'm not sure if you posted this to the correct project? If you did then I'll need a bit of help interpreting what gphotos-sync is involved here.

**Comment by gilesknap** [comment]
Pretty sure this was a mis-post. Closing.
