### ISSUE TITLE
Error When Connecting - Running Cloud Flare and NGINX

### ISSUE THREAD

**Issue by mikejenbrown** [gilesknap/gphotos-sync#447]
Hi,

I have configured and installed the gphoto-sync docker on my UNRAID.  After I allow access to my UNRAID server I get the attached error page. Is there soemthing i need to do with cloud flare or nginx proxy to allow access?

really excited to try this out and appreciate any assistance!

**Comment by gilesknap** [comment]
Sorry but I don't know anything about UNRAID. If you search through historical closed issues on this repo there are a few users who have started conversations on the subject - you may find some help there.

**Comment by gilesknap** [comment]
closing - please respond if you still need help
