### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by Faasje1234** [gilesknap/gphotos-sync#455]
I'm on a Windows 10 desktop, I installed python312.
Whenever I type 'pip install gphotos-sync' the command prompt returns with: SyntaxError: invalid syntax
I don't understand what to do about it and why it won't install gphotos-sync, I did the whole google API thing and published my program. 
What could be wrong, if you need more information feel free to ask.
TIA

**Comment by gilesknap** [comment]
Hi @Faasje1234 

is pip installed into your path?

What do you get if you type `pip --version1`

**Comment by Faasje1234** [comment]
Yes pip seems to be installed, yesterday I got the install of gphotos-sync to work in a virtual environment, with the shift right click, but because I was formatting a disk for the space I didn't have time to actually upload the gphotos.

Now I don't have the client_secret file in the right place and also still don't have gphotos-sync installed in the right place

**Comment by gilesknap** [comment]
Sorry I'm unclear what your issue is in https://github.com/gilesknap/gphotos-sync/issues/455#issuecomment-1825514776 above. Can you describe what errors you are getting and where things are please?

**Comment by gilesknap** [comment]
closing due to no response. Please reply to the closed issue if you still need help.
