### ISSUE TITLE
Many 404 client error while downloading

### ISSUE THREAD

**Issue by artifexor** [gilesknap/gphotos-sync#463]
I am using 3.1.3 on Debian Bookworm and the download gives many different errors (403, 400 and mostly 404) while downloading the rest of gphotos is flawless. Any idea why these errors happened? I read issues here about other errors but because otherwise the downloading is fine I think this is not because of some traffic or request number limitation (for example "Downloaded 45277 Items, Failed 69, Already Downloaded 1160").

Many "not found for url" error which means there should be an image/video but the direct url is wrong, I think.

**Comment by gilesknap** [comment]
Hi @artifexor, I would say that sounds like transient server errors. Those are low level HTTP errors, if an API endpoint gets a 404 then it is currently offline.

If you continue to see these then post again and we'll look into diagnosing, but the occasional 403 points more towards Google server issues.

**Comment by artifexor** [comment]
> Hi @artifexor, I would say that sounds like transient server errors. Those are low level HTTP errors, if an API endpoint gets a 404 then it is currently offline.
> 
> If you continue to see these then post again and we'll look into diagnosing, but the occasional 403 points more towards Google server issues.

Thank you. Upgraded to 3.2.1 since. I will try to download the files with error later.

I downloaded photos through takeout and there is much more file (95 GB vs 278 GB). I configured rclone as well and what I noticed the takeout files missing some jpeg header which existed in rclone and gphotos-sync.

**Comment by gilesknap** [comment]
Re takeout:that is interesting. What jpeg info was missing ?

**Comment by artifexor** [comment]
Same image as downloaded using takeout (45945 bytes) and gphotos-sync (69618 bytes):

![0052onj7r9k81-gphotos](https://github.com/gilesknap/gphotos-sync/assets/1253917/aad3345e-18f6-4413-8047-0001f70ccc04)
![0052onj7r9k81-takeout](https://github.com/gilesknap/gphotos-sync/assets/1253917/012dff17-ad35-4d5c-9bbf-c7b0732d9658)

rclone output is the same as the gphotos-sync, probably because using the same way to download the image.

**Comment by gilesknap** [comment]
interesting, so if you download direct from the google photos web ui, how does that compare with these two? (i have limited colour vision and can't really see the difference above)

**Comment by gilesknap** [comment]
I also expected gphotos-sync to get the smaller image because it always gets 'quality' compression even if you have paid for 'original' and asked the API for original.

**Comment by gilesknap** [comment]
I think we are all good on this issue?

Please post here again if you want to re-open.
