### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by gosugimoto** [gilesknap/gphotos-sync#50]
Getting some errors now on install:
`gomachan:googlephotos gomachan$ python setup.py build
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/Users/gomachan/Documents/_temp/googlephotos/.eggs/pbr-5.1.2-py2.7.egg/pbr/core.py", line 96, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/Users/gomachan/Documents/_temp/googlephotos/.eggs/pbr-5.1.2-py2.7.egg/pbr/util.py", line 256, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "/Users/gomachan/Documents/_temp/googlephotos/.eggs/pbr-5.1.2-py2.7.egg/pbr/hooks/__init__.py", line 25, in setup_hook
    metadata_config.run()
  File "/Users/gomachan/Documents/_temp/googlephotos/.eggs/pbr-5.1.2-py2.7.egg/pbr/hooks/base.py", line 27, in run
    self.hook()
  File "/Users/gomachan/Documents/_temp/googlephotos/.eggs/pbr-5.1.2-py2.7.egg/pbr/hooks/metadata.py", line 26, in hook
    self.config['name'], self.config.get('version', None))
  File "/Users/gomachan/Documents/_temp/googlephotos/.eggs/pbr-5.1.2-py2.7.egg/pbr/packaging.py", line 849, in get_version
    name=package_name))
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name gphotos-sync was given, but was not able to be found.
error in gphotos-sync setup command: Error parsing /Users/gomachan/Documents/_temp/googlephotos/setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name gphotos-sync was given, but was not able to be found.
`

and then also

`mock 2.0.0 has requirement six>=1.9, but you'll have six 1.4.1 which is incompatible.`

and then

`gomachan:googlephotos gomachan$ sudo python setup.py install
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pbr/core.py", line 96, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/Library/Python/2.7/site-packages/pbr/util.py", line 256, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "/Library/Python/2.7/site-packages/pbr/hooks/__init__.py", line 25, in setup_hook
    metadata_config.run()
  File "/Library/Python/2.7/site-packages/pbr/hooks/base.py", line 27, in run
    self.hook()
  File "/Library/Python/2.7/site-packages/pbr/hooks/metadata.py", line 26, in hook
    self.config['name'], self.config.get('version', None))
  File "/Library/Python/2.7/site-packages/pbr/packaging.py", line 849, in get_version
    name=package_name))
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name gphotos-sync was given, but was not able to be found.
error in gphotos-sync setup command: Error parsing /Users/gomachan/Documents/_temp/googlephotos/setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name gphotos-sync was given, but was not able to be found.
`

**Comment by gilesknap** [comment]
HI,

It looks like my installer needs to be run from a git repo with a  github upstream remote. It looks like you might not have that.

Please can you try
git clone https://github.com/gilesknap/gphotos-sync.git
cd gphotos-sync
python setup.py build
sudo python setup.py install

If that is already what you did then let me know and we'll try to debug.

**Comment by gilesknap** [comment]
Also, please describe to me the steps you used to get the error if it was not the above.

**Comment by gosugimoto** [comment]
Just gave all that a try now, somethings look better, but I see some errors too:

gomachan:~ gomachan$ git clone https://github.com/gilesknap/gphotos-sync.git
Cloning into 'gphotos-sync'...
remote: Enumerating objects: 124, done.
remote: Counting objects: 100% (124/124), done.
remote: Compressing objects: 100% (91/91), done.
remote: Total 1951 (delta 69), reused 76 (delta 32), pack-reused 1827
Receiving objects: 100% (1951/1951), 6.80 MiB | 4.64 MiB/s, done.
Resolving deltas: 100% (1451/1451), done.
gomachan:~ gomachan$ cd gphotos-sync
gomachan:gphotos-sync gomachan$ python setup.py build
running build
running build_py
creating build
creating build/lib
creating build/lib/test
copying test/test_setup.py -> build/lib/test
copying test/test_database.py -> build/lib/test
copying test/__init__.py -> build/lib/test
copying test/test_system.py -> build/lib/test
copying test/test_requests.py -> build/lib/test
copying test/test_units.py -> build/lib/test
creating build/lib/gphotos
copying gphotos/DbRow.py -> build/lib/gphotos
copying gphotos/LocalData.py -> build/lib/gphotos
copying gphotos/DatabaseMedia.py -> build/lib/gphotos
copying gphotos/GoogleAlbumsSync.py -> build/lib/gphotos
copying gphotos/authorize.py -> build/lib/gphotos
copying gphotos/BadIds.py -> build/lib/gphotos
copying gphotos/__init__.py -> build/lib/gphotos
copying gphotos/BaseMedia.py -> build/lib/gphotos
copying gphotos/GooglePhotosDownload.py -> build/lib/gphotos
copying gphotos/Utils.py -> build/lib/gphotos
copying gphotos/GoogleAlbumMedia.py -> build/lib/gphotos
copying gphotos/GooglePhotosIndex.py -> build/lib/gphotos
copying gphotos/Main.py -> build/lib/gphotos
copying gphotos/GooglePhotosMedia.py -> build/lib/gphotos
copying gphotos/restclient.py -> build/lib/gphotos
running egg_info
creating gphotos_sync.egg-info
writing pbr to gphotos_sync.egg-info/pbr.json
writing requirements to gphotos_sync.egg-info/requires.txt
writing gphotos_sync.egg-info/PKG-INFO
writing top-level names to gphotos_sync.egg-info/top_level.txt
writing dependency_links to gphotos_sync.egg-info/dependency_links.txt
[pbr] Processing SOURCES.txt
writing manifest file 'gphotos_sync.egg-info/SOURCES.txt'
[pbr] In git context, generating filelist from git
warning: no previously-included files found matching '.gitreview'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
writing manifest file 'gphotos_sync.egg-info/SOURCES.txt'
copying test/testDb1.sqlite -> build/lib/test
creating build/lib/test/test_credentials
copying test/test_credentials/.gphotos.token -> build/lib/test/test_credentials
copying test/test_credentials/client_secret.json -> build/lib/test/test_credentials
creating build/lib/gphotos/sql
copying gphotos/sql/gphotos_create.sql -> build/lib/gphotos/sql
running build_scripts
creating build/scripts-2.7
copying and adjusting gphotos-sync -> build/scripts-2.7
changing mode of build/scripts-2.7/gphotos-sync from 644 to 755
gomachan:gphotos-sync gomachan$ sudo python setup.py install
Password:
running install
[pbr] Writing ChangeLog
[pbr] Generating ChangeLog
[pbr] ChangeLog complete (0.0s)
[pbr] Generating AUTHORS
[pbr] AUTHORS complete (0.0s)
running build
running build_py
running egg_info
writing pbr to gphotos_sync.egg-info/pbr.json
writing requirements to gphotos_sync.egg-info/requires.txt
writing gphotos_sync.egg-info/PKG-INFO
writing top-level names to gphotos_sync.egg-info/top_level.txt
writing dependency_links to gphotos_sync.egg-info/dependency_links.txt
[pbr] Processing SOURCES.txt
[pbr] In git context, generating filelist from git
warning: no previously-included files found matching '.gitreview'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
writing manifest file 'gphotos_sync.egg-info/SOURCES.txt'
running build_scripts
running install_lib
creating /Library/Python/2.7/site-packages/test
copying build/lib/test/test_setup.py -> /Library/Python/2.7/site-packages/test
copying build/lib/test/test_database.py -> /Library/Python/2.7/site-packages/test
copying build/lib/test/testDb1.sqlite -> /Library/Python/2.7/site-packages/test
copying build/lib/test/__init__.py -> /Library/Python/2.7/site-packages/test
copying build/lib/test/test_system.py -> /Library/Python/2.7/site-packages/test
copying build/lib/test/test_requests.py -> /Library/Python/2.7/site-packages/test
copying build/lib/test/test_units.py -> /Library/Python/2.7/site-packages/test
creating /Library/Python/2.7/site-packages/test/test_credentials
copying build/lib/test/test_credentials/client_secret.json -> /Library/Python/2.7/site-packages/test/test_credentials
copying build/lib/test/test_credentials/.gphotos.token -> /Library/Python/2.7/site-packages/test/test_credentials
creating /Library/Python/2.7/site-packages/gphotos
copying build/lib/gphotos/DbRow.py -> /Library/Python/2.7/site-packages/gphotos
copying build/lib/gphotos/LocalData.py -> /Library/Python/2.7/site-packages/gphotos
copying build/lib/gphotos/DatabaseMedia.py -> /Library/Python/2.7/site-packages/gphotos
copying build/lib/gphotos/GoogleAlbumsSync.py -> /Library/Python/2.7/site-packages/gphotos
copying build/lib/gphotos/authorize.py -> /Library/Python/2.7/site-packages/gphotos
copying build/lib/gphotos/BadIds.py -> /Library/Python/2.7/site-packages/gphotos
copying build/lib/gphotos/__init__.py -> /Library/Python/2.7/site-packages/gphotos
copying build/lib/gphotos/BaseMedia.py -> /Library/Python/2.7/site-packages/gphotos
copying build/lib/gphotos/GooglePhotosDownload.py -> /Library/Python/2.7/site-packages/gphotos
copying build/lib/gphotos/Utils.py -> /Library/Python/2.7/site-packages/gphotos
copying build/lib/gphotos/GoogleAlbumMedia.py -> /Library/Python/2.7/site-packages/gphotos
copying build/lib/gphotos/GooglePhotosIndex.py -> /Library/Python/2.7/site-packages/gphotos
copying build/lib/gphotos/Main.py -> /Library/Python/2.7/site-packages/gphotos
copying build/lib/gphotos/GooglePhotosMedia.py -> /Library/Python/2.7/site-packages/gphotos
copying build/lib/gphotos/restclient.py -> /Library/Python/2.7/site-packages/gphotos
creating /Library/Python/2.7/site-packages/gphotos/sql
copying build/lib/gphotos/sql/gphotos_create.sql -> /Library/Python/2.7/site-packages/gphotos/sql
byte-compiling /Library/Python/2.7/site-packages/test/test_setup.py to test_setup.pyc
byte-compiling /Library/Python/2.7/site-packages/test/test_database.py to test_database.pyc
byte-compiling /Library/Python/2.7/site-packages/test/__init__.py to __init__.pyc
byte-compiling /Library/Python/2.7/site-packages/test/test_system.py to test_system.pyc
byte-compiling /Library/Python/2.7/site-packages/test/test_requests.py to test_requests.pyc
byte-compiling /Library/Python/2.7/site-packages/test/test_units.py to test_units.pyc
byte-compiling /Library/Python/2.7/site-packages/gphotos/DbRow.py to DbRow.pyc
  File "/Library/Python/2.7/site-packages/gphotos/DbRow.py", line 35
    cols_def: ClassVar[Mapping[str, Type]] = None
            ^
SyntaxError: invalid syntax

byte-compiling /Library/Python/2.7/site-packages/gphotos/LocalData.py to LocalData.pyc
  File "/Library/Python/2.7/site-packages/gphotos/LocalData.py", line 17
    DB_FILE_NAME: str = 'gphotos.sqlite'
                ^
SyntaxError: invalid syntax

byte-compiling /Library/Python/2.7/site-packages/gphotos/DatabaseMedia.py to DatabaseMedia.pyc
  File "/Library/Python/2.7/site-packages/gphotos/DatabaseMedia.py", line 33
    def __init__(self, row: LocalData.SyncRow):
                          ^
SyntaxError: invalid syntax

byte-compiling /Library/Python/2.7/site-packages/gphotos/GoogleAlbumsSync.py to GoogleAlbumsSync.pyc
  File "/Library/Python/2.7/site-packages/gphotos/GoogleAlbumsSync.py", line 22
    def __init__(self, api: RestClient, root_folder: str, db: LocalData):
                          ^
SyntaxError: invalid syntax

byte-compiling /Library/Python/2.7/site-packages/gphotos/authorize.py to authorize.pyc
  File "/Library/Python/2.7/site-packages/gphotos/authorize.py", line 20
    def __init__(self, scope: List[str], token_file: str, secrets_file: str):
                            ^
SyntaxError: invalid syntax

byte-compiling /Library/Python/2.7/site-packages/gphotos/BadIds.py to BadIds.pyc
  File "/Library/Python/2.7/site-packages/gphotos/BadIds.py", line 15
    path: str
        ^
SyntaxError: invalid syntax

byte-compiling /Library/Python/2.7/site-packages/gphotos/__init__.py to __init__.pyc
byte-compiling /Library/Python/2.7/site-packages/gphotos/BaseMedia.py to BaseMedia.pyc
  File "/Library/Python/2.7/site-packages/gphotos/BaseMedia.py", line 26
    def validate_encoding(self, s: str) -> str:
                                 ^
SyntaxError: invalid syntax

byte-compiling /Library/Python/2.7/site-packages/gphotos/GooglePhotosDownload.py to GooglePhotosDownload.pyc
  File "/Library/Python/2.7/site-packages/gphotos/GooglePhotosDownload.py", line 30
    PAGE_SIZE: int = 100
             ^
SyntaxError: invalid syntax

byte-compiling /Library/Python/2.7/site-packages/gphotos/Utils.py to Utils.pyc
  File "/Library/Python/2.7/site-packages/gphotos/Utils.py", line 18
    def safe_str_time(date_time: datetime, date_format: str) -> str:
                               ^
SyntaxError: invalid syntax

byte-compiling /Library/Python/2.7/site-packages/gphotos/GoogleAlbumMedia.py to GoogleAlbumMedia.pyc
byte-compiling /Library/Python/2.7/site-packages/gphotos/GooglePhotosIndex.py to GooglePhotosIndex.pyc
  File "/Library/Python/2.7/site-packages/gphotos/GooglePhotosIndex.py", line 19
    def __init__(self, api: RestClient, root_folder: str, db: LocalData):
                          ^
SyntaxError: invalid syntax

byte-compiling /Library/Python/2.7/site-packages/gphotos/Main.py to Main.pyc
  File "/Library/Python/2.7/site-packages/gphotos/Main.py", line 27
    self.data_store: LocalData = None
                   ^
SyntaxError: invalid syntax

byte-compiling /Library/Python/2.7/site-packages/gphotos/GooglePhotosMedia.py to GooglePhotosMedia.pyc
  File "/Library/Python/2.7/site-packages/gphotos/GooglePhotosMedia.py", line 15
    self.__media_json: JSONType = media_json
                     ^
SyntaxError: invalid syntax

byte-compiling /Library/Python/2.7/site-packages/gphotos/restclient.py to restclient.pyc
  File "/Library/Python/2.7/site-packages/gphotos/restclient.py", line 27
    def __init__(self, api_url: str, auth_session: Session):
                              ^
SyntaxError: invalid syntax

running install_egg_info
Copying gphotos_sync.egg-info to /Library/Python/2.7/site-packages/gphotos_sync-2.1.1.dev15-py2.7.egg-info
running install_scripts
copying build/scripts-2.7/gphotos-sync -> /usr/local/bin
changing mode of /usr/local/bin/gphotos-sync to 755
gomachan:gphotos-sync gomachan$

**Comment by gilesknap** [comment]
OK I see the issue here. I'm afraid this is a python 3.6 or greater project. You appear to be picking up python 2.7

**Comment by gilesknap** [comment]
I guess my setup.py should specify that somehow, but you probably need to install python 3.6.

**Comment by gosugimoto** [comment]
So I've tried doing this:
https://www.digitalocean.com/community/tutorials/how-to-install-python-3-and-set-up-a-local-programming-environment-on-macos

And it looks like it's installed python 3, but no matter how I check in terminal, it says python 2.7...

**Comment by gilesknap** [comment]
My guess is that you need to execute 'python3' instead of 'python', did you try that?

**Comment by gilesknap** [comment]
By the way, you are the first user on Mac so we may have some things to sort out!

**Comment by gosugimoto** [comment]
hmm, doesn't seem to be working and doesn't look like i can just overwrite
the base mac python environment, or whatever it is called from 2.7.10

**Comment by gilesknap** [comment]
I'm not going to be much help since I don't have a mac to try things on. This https://wsvincent.com/install-python3-mac/ implies that it should be pretty easy and that you do need to run 'python3'.

**Comment by gosugimoto** [comment]
hmmm getting closer perhaps...

*gomachan:gphotos-sync gomachan$ gphotos-sync*

*Traceback (most recent call last):*

*  File
"/Library/Frameworks/Python.framework/Versions/3.7/bin/gphotos-sync", line
3, in <module>*

*    from gphotos.Main import GooglePhotosSyncMain*

*  File
"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gphotos/Main.py",
line 9, in <module>*

*    from appdirs import AppDirs*

*ModuleNotFoundError: No module named 'appdirs'*



and then for the help command I get

*gomachan:gphotos-sync gomachan$ gphotos-sync --help*

*Traceback (most recent call last):*

*  File
"/Library/Frameworks/Python.framework/Versions/3.7/bin/gphotos-sync", line
3, in <module>*

*    from gphotos.Main import GooglePhotosSyncMain*

*  File
"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gphotos/Main.py",
line 9, in <module>*

*    from appdirs import AppDirs*

*ModuleNotFoundError: No module named 'appdirs'*

*gomachan:gphotos-sync gomachan$ *

**Comment by gilesknap** [comment]
OK, so now you are missing a dependency (AppDirs). If you had successfully done the install, then it should have installed all the dependencies. Did you manage to get setup.py install to run?

If you have not managed to run setup.py, you may be able to work around it with:
pip install -r requirements.txt

**Comment by gilesknap** [comment]
UPDATE: I've just been testing the installer and I get the same error as you.
Thus the installer is broken and I'm now investigating.
I do all my testing in a virtual environment and everything works fine there if you run 'pip install requirements.txt'. If you know how to use virtualenv then you can try this, but I should get  fix reasonably soon.

**Comment by gosugimoto** [comment]
Great. I've tried installing just applied, I feel like I'm typing in loads
of terminal commands, not knowing the result... 😅

**Comment by gilesknap** [comment]
This might take a little longer. Python package distribution has a little more in it than I realized and I'm switching to using pipenv at the same time. (this project is my testing ground for latest best practice and I've not touched the installer since the original fork).

Please hang on for a day or two.

**Comment by gilesknap** [comment]
OK, please try the latest release 2.7. I hope I have fixed installation issues.

If you have pip installed you can now get it direct from PyPi with no source code required by running
`sudo pip install gphotos-sync`.

Let me know if that works for you and if not see the new instructions in ReadMe.rst.

There is a new feature that might come in handy for your use case. Which is that it is now possible to compare the library contents with a local filesystem folder.

**Comment by gosugimoto** [comment]
Great, I'll give it a go on the wknd. thanks!

**Comment by gilesknap** [comment]
Hi, if you get a chance to try this out then I'd be very interested to know if you can install onto mac using pip. Thanks!

**Comment by gilesknap** [comment]
closing this since we are now discussing your install issues in #70.
Cheers.
