### ISSUE TITLE
Unable to sync or Create new backup

### ISSUE THREAD

**Issue by zackfravel** [gilesknap/gphotos-sync#503]
I'm was experiencing an expired token error and found newer documentation related to fixing that, along with the steps in the following ticket: [https://github.com/gilesknap/gphotos-sync/issues/290](url) and have tried the solutions described, currently when I run the following command I get no output and the terminal just hangs (I'm using Docker, on an Unraid Machine):

docker exec GooglePhotosSync gphotos-sync /storage --new-token

Was working fine for 3+ years on a cronjob and just realized it stopped working a few months ago. Anyone else run into this where --new-token doesn't generate a new link? I re-installed the docker container, created a new empty root folder, and have redone the credential initialization process. Anything else to try?

**Comment by gilesknap** [comment]
Hi @zackfravel 

I'll have a go at regenerating my token and see if I'm seeing the issue. Will look at this later today.

**Comment by zackfravel** [comment]
Wanted to reply here again and say the issue has since resolved! Not sure what changed but I'm good to go now

**Comment by gilesknap** [comment]
Thanks for letting me know.
