### ISSUE TITLE
Possible parameters for docker

### ISSUE THREAD

**Issue by Feriman22** [gilesknap/gphotos-sync#508]
I'd like to add the [--do-delete option](https://github.com/gilesknap/gphotos-sync/issues/427) to the docker run command, but how can I do that?

Also, what other parameters are available for Docker?

Thanks!

**Comment by gilesknap** [comment]
Hi @Feriman22 

When you run via docker you still have the same set of arguments that you can add after `gphotos-sync`.

**Comment by Feriman22** [comment]
Hi @gilesknap,
I have tried like this:

`docker run --rm -v /mnt/Docker/googlephotossync/config:/config -v /mnt/Shared/GooglePhotosMirror:/storage -it ghcr.io/gilesknap/gphotos-sync /storage --do-delete`

However, it won't delete files locally that have already been deleted from Google Photos. Output:

```
08-29 07:25:01 WARNING  gphotos-sync 3.2.6.dev2+g89d9880 2024-08-29 07:25:01.684438
08-29 07:25:01 WARNING  Indexing Google Photos Files ...
08-29 07:25:02 WARNING  indexed 0 items
08-29 07:25:02 WARNING  Downloading Photos ...
08-29 07:25:02 WARNING  Downloaded 0 Items, Failed 0, Already Downloaded 11910
08-29 07:25:02 WARNING  Finding and removing deleted media ...
08-29 07:25:05 WARNING  Done.
```

**Comment by gilesknap** [comment]
You need --rescan as well as --do-delete otherwise it only scans for changes since the last scan.

**Comment by gilesknap** [comment]
but use do-delete with caution - there is another open issue that says this behaves badly.

**Comment by Feriman22** [comment]
Thanks! I tried with --rescan and --do-delete together, but local files are still there, however I already deleted them from Google Photos. Shall I empty the trash can as well?

**Comment by gilesknap** [comment]
Oh, sorry I gave you the wrong option - you need --flush-index.

Note that it says this if you try `gphotos-sync --help`

**Comment by Feriman22** [comment]
Thanks, it works with these three parameters together:

 _--rescan --flush-index --do-delete_
