### ISSUE TITLE
Sync only a particular album (Feature) ?

### ISSUE THREAD

**Issue by neilmahaseth** [gilesknap/gphotos-sync#69]
Hi is it possible to only download photos from a particular album skipping all the remaining photos ?

**Comment by gilesknap** [comment]
I had this feature in the earlier version based on Picassa API. It is not yet implemented in the current version.

I could very easily add it. I'll take a look this week.

**Comment by neilmahaseth** [comment]
Oh okay thank you. I am using the Google photos sharing and auto add using face recognition feature to create an auto updated family album. It would nice to have a backup of this particular album on my local machine.

**Comment by gilesknap** [comment]
Hi, I've implemented this in branch 'feature' but not had time for extensive testing today. Please give it a try and I'll release if all is good.

**Comment by gilesknap** [comment]
this feature is now in release 2.8.6
