### ISSUE TITLE
Extra files downloaded into picasa folder

### ISSUE THREAD

**Issue by gilesknap** [gilesknap/gphotos-sync#7]
After syncing 100,000 files I checked against the files synced by Google on Windows, all good.
2nd Sync indexed as expected but brought down about 100 extra files into the Picasa folders, these files are also in drive and should not have been copied.
Looking in the database these files are correctly matched against their drive counterparts so the indexing worked ok.
3rd, 4th, 5th sync worked as expected and verified correctly.

(giles see FirstSyncLogs.txt for log of this behaviour)

**Comment by pierrerigal** [comment]
Indexing still running on my side, but I think there is a problem with picasa part. Not sure it's the same issue that yours.

It's indexing again all my photos (not only the animations, gif or creations). 

Drive has indexed 41001 photos, picasa tell me it will index 41334 photos, most of them are the same. 

Will they be downloaded 2 times ?

Simple grep on a filename in complete log file : 

```
(gphotos-sync) pi@raspberrypi:~/pyenvs/gphotos-sync $ cat var/gphotos.log | grep '20160528_153627.jpg'
gphotos.drive: Added 522 /media/toshiba/drive/Google Photos/2016/20160528_153627.jpg
gphotos.picasa: Added 8658 /media/toshiba/picasa/2016/05/20160528_153627.jpg
```

**Comment by gilesknap** [comment]
No they won't download twice. Picasa is being indexed to discover album content. Picasa files will only get downloaded if no matching file is found in drive. 
In my experience this works fine on the first sync but I have a 100 or so troublesome Giles that get downloaded into Picasa folder on second sync. According to the dB the drive match happened ok but they still downloaded. This is a minor irritation at present done it just wastes 100 JPGs of disc. I'm still investigating the cause.

If you don't want album links then you can sort things up considerably by using --skip-picasa.

In addition you are ok to cancel a running sync and the next one will pick up from where it was. (Kill might be an issue but ctrl C is certainly ok)

**Comment by gilesknap** [comment]
Some typos in prev comment and no option to exit from mobile!

I think your question points to the need for me to change the log messages since it does make it look like a 2nd download will happen.

**Comment by gilesknap** [comment]
Edit from mobile, I mean!

**Comment by gilesknap** [comment]
The matching algorithm has been improved.
Log messages have been cleaned up.
Testing has shown that the issue was in fact due to some anomalies in my photo store caused by googles backup and sync (and possibly running it in a saved state VirtualBox)
All good in cefcef3972894f5edee6ade3d85180c5a9154757
