### ISSUE TITLE
can't run

### ISSUE THREAD

**Issue by gosugimoto** [gilesknap/gphotos-sync#70]
the sudo pip install seemed to work on my mac, but it says requirements already met.  however when running, i get

gomachan:gphotos-sync gomachan$ gphotos-sync backup
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/gphotos-sync", line 3, in <module>
    from gphotos.Main import GooglePhotosSyncMain
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gphotos/Main.py", line 9, in <module>
    from appdirs import AppDirs
ModuleNotFoundError: No module named 'appdirs'

**Comment by gilesknap** [comment]
Hi,

It sounds like the install failed to include dependencies. You could try
'sudo pip uninstall' and retry. I'm away for the next 10 days, will
investigate further on my return.

**Comment by gosugimoto** [comment]
I get this:

DEPRECATION: Python 2.7 will reach the end of its life on January 1st,
2020. Please upgrade your Python as Python 2.7 won't be maintained after
that date. A future version of pip will drop support for Python 2.7.

The directory '/Users/gomachan/Library/Caches/pip/http' or its parent
directory is not owned by the current user and the cache has been disabled.
Please check the permissions and owner of that directory. If executing pip
with sudo, you may want sudo's -H flag.

You must give at least one requirement to uninstall (see "pip help
uninstall")
--
iamgo.net

**Comment by gilesknap** [comment]
Ok please try these.
1. Make sure you have the latest version of gphotos. It should require
python 3.7
2. Make sure you have python 3.7 and associated pip.
3. You may need to run pip3 instead of pip.

Ill try to find a Mac to try this out on when I get back so I can give you
more informed advice.

**Comment by gilesknap** [comment]
Hi, did you get anywhere with this? I might need to borrow a Mac to help you with this issue.

**Comment by gilesknap** [comment]
has anyone successfully used gphotos-sync on Mac and can help with this ticket? Thanks.

**Comment by gilesknap** [comment]
Not had any response on this for a while. 
Closing for now. Please reopen if you still have an issue. Tx.

**Comment by gosugimoto** [comment]
So as I saw lots of updates to this since last run, I'm trying fresh again, but coming across:

`me:gphotos-sync-master me$ gphotos-sync
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/gphotos-sync", line 3, in <module>
    from gphotos.Main import GooglePhotosSyncMain
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gphotos/Main.py", line 9, in <module>
    from appdirs import AppDirs
ModuleNotFoundError: No module named 'appdirs'
me:gphotos-sync-master me$ 
`

**Comment by gilesknap** [comment]
Hi again. I dont have experience of running python on a Mac but I have now got tests running on a mac vm for travis builds. 

I think you need to get homebrew installed if you do not already have it, then:

- cd to the gphotos directory
- brew cleanup
- brew update
- brew upgrade python3
- python3 -m pip install virtualenv
- virtualenv .venv -p python3
- source .venv/bin/activate
 - pip install .
- python3 ./gphotos-sync --help

**Comment by gosugimoto** [comment]
looks like that did a whole lot of something :)

now at:


(.venv) me:gphotos-sync-master gomachan$ gphotos-sync

usage: gphotos-sync [-h] [--album ALBUM] [--logfile LOGFILE]

                    [--compare-folder COMPARE_FOLDER] [--favourites-only]

                    [--flush-index] [--rescan] [--retry-download]

                    [--skip-video] [--skip-shared-albums]

                    [--start-date START_DATE] [--end-date END_DATE]

                    [--log-level LOG_LEVEL] [--db-path DB_PATH]

                    [--albums-path ALBUMS_PATH] [--photos-path PHOTOS_PATH]

                    [--use-flat-path] [--new-token] [--index-only]

                    [--skip-index] [--do-delete] [--skip-files]

                    [--skip-albums] [--get-locations] [--use-hardlinks]

                    [--no-album-index]

                    root_folder

gphotos-sync: error: the following arguments are required: root_folder

(.venv) me:gphotos-sync-master gomachan$


--
iamgo.net

**Comment by gilesknap** [comment]
OK, that looks good. You need to specify the root folder where you would
like your photos backed up to and then it should work.

But you also need to set up the application token for your copy of gphotos
if you have not already done so. See
https://www.linuxuprising.com/2019/06/how-to-backup-google-photos-to-your.html
if you don't find my README adequate.

Cheers, giles.

**Comment by gosugimoto** [comment]
Ok, I think it's working!! it says indexing google photos files...
but i guess i need to activate this .venv thing prior to running everytime?

--
iamgo.net

**Comment by gilesknap** [comment]
Hi yes you do need to activate venv. Or if you could work out how to use
pipenv then that will do it for you.

**Comment by gosugimoto** [comment]
Great.  So I just run the

source .venv/bin/activate

command and I can execute.  Seems easy enough to add to an applescript or
something similar as an automated thing.  I think from here, it's slightly
redundant, but:

   - I'll maintain this downloaded folder as "backup"
   - Copy over to the main catalogue of photos to merge with camera photos
   (essentially enabling my mobile + camera library)
   - I just need to get this copy process to be automatic to just drop into
   the respective folders where my camera shots live

Thanks so much for your amazing help, this is just fantastic!!
--
iamgo.net
