### ISSUE TITLE
Download Just Favorites

### ISSUE THREAD

**Issue by stdavis** [gilesknap/gphotos-sync#74]
Has anyone ever tried to use this project to download just your favorites? I tried to pass `Favorites` as an album name but it doesn't look like it's the same as a normal album. Perhaps the Google Photos API does not support interacting with favorites yet? I've searched their docs and haven't been able to find anything. Any ideas? I'd be happy to submit a PR if someone can point me in the right direction.

**Comment by gilesknap** [comment]
I've not seen anything in the API for this and there is not an album that
represents Favourites.

You could post a feature request with Google at
https://issuetracker.google.com/issues/new?component=385336&template=1083979

I think we would need a special album to represent Favourites. An
alternative would be to add favourite flag to the items metadata but that
would require scanning the whole library to find Favourites.

Either solution would allow me to update gphotos to provide what you want.

**Comment by stdavis** [comment]
https://issuetracker.google.com/issues/134309059

**Comment by gilesknap** [comment]
Starred :-)

**Comment by gilesknap** [comment]
Apparently, this has been added. See https://issuetracker.google.com/issues/110188560
I can't find the documentation yet but it might not yet be public.

**Comment by stdavis** [comment]
https://developers.google.com/photos/library/support/release-notes
https://developers.google.com/photos/library/reference/rest/v1/mediaItems/search#FeatureFilter

**Comment by gilesknap** [comment]
Production links are here:
https://developers.google.com/photos/library/reference/rest/v1/mediaItems/search#FeatureFilter
https://developers.google.com/photos/library/support/release-notes

**Comment by gilesknap** [comment]
Thanks, Scott I think we cross posted. I'll take a look at implementing this in gphotos soon. Right now I'm investigating some changes that seem to have happened to my library since my last full sync.

**Comment by gilesknap** [comment]
I have added --favourites-only (English spelling :-) )

Currently, it is in the feature branch if you would like to try. It will be released soon.

**Comment by gilesknap** [comment]
This is now released, see https://github.com/gilesknap/gphotos-sync/releases/tag/2.9

**Comment by stdavis** [comment]
I finally got around to trying this out and it worked like a charm. Thank you very much! This is going to be super useful to me.
