### ISSUE TITLE
Python 3.7 requirement

### ISSUE THREAD

**Issue by kcgthb** [gilesknap/gphotos-sync#77]
Hi!

Thanks a lot for this great project, this is really bridging a huge gap in functionality for Google Photos.

I see that the latest versions are moving to Python 3.7 as a hard requirement, and this could prove challenging for many users, as Python 3.7 has not yet reached the universally available status of earlier versions. For instance, running `gphotos-sync` on Synology NAS, where it could prove extremely useful, is not currently possible, as the highest Python available there is 3.6.

Is there a way to relax the requirement on 3.7, and keep using 3.6 for the time being, until 3.7 reaches more adoption on more platforms?

Thanks!

**Comment by gilesknap** [comment]
Hi Kilian,

I'll take a look and see if this is an easy change.

I use this project to experiment with the latest innovations and I think I
have used a 3.7 feature.

However, it is probably not to much trouble to downgrade to 3.6 so will let
you know.

Cheers.
giles

**Comment by kcgthb** [comment]
Excellent, thanks for considering it!

**Comment by gilesknap** [comment]
This is harder than expected. disutils is not compatible between 3.6 and 3.7 which means I can't create virtualenvs for 3.6 on my distribution.

Also, Pipenv restricts to a hard version.

I shall continue to investigate.

**Comment by gilesknap** [comment]
We now have all tests passing on Python3.6.

See here for details:- https://github.com/gilesknap/gphotos-sync/blob/master/etc/Python3.6.rst

**Comment by gilesknap** [comment]
I've just realised that installing from Pypi does not use the project Pipfile.
Hence I think the default install instructions should work for you. 
If this is the case then let me know and I'll remove the Python3.6 specific instructions.

**Comment by kcgthb** [comment]
Wow, that was fast, thanks a lot!

`pip install --upgrade` worked fine to install `gphotos-sync` 2.9 with Python 3.6.8, so the installation was very smooth.

Thank you very much for that change, very much appreciated.
