### ISSUE TITLE
Option to not sync albums/photos that others have shared with me

### ISSUE THREAD

**Issue by mrmattwilkins** [gilesknap/gphotos-sync#83]
Hi,
If I am understanding things correctly it appears that all the albums that other people have shared with me are being downloaded.  Would it be possible to have an option so they aren't downloaded?  What I would like is to only sync those photos and albums that I actually own and have uploaded.
Thanks
Matt

**Comment by gilesknap** [comment]
Hi Matt,

You understand correctly. I think it is sensible to have an option to
suppress this and it's not hard to do.

I will add the option in the next week or so.

Cheers,
giles.

**Comment by mrmattwilkins** [comment]
Awesome, thanks Giles

Matt

**Comment by gilesknap** [comment]
hmmm.
I had a go this evening and although there are separate sharedAlbums.list and albums.list APIs, I seemed to get shared albums when using just the latter. This is odd because I recall adding the sharedAlbums.list feature and seeing it work. Perhaps my test account shared album has different status because it is a linked account?

Investigating further.

**Comment by gilesknap** [comment]
OK, got it.

If you look at a shared album and select 'Show in Albums' then that becomes one of your albums listed by albums.list API. Unfortunately, this is still true if you then use 'hide from albums'.

**Comment by mrmattwilkins** [comment]
OK, fortunately for me I haven't clicked that 'Show in Albums'!

To get the behaviour I'm after would just commenting out line 236
in GoogleAlbumsSync.py do the trick?  In other words just getting rid of
       self.index_albums_type(self._api.sharedAlbums.list.execute,
                               'sharedAlbums', "Shared (titled) Albums",
                               False, True)

I did a bit of debugging, printing out the album.description, and it looks
like that line is what indexes all the sharedAlbums, so if that line wasn't
called, would that mean the photos wouldn't be synced?

Cheers

Matt

**Comment by gilesknap** [comment]
Yes, your fix would work. But a configurable fix is nearly done. :-)

**Comment by mrmattwilkins** [comment]
Cool, yes, an configurable option would be much better.  I will wait  :-)
Thank you!

**Comment by gilesknap** [comment]
If you pull the latest master you should now see an option --skip-shared-albums
Please give it a try.
Thanks.

**Comment by mrmattwilkins** [comment]
Awesome, worked fine.  Just a couple tiny things in the help screen:
   --skip-shared-albums  skip albums that only appearing in 'Sharing'
should be
  --skip-shared-albums  skip albums that only appear in 'Sharing'

And the --do-delete option shouldn't refer to --flush-db,
rather  --flush-index (I think, that is what worked for me to get the
delete anyway!)

Thanks very much!  Nice to get this sorted, I expect many more people will
be wanting to use gphotos-sync since google dropping the sync from photos
into drive.

Matt

**Comment by gilesknap** [comment]
Thanks, I have fixed the typos. Closing this issue.
