### ISSUE TITLE
Create a robust duplicates handling mechanism

### ISSUE THREAD

**Issue by gilesknap** [gilesknap/gphotos-sync#86]
Currently, if a file shares its filename with another in the same folder it gets a suffix (n) where n starts at 2 and increments as further duplicates are found. The first file in the set of duplicates retains its original filename (but is given duplicate number 1 in the index).

This approach matches Google's official sync tools (except that I can't guarantee the same order of  numbers - I don't know what their ordering is)

The order of duplicate suffix is dependent on the order that files are returned by the API.

This approach is not entirely robust, especially if Google does not guarantee consistent ordering of the results of a search (see  https://docs.google.com/document/d/1hK_GDLUwP7PpD1VmDbDsYLyTfbZGv2C-JCihezYhiLY/edit?usp=sharing). Also, it would not work if I wanted to restructure the folder hierarchy of the local copies like in #80.

Also, note that this scheme caused all sorts of headaches before I even developed gphotos-sync. I used to use InSync to backup my Google Drive connected Photos but that had issues and ended up deleting lots of my duplicates from the Library itself.

I would like to develop a new approach to making filenames unique. With the following features:

1. filenames are unique across the entire library
2. suffixes are still relatively short
3. the suffix can be deterministically derived from some immutable attribute of the media FILE (not the metadata supplied by Google APIs)
4. this approach should not slow down Gphotos too much (but assume it needs to look inside any files with non-unique names)
5. It is OK to flush the index DB and the re-index will re-match the same files to their remote counterparts

Point 3 is going to be particularly hard - the linked document above describes how the content of files that Google delivers via the API is slightly 'fluid' both in the image data and metadata.

**Comment by gilesknap** [comment]
An easy answer to the 'immutable attribute' has occurred to me. The remote ID is the one thing that always uniquely identifies a particular resource in the library. If that were to change then all bets are off anyway.

Even better, I don't need to look in the files and already record this value in the DB so could run a conversion on the local copy offline.

**Comment by gilesknap** [comment]
I will need to provide a conversion operation to rename duplicate files in an existing backup. This will be contentious since it will change your existing library backup. Thus I should support the old scheme as an option.

This requires careful management of the DB upgrade and file store upgrade for existing users.

**Comment by ScottESanDiego** [comment]
I would think it's probably acceptable to just make a new release and have a flag day - knowing any sync with the new release will be a total resync and a new structure.  Feels like "upgrading" is more trouble than it's worth given the relative infancy of this project.  (Just MHO, but I've only got 90GB of photos, so it's not horrible to "start over".)

**Comment by gilesknap** [comment]
Yes, that approach would work for me. I have 200GB of photos but only takes a few hours to download.

Also, the complexity of restructuring would be error-prone and hard to test.

I think I'll take your suggestion.

**Comment by richard-hunt** [comment]
Quick question - I'm new to gphotos-sync (as a result of Google's changes to Photos/Drive integration this month) and am getting failures during initial sync whenever I have two photos with the same filename in the same month (in this case DSC_0354.JPG):

FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'D:\\Google Photos\\photos\\2007\\04\\tmp2ypunqep' -> 'D:\\Google Photos\\photos\\2007\\04\\DSC_0354.JPG'

Is this expected behaviour that you're looking to address with this issue or is there something else going on?  I can provide a full trace if it helps.

**Comment by gilesknap** [comment]
This might be an issue with files that differ only in case on Windows. E.g.
pic1.jpg and pic1.JPG.

If so then it is fixed in the latest version on master branch. It is not
yet released to pypi.

If you are already using the master branch version then please send your
log file to gilesknap@gmail.com.

Thanks.

**Comment by richard-hunt** [comment]
Yep, that looks exactly the issue - my two files are named DSC_0354.JPG and DSC_0354.jpg.  I'll download the master branch version and give it a whirl.

Awesome tool by the way, thanks for making it available!

**Comment by jonathancrawford** [comment]
Have you considered integrating something like http://www.phash.org/ (see, e.g.,  https://github.com/philipbl/duplicate-images) to find and remove dupes?  Or if you want find only true binary duplicates could you use a SHA-256 hash.

The system could store the phash of each indexed image after download.  If a new download matches the phash, you can do a symbolic link for the new image and/or (configurable?) skip the download entirely and mark it as a skipped duplicate.

**Comment by gilesknap** [comment]
Hi Jonathan. At present, I try to keep gphotos-sync as passive as possible. It is only intended to make as good a copy as possible of the google photos library. Google photos itself removes duplicates based on the unique ID in EXIF. It does then have multiple links to the same file and gphotos-sync probably should use symlinks to represent these as you suggest.

The duplicates in question in this issue #86 are file name duplicates. When we reconstruct the library in a local filesystem, the choice of how we split into folders affects when file names will clash. I use the original filename of the photo in the local copy. For modern cameras, this is rarely an issue since they use unique names based on date. But for older cameras and google generated content it often is.

Currently, I use the same naming strategy as the official Google backup and sync. I add (2) to the name of the first clashing filename and (3) etc. for further clashes. This approach relies heavily on the order in which items are listed by the API (which can change). It is also very clumsy for the case where we change the folder hierarchy as requested in #80. 

The current approach has occasionally caused a few issues with old filenames on re-synching my own library.

**Comment by vdevan** [comment]
Hi: Let me congratulate you on a great product first.
I had no issues in downloading my photos from google. However when I do this with my son's account (he lives in US while I live in Australia) I am able to download only 20 photos before the program exits. I have provided the errors. Currently I am running the script in a bash loop. FYI I run this in raspberry pi model 3B with Debian buster - lite 
09-12 10:53:00 WARNING  Indexing Google Photos Files ... 
09-12 10:53:02 WARNING  indexed 0 items 
09-12 10:53:02 WARNING  Downloading Photos ... 
09-12 10:53:07 ERROR    FAILURE 1 downloading photos/2018/05/IMG-20180506-WA0000.jpg - [Errno 1] Operation not permitted 
09-12 10:53:15 ERROR    FAILURE 2 downloading photos/2018/05/IMG_20180506_201843488.jpg - [Errno 1] Operation not permitted 
09-12 10:53:16 ERROR    
Process failed. 
Traceback (most recent call last):
  File "/snap/gphotos-sync/234/lib/python3.6/site-packages/gphotos/GooglePhotosDownload.py", line 151, in download_photo_media
    self.download_batch(batch)
  File "/snap/gphotos-sync/234/lib/python3.6/site-packages/gphotos/GooglePhotosDownload.py", line 192, in download_batch
    self.download_file(media_item, media_item_json)
  File "/snap/gphotos-sync/234/lib/python3.6/site-packages/gphotos/GooglePhotosDownload.py", line 223, in download_file
    self.do_download_complete(done_list)
  File "/snap/gphotos-sync/234/lib/python3.6/site-packages/gphotos/GooglePhotosDownload.py", line 327, in do_download_complete
    raise e
  File "/snap/gphotos-sync/234/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/snap/gphotos-sync/234/lib/python3.6/site-packages/gphotos/GooglePhotosDownload.py", line 267, in do_download_file
    create_date.timestamp(),
PermissionError: [Errno 1] Operation not permitted

**Comment by gilesknap** [comment]
Hi.

This is a permission error on the folder you are trying to write to.

There are special permissions on the snap package which allow it to write
to folders outside of the snap filesystem. However early versions did not
have this feature.

Please check the file permissions on the folder you are writing to and also
that you are using the latest snap package.

**Comment by gilesknap** [comment]
On reflection it appears not to be write permission but that we are trying to set a date in the file which is too early and illegal on your file system.

Perhaps the photos on your son's library go back on time further than yours?

The code is supposed to check for this and handle it correctly. 

Do you know what filesystem your target folder is?

**Comment by vdevan** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:Latha;
	panose-1:2 11 6 4 2 2 2 2 2 4;}
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:72.0pt 72.0pt 72.0pt 72.0pt;}
div.WordSection1
	{page:WordSection1;}

**Comment by gilesknap** [comment]
Closing as won't fix, see closing comment #80
