### ISSUE TITLE
new install, cant authenticate

### ISSUE THREAD

**Issue by dirtbag** [gilesknap/gphotos-sync#87]
installed this via pip on my arch linux and when I run it, I get 

[jason@archlinux ~]$ gphotos-sync  --new-token  googlephotos 
missing or bad secrets file: /home/jason/.config/gphotos-sync/client_secret.json
07-20 16:10:10 
Process failed.
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/gphotos/authorize.py", line 37, in __init__
    with secrets_file.open('r') as stream:
  File "/usr/lib/python3.7/pathlib.py", line 1186, in open
    opener=self._opener)
  File "/usr/lib/python3.7/pathlib.py", line 1039, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/jason/.config/gphotos-sync/client_secret.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/gphotos/Main.py", line 328, in main
    self.setup(args, db_path)
  File "/usr/lib/python3.7/site-packages/gphotos/Main.py", line 191, in setup
    self.auth = Authorize(scope, credentials_file, secret_file)
  File "/usr/lib/python3.7/site-packages/gphotos/authorize.py", line 50, in __init__
    exit(1)
  File "/usr/lib/python3.7/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 1
07-20 16:10:10 Done.
[jason@archlinux ~]$

[jason@archlinux ~]$ python -V
Python 3.7.3

any ideas?

**Comment by gilesknap** [comment]
Hi, this means you have not yet created an application key for your copy of
gphotos.

This is a bit fiddly but only needs to be fine once.

See
https://github.com/gilesknap/gphotos-sync/blob/master/README.rst#install-and-configure

Or you might find the Linux uprising description easier to follow:
https://www.linuxuprising.com/2019/06/how-to-backup-google-photos-to-your.html

**Comment by dirtbag** [comment]
well yeah its supposed to bring up the google webpage the first time I run it for me to authenticate.. but it doesnt, it just dumps that error message

[jason@archlinux ~]$ pipenv run gphotos-sync ~/gphotos-sync
missing or bad secrets file: /home/jason/.config/gphotos-sync/client_secret.json
07-22 18:24:58 
Process failed.
Traceback (most recent call last):
  File "/home/jason/.local/share/virtualenvs/jason-PIdUkb3O/lib/python3.7/site-packages/gphotos/authorize.py", line 37, in __init__
    with secrets_file.open('r') as stream:
  File "/usr/lib64/python3.7/pathlib.py", line 1186, in open
    opener=self._opener)
  File "/usr/lib64/python3.7/pathlib.py", line 1039, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/jason/.config/gphotos-sync/client_secret.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jason/.local/share/virtualenvs/jason-PIdUkb3O/lib/python3.7/site-packages/gphotos/Main.py", line 328, in main
    self.setup(args, db_path)
  File "/home/jason/.local/share/virtualenvs/jason-PIdUkb3O/lib/python3.7/site-packages/gphotos/Main.py", line 191, in setup
    self.auth = Authorize(scope, credentials_file, secret_file)
  File "/home/jason/.local/share/virtualenvs/jason-PIdUkb3O/lib/python3.7/site-packages/gphotos/authorize.py", line 50, in __init__
    exit(1)
  File "/home/jason/.local/share/virtualenvs/jason-PIdUkb3O/lib/python3.7/site.py", line 389, in __call__
    raise SystemExit(code)
SystemExit: 1
07-22 18:24:58 Done.
[jason@archlinux ~]$ file /home/jason/.config/gphotos-sync/client_secret.json
/home/jason/.config/gphotos-sync/client_secret.json: cannot open `/home/jason/.config/gphotos-sync/client_secret.json' (No such file or directory)
[jason@archlinux ~]$

**Comment by gilesknap** [comment]
You will get the google authentication page once you have registered the application to get a secret key.

These are the steps from Linux uprising to get the client secret. Did you perform these steps?

> 1. Create a new Google Cloud project
> 
> Go to https://console.cloud.google.com/cloud-resource-manager and create a new project. 
> 
> For help with this step, see the Google Cloud documentation for creating a project https://cloud.google.com/resource-manager/docs/creating-managing-projects
> 
> 2. Go to https://console.cloud.google.com/apis/library?project=_, select a project, then search for the Photos Library API and enable it for this project.
> 
> The Google Cloud help for enabling APIs can be found here: https://cloud.google.com/apis/docs/enable-disable-apis
> 
> 3. Go to https://console.cloud.google.com/, make sure the correct project is selected from the top dropdown menu, then click on APIs & Services in the sidebar, and finally click Credentials in the sidebar. Create an Create OAuth client ID. When asked to choose the application type, select "Other".
> 
> You can see the complete procedure for setting up OAuth 2.0 with your new project on https://support.google.com/cloud/answer/6158849
> 
> 4. Once the client ID is created, download it as client_secret.json (so rename it, as it will have a longer name) and save it under the application configuration directory:
> 
> ~/Library/Application Support/gphotos-sync/ under Mac OS X
> ~/.config/gphotos-sync/ under Linux
> C:\Users\<username>\AppData\Local\gphotos-sync\gphotos-sync\ under Windows
> 
>

**Comment by dirtbag** [comment]
ooh man.. I saw all that but I was kinda in disbelief that I had to go through all those hoops to get this to work.. Thanks for the info and please accept my apologies for being dense.. ;) 

-db

**Comment by drose12** [comment]
how does someone get past

missing or bad secrets file: /root/.config/gphotos-sync/client_secret.json

when they are using docker? not sure how to get to the app not verified page

Also its referencing /root/.config/gphotos-sync/client_secret when I have

docker run -it --name gphotos-sync -v /Users/Dave/gphotos-sync/storage:/storage -v /Users/Dave/gphotos-sync/config/client_secret.json:/config/client_secret.json:ro gilesknap/gphotos-sync --log-level INFO /storage

**Comment by gilesknap** [comment]
@drose12 i'm not particularly familiar with docker, it was provided by a contributor. But maybe there is a typo in the instructions? I think the command should have a dot before the volume mapping  'config/client_secret'

i.e.

docker run -it --name gphotos-sync -v /Users/Dave/gphotos-sync/storage:/storage -v /Users/Dave/gphotos-sync/config/client_secret.json:/.config/client_secret.json:ro gilesknap/gphotos-sync --log-level INFO /storage

Containers run as root so /root/.config may be the correct location to map to.
