### ISSUE TITLE
File permission

### ISSUE THREAD

**Issue by manny73** [gilesknap/gphotos-sync#92]
Hi, congratulations for this great software. 
When the image are saved, in linux environment the file permission is rw- --- --- .
It's possibile to configure the mask, for the folder too?
For example file: rw- rw- -- and folder: rwx rwx x

Thanks

**Comment by gilesknap** [comment]
Hi, there is currently no option to control the file permissions.

This is a reasonable feature request. I'll add it to the list. 

Does anyone else fancy contributing this feature? (see comments in #79 since this is quite similar\)

**Comment by gilesknap** [comment]
I'm wondering if it makes more sense to use umask in the script from which you launch gphotos-sync?

**Comment by gilesknap** [comment]
Actually, I just tried and that does not work. 

If gphotos-sync honoured umask would that be OK?

**Comment by gilesknap** [comment]
I believe the umask is ignored because tempfile tries to be secure https://docs.python.org/2/library/tempfile.html. So I will have to explicitly set the permissions after download completes.

**Comment by manny73** [comment]
> If gphotos-sync honoured umask would that be OK?

it would be perfect. Thanks.

**Comment by gilesknap** [comment]
this should be fixed in 2.9.2 (on pypi) please give it a go.

Now umask determines the permissions on downloaded files (BUT this only works on Linux)

**Comment by manny73** [comment]
Hi Giles, has working correctly!
Great job.
