### ISSUE TITLE
Shared libraries

### ISSUE THREAD

**Issue by vitobotta** [gilesknap/gphotos-sync#93]
Hi, I tried gphotos-sync today to back up my Google Photos library, and it works well but it doesn't seem to download the picture of a library shared with me (my wife is sharing her entire library and in the Photos settings of my account I choose to add her collection to my own library). I would like a full backup of both libraries. How can I do this? Thanks!

**Comment by gilesknap** [comment]
This is an interesting question. I do not know if the google photos API currently supports this.

I will look into it.

**Comment by vitobotta** [comment]
Thanks, I appreciate :)

**Comment by gilesknap** [comment]
I've had a look in the API docs there is no reference to shared libraries. We could put in a feature request at https://issuetracker.google.com/issues?q=componentid:385336%20status:open. They are not that fast at responding but it's worth a try.

In the meantime, you could sync both libraries side by side. If you invoke gphotos-sync twice with two different root folders then it will ask for google credentials for each of those folders so you can provide yours and your wife's.

**Comment by vitobotta** [comment]
Do I have to enter the credentials/token each time or can I add this to cron so it updates the backup daily?

**Comment by gilesknap** [comment]
The tokens are stored in each root folder. Thus after the initial setup,
you can create a cron that syncs both folders by running gphotos-sync
twice. And you could do it in parallel. And if the cron job takes a long
time and runs twice the second instance will exit cleanly due to the lock
file!

**Comment by vitobotta** [comment]
Wonderful, thanks a lot for your help! I'll close this :)
